### ISSUE TITLE
Fast Charing Map Charger are lost. 

### ISSUE THREAD

**Issue by brau01ma** [bassmaster187/TeslaLogger#1009]
Auf der Seite [Fast Charging Map 6](https://teslalogger.de/map.php) werden keine Supercharger usw. mehr angezeigt.

**Comment by brau01ma** [comment]
![2023-05-08_15h48_48](https://user-images.githubusercontent.com/67189473/236840943-0731fdcd-b218-4ff8-a579-bcb34e55aa8e.png)

**Comment by bassmaster187** [comment]
It seems like it uses more than 256MB Ram on the server, so it will be blocked. I increased the amount of max memory, but that's just a temporary solution. I Have to filter the data depending the zoom factor an position on the map.

**Comment by brau01ma** [comment]
Die Map ist so natürlich auch überhaupt nicht nutztbar.. lädt sehr lange oder crasht.

**Comment by Adminius** [comment]
@bassmaster187 geht (wieder) nicht :/

**Comment by bassmaster187** [comment]
Geht.
![image](https://github.com/bassmaster187/TeslaLogger/assets/6816385/cafe01a0-ce41-4dcb-b8dd-2f86049ba307)
