### ISSUE TITLE
Daten aus cFos Wallbox (cFos Charging Manager) auslesen und für Ladestatistik nutzen

### ISSUE THREAD

**Issue by Schimi1983** [bassmaster187/TeslaLogger#1011]
Hi,

wäre es möglich die cFos Wallbox (den Charging Manager) "anzuzapfen" und die Daten z.b. kWh, davon PV, etc für die Laedehistiroe zu nutzen?

Gerade in verbindung mit PV-Überschussladen würde das eine schöne statistik bedeuten... Der weg über nen Shelly 3EM ist da sehr fehlerbehaftet...

Ich würde da auch in rahmen der möglichkeiten unterstützen...

![image](https://user-images.githubusercontent.com/4581474/236694188-b6d3f7c6-b228-4d81-9da0-d927d45d484c.png)

![image](https://user-images.githubusercontent.com/4581474/236694194-fd2e4881-1a63-4f58-a484-cc9926d56ddb.png)

**Comment by Adminius** [comment]
Gibt es da eine Schnittstelle und eine Beschreibung dazu?

**Comment by Schimi1983** [comment]
würde das schonmal was bringen?

https://www.cfos-emobility.de/de/cfos-charging-manager/documentation/mqtt.htm

habe ach mal beim hersteller angefragt

**Comment by bassmaster187** [comment]
Ich schaue mir das nächste Woche mal an, aber dazu müsste ich mal auf das System drauf und brauche ein Mitschnitt ohne Ladung und mit Ladung. Ruf mich einfach nächste Woche mal an: https://www.impala64.de/blog/kontakt/

**Comment by ThmsD** [comment]
Gibt auch ein HTTP API: https://www.cfos-emobility.de/de/cfos-power-brain/http-api.htm

**Comment by Adminius** [comment]
@Schimi1983 @ThmsD 
Hilft mir mal die Sache zu verstehen:
cFos ist eine Wallbox oder ein Device zum Steuern einer Wallbox?
wenn ich mir die HTTP API anschaue, muss man meter1 oder meter2 angeben. 
Das weiß dann der User was meter1 oder meter2 ist, richtig?
Mobusregister die man mitangeben muss, sind klar.

**Comment by Schimi1983** [comment]
so  jetzt habe ich Zeit :-)

die cFos Wallbox ist eine Wallbox vergleichbar mit der OpenWB (https://shop.cfos-emobility.de/products/cfos-power-brain-wallbox-11kw)

es gibt auch noch den cFos charging Manager als windows version.... der ist im grunde auf allen wallboxen drauf und man kann den zum steuern anderer Wallboxen nutzen (ich vermute sowas wie evcc)....
https://www.cfos-emobility.de/de/cfos-charging-manager/download.htm

evse ist die wallbox und meter1 müsste der integrierte Zähler sein... keter 3, 4 etc. kann man auch selbst integrieren oder weitere Modbus, etc. zähler einbinden (habe z.B. nen Shell3EM damit die wallbox selbst das PV-überschussladen steuert)

Ich habe die wallbox im iobroker über modbus eingebunden... und stuere Sie (wenn ich es mal brauche) über http befehle

Ich mach mal ne parr Screenshots, vielleicht helfen sie dir weiter:

evse über modbus (iobroker)
![image](https://github.com/bassmaster187/TeslaLogger/assets/4581474/99542f6e-a7b5-4a40-98a7-1a67cdd02dba)


S0-Zähler über modbus (ionroker)
![image](https://github.com/bassmaster187/TeslaLogger/assets/4581474/5cf06be2-57fe-4be5-a58a-1db586402217)

Screenshots der benutzeroberfläche:
![image](https://github.com/bassmaster187/TeslaLogger/assets/4581474/9c999cf3-a417-48e1-be42-e37a039d8807)

leider habe ich letztens die ladevorgänge resettet... sonst wäre hier eine anzeige... wieviel geladen wurde, wielange, wieviel über PV und netzbezug
![image](https://github.com/bassmaster187/TeslaLogger/assets/4581474/afecd3b5-4579-4a8f-a4a0-9042ab3973a2)

**Comment by Adminius** [comment]
Ah, ok, also müsste man einen (nur Wallbox) oder 2 Meter (Wallbox+Netz= PV Anteil) auslesen.
Klingt einfach, ich melde mich noch mal wenn ich mich eingelesen habe

**Comment by pseudoreal247** [comment]
würde es auch begrüßen, wenn man die Effizienz mit Hilfe der cfos in Teslalogger einbauen könnte.

**Comment by Adminius** [comment]
Ich brauche antworten (JSON) von diesen Endpoints (bitte die IP anpassen):
http://192.168.2.111//cnf?cmd=get_dev_info
http://192.168.2.111/cnf?cmd=modbus&device=meter1&read=8058
http://192.168.2.111/cnf?cmd=modbus&device=evse&read=8004
http://192.168.2.111/cnf?cmd=modbus&device=evse&read=8092

**Comment by Schimi1983** [comment]
[8058q.json](https://github.com/bassmaster187/TeslaLogger/files/14451871/8058q.json)

**Comment by Schimi1983** [comment]
[meter1_all.json](https://github.com/bassmaster187/TeslaLogger/files/14452285/meter1_all.json)
[evse_all.json](https://github.com/bassmaster187/TeslaLogger/files/14452287/evse_all.json)

**Comment by Schimi1983** [comment]
http://192.168.20.148/cnf?cmd=modbus&device=evse&read=8058q

gibt die insgesamt geladen kwh der Wallbox aus.... wenn du meter1 nimmst dann die gesamt kwh des modbus zählers (bei mir wohl unterschiedlioch da ich die box mal auf werkseinstellung zurück gesetzt habe

**Comment by Adminius** [comment]
so, die [md=get_dev_info](http://192.168.2.111//cnf?cmd=get_dev_info) gefällt mir am besten, da sind auch die "externen" Zähler dabei, auch wenn cFos sagt, dass die API sich ohne vorwarnung verändern kann, gehen wir mal dahin.
Jetzt muss du mir noch mal helfen:
Device M3, "EM3 am Hausanschluss" was ist das? Netzzähler? er hat "import": 9766409, [Wh] => 9766, 409 kWh, Ist das richtig? 
Device E1, "cFos Power Brain 11kW", das ist die Wallbox selbst, richtig? "import": 628277, [Wh] => 628,277 kWh, Ist das richtig?
Device E1 hat auch noch unter evse -> "charging": false, schaue ob es auf true steht wenn das Auto lädt (am besten noch eine json beim Laden erzeugen)

M1 und M2 sind für uns egal nehme ich mal an, richtig?
Ich nehme auch an, dass E1 immer die Wallbox ist, man kann also hardcoden, oder? M3 oder M2/M1 muss aber schon vergeben.
Oder auch E1 flexibel machen?

ich fange dann schon mal an :)

**Comment by Schimi1983** [comment]
Dann hole ich mal aus und hoffe alles beantworten zu können :-)

- Device M3 ist ein Shelly 3EM (mir ist gar nicht aufgefallen das ich da nen dreher seit über 2 Jahren drin habe) der am Netzübergabepunkt direkt hinter dem Stromzähler den verbrauch (und einspeisung) misst.
Dadurch weiss die Box wieviel bezogen bzw. wieviel eingespeist wird( um PV-überschuss laden zu ermöglichen)
Wenn ich z.B. mit 11kw lade und bezug ist nur 2kw weiss die Box das 9Kw aus Solar kommen und regelt es entsprechend runter das es nach möglichkeit nur 0 W bezug sind.
Der import ist richtig..., das ist aber nicht der import der Wallbox sondern des gesamten hauses seit letztem reset (oder einbau)

[get_dev_info.txt](https://github.com/bassmaster187/TeslaLogger/files/14461494/get_dev_info.txt)
während das Auto geladen hat

- Device M4  ist auch nen Shelly 3EM der direkt vor der Wallbox misst. Dadurch erkennt die Wallbox wieviele Phasen benutzt werden und passt die PV-Überschuss regelung entsprechend an). Müsste aber ein spezialfall (spieltrieb und ich schalte mal eine bzw. zwei Phasen aus um besser die PV- Anlage auszunutzen) bei mir sein und sonst unnötig...

- Device E1, das ist die Wallbox... import hast du richtig erkannt

- M1 und M2 sind die integrierten Zähler eingänge... an M1 ist bei mir der Modbus zähler (ich vermute die neuen Versionen haben den auch so angeschlossen). Ich bin mir zu 99,99% das die evse sich daraus auch ihren import errechnet.
Sollte also für "uns" uninteressant sein da der Wert unter E1 ausgelesen werden kann.

- M3 als Netzzähler, siehe weiter oben... sollte erklären woraus die Box das herleitet...
""role":2", ist "Netzbezug", also ja, der Netzzähler am Hausanschluss

-zum Thema "Solar", die box bietet auch die möglichkeit Wechselrichter oder Zähler am Wechselrichter einzubinden um da auch eine PV-Überschuss ladung zu ermögichen... da führen am ende mehrere wege nach "Rom"....
Die idee sich an get_dev_info zu orientieren ist wahrscheinlich am besten... die zähler kann jeder user selber definieren und teilweise auch mit formeln verändern.
die Wallbox ist recht mächtig/flexiebel... macht dadurch aber auch wahrscheinlich probleme :-)

**Comment by Adminius** [comment]
"phases": 7, nicht schlecht :D 

Danke, damit kann ich arbeiten, ich melde mich wieder die Tage

**Comment by Schimi1983** [comment]
Frag mich nicht wie der drauf kommt :-)

Es funzt alles wie es soll, aber ich bin mir sicher ich habe nur 3 Phasen :D

**Comment by Schimi1983** [comment]
Habe hier mal bei cfos die frage im Community bereich erstellt

https://www.cfos-emobility.de/network/antworten/ladevorgaenge-ueber-http-api-auslesen/#answer-1468

man kann auch die jungs direkt per mail (kontaktformular) anschrieben. Als ich nur aktiver war, haatte ich einiges mit denen zutun. waren sehr hilsbereit und haben sachen auch umgesetzt

**Comment by Adminius** [comment]
@Schimi1983 wenn es released wird, bitte testen und Rückmeldung geben.
ich habe zwar mit einem MockupServer entwickelt, aber reale Daten sind besser zum Testen ;)

**Comment by Schimi1983** [comment]
wenn ich die Ip adresse eingebe, dann kommt nur das im Log?

`12.03.2024 16:55:54 : System.NullReferenceException: Object reference not set to an instance of an object.
at TeslaLogger.WebServer.Admin_Wallbox (System.Net.HttpListenerRequest request, System.Net.HttpListenerResponse response) [0x002c2] in <2539df6baea14424abe174fc5256b02b>:0
12.03.2024 16:56:23 : Wallbox
12.03.2024 16:56:23 : Wallbox
12.03.2024 16:56:23 : Test Wallbox
12.03.2024 16:56:23 : System.NullReferenceException: Object reference not set to an instance of an object.
at TeslaLogger.WebServer.Admin_Wallbox (System.Net.HttpListenerRequest request, System.Net.HttpListenerResponse response) [0x002c2] in <2539df6baea14424abe174fc5256b02b>:0
12.03.2024 16:56:32 : Wallbox
12.03.2024 16:56:32 : Test Wallbox
12.03.2024 16:56:32 : System.NullReferenceException: Object reference not set to an instance of an object.
at TeslaLogger.WebServer.Admin_Wallbox (System.Net.HttpListenerRequest request, System.Net.HttpListenerResponse response) [0x002c2] in <2539df6baea14424abe174fc5256b02b>:0
12.03.2024 16:56:43 : Wallbox
12.03.2024 16:56:43 : Test Wallbox
12.03.2024 16:56:43 : System.NullReferenceException: Object reference not set to an instance of an object.
at TeslaLogger.WebServer.Admin_Wallbox (System.Net.HttpListenerRequest request, System.Net.HttpListenerResponse response) [0x002c2] in <2539df6baea14424abe174fc5256b02b>:0
12.03.2024 16:56:45 : Wallbox`


muss man sich vielleicht einloggen?

**Comment by Adminius** [comment]
es gibt noch kein Release auch wenn cFos schon auswählbar ist ;)

**Comment by Schimi1983** [comment]
ok...  dann hätte ich nicht sofort "aktualiesieren" müssen 🗡️ 
Ich warte und meld vollzug wenn es soweit ist :-)

**Comment by Schimi1983** [comment]
So hat sich selber 2geupdated" :-)

beim auf "test" drücken, passiert nichts... nur im Log steht:

`14.03.2024 21:20:13 : System.NullReferenceException: Object reference not set to an instance of an object.
at TeslaLogger.WebServer.Admin_Wallbox (System.Net.HttpListenerRequest request, System.Net.HttpListenerResponse response) [0x002c2] in <2539df6baea14424abe174fc5256b02b>:0`

**Comment by Adminius** [comment]
Change log haben wir vorbereitet und dann einen Bug gefunden, dadurch kleine Verzögerung...

**Comment by Adminius** [comment]
@Schimi1983 jetzt bis du dran ;)

**Comment by pseudoreal247** [comment]
Was muss man denn als Param eingeben? Ich möchte, dass die Werte des Ladevorgangs und die effizienz im TL angezeigt werde?

**Comment by pseudoreal247** [comment]
dann kommt bei https folgende Fehlermeldung:
15.03.2024 13:40:24 : System.Net.WebException: The operation has timed out.
at System.Net.HttpWebRequest.RunWithTimeoutWorker[T]
(System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout,
System.Action abort, System.Func`1[TResult] aborted,
System.Threading.CancellationTokenSource cts) [0x000f8] in
<9c6e2cb7ddd8473fa420642ddcf7ce48>:0
at System.Net.HttpWebRequest.GetResponse () [0x00016] in
<9c6e2cb7ddd8473fa420642ddcf7ce48>:0
at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request)
[0x00000] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0
at System.Net.WebClient.DownloadBits (System.Net.WebRequest request,
System.IO.Stream writeStream) [0x000e6] in
<9c6e2cb7ddd8473fa420642ddcf7ce48>:0
at System.Net.WebClient.DownloadDataInternal (System.Uri address,
System.Net.WebRequest& request) [0x00061] in
<9c6e2cb7ddd8473fa420642ddcf7ce48>:0
at System.Net.WebClient.DownloadString (System.Uri address) [0x00011] in
<9c6e2cb7ddd8473fa420642ddcf7ce48>:0
at System.Net.WebClient.DownloadString (System.String address) [0x00008] in
<9c6e2cb7ddd8473fa420642ddcf7ce48>:0
at (wrapper remoting-invoke-with-check)
System.Net.WebClient.DownloadString(string)
at TeslaLogger.ElectricityMeterCFos.GetCurrentData () [0x00071] in
<5cae15e473184a859e46bebb9844ec5c>:0

http funktioniert:
15.03.2024 13:44:34 : Wallbox
15.03.2024 13:44:34 : Wallbox
15.03.2024 13:44:34 : Test Wallbox


[image: image.png]

Am Fr., 15. März 2024 um 13:21 Uhr schrieb Eugen ***@***.***>:

**Comment by Adminius** [comment]
Alles nach einander:
Was genau hast du im Feld "Host:" eingetragen.
Wenn du auf "Test" Button klickst, werden da Daten angezeigt?

**Comment by pseudoreal247** [comment]
im host habe ich entweder:
* https://192....
oder
* http://192....

Nun scheint es zu funktionieren

Am Fr., 15. März 2024 um 13:53 Uhr schrieb Eugen ***@***.***>:

**Comment by Adminius** [comment]
mit https nie getestet. Dafür habe ich keine Möglichkeit.
Es freut mich wenn es funktioniert :)

**Comment by Schimi1983** [comment]
Es funzt alles :-)

![image](https://github.com/bassmaster187/TeslaLogger/assets/4581474/d52b4406-b098-48a8-960e-05c5d4ee88fe)

und vor allem der PV überschuss wird nicht angezeigt (mir war nicht klar dass du das auch hinbekommst 👍 )
![image](https://github.com/bassmaster187/TeslaLogger/assets/4581474/18271615-aca0-4f02-a518-66ebceef09da)

**Comment by Adminius** [comment]
Sobald man Utility und Vehicle Zählerstände hat, kann man PV Überschuss berechnen 😉

**Comment by Schimi1983** [comment]
ah das geht dann in meinem fall weil ich die entsprechenden zähler habe? oder war das aus der "get_dev_info" ersichtlich?
Ich frage nur für mich aus neugier, weil ichh das auch durchgeschaut habe und nicht fuündig geworden bin (war auch von den ganzen Infos "erschlagen") :-)

**Comment by Adminius** [comment]
Steht alles in get_dev_info :)
"role": 3 tut die Magie ;) (das ist der Bezugszähler)
