### ISSUE TITLE
Support for MariaDB 10.11+

### ISSUE THREAD

**Issue by sgaert** [bassmaster187/TeslaLogger#1040]
Ich verwende den Teslalogger mit meiner zentralen Datenbank auf meinem Serversystem.

Die Datenbank habe ich auf Version 10.11.3 aktualisiert und der Teslalogger konnte sich nicht mit der Datenbank verbinden.

Nach einigen Recherchen war die verwendete Libary MySql.Data.MySqlClient das Problem, ich habe das Projekt auf MySqlConnector aktualisiert und nun kann der Teslalogger die MariaDB 10.11.3 verwenden.

Nur an 2 Stellen im Code sind Probleme offen (if (ex.ErrorCode == -2147467259)), die Quelle von -2147467259 ist mir unbekannt.

Die Rückwärtskompatibilität der MySqlConnector Bibliothek ist nicht geprüft, bei Bedarf kann ich einen zweiten Docker aufsetzen, wo ich die interne Datenbank verwende.

**Comment by bassmaster187** [comment]
passt das: https://github.com/bassmaster187/TeslaLogger/commit/cb7fefd2b839f851080f25ab66d4b1c117a981be

Welche zwei stellen sind das genau?

**Comment by sgaert** [comment]
richtig war bei mir auch so. Daher der switch von MySql.Data auf MySqlConnector.

Ich hatte dann noch probleme mit:
Cars.cs Zeile 929 
DBHelper.cs Zeile 1371

Da ex.ErrorCode dann nur ein Object sein kann und kein int.

**Comment by Funy17** [comment]
Ich habe das gleiche Problem wie "sgaert". Mein TL läuft auf UBUNTU 16.04  , die Datenbank Vers. 10.11.6 auf einem externen Rechner.
Wie kann ich den MySqlConnector aktualisieren?

**Comment by Funy17** [comment]
Kann mir jemand bitte die  MySqlConnector Bibliothek (Dateien) für die MariaDB 10.11.x  zur Verfügung stellen ? Diese Dateien liegen wohl innerhalb des \teslalloger .  BITTE.

**Comment by superfloh247** [comment]
hat MariaDB keinen "compatibility mode" für ältere Clients?

**Comment by superfloh247** [comment]
wir verwenden den hier

https://dev.mysql.com/downloads/connector/net/

und da gibt's nix neueres als das was wir mitliefern

**Comment by Funy17** [comment]
Danke, ich checke es.

Gruß
Reinhard 

Am 15.12.2023 um 14:28 schrieb superfloh247 ***@***.***>:

﻿
wir verwenden den hier

https://dev.mysql.com/downloads/connector/net/

und da gibt's nix neueres als das was wir mitliefern

**Comment by Funy17** [comment]
Leider gibt es mit der MariaDB kein zurück mehr. Das DEBIAN auf der sie läuft ist zu neu.

@sgaert schreibt weiter oben:

Nach einigen Recherchen war die verwendete Libary MySql.Data.MySqlClient das Problem, ich habe das Projekt auf MySqlConnector aktualisiert und nun kann der Teslalogger die MariaDB 10.11.3 verwenden.

Also hat er die Programmdateien gefunden und erfolgreich installiert.

Hier aus https://dev.mysql.com/downloads/connector/net/  konnte ich nicht erfolgreich sein - schade.

Gruss
Reinhard





>>> ***@***.***> 15.12.2023 14:28 >>>
wir verwenden den hier

https://dev.mysql.com/downloads/connector/net/ 

und da gibt's nix neueres als das was wir mitliefern

‑‑ 
Reply to this email directly or view it on GitHub:
https://github.com/bassmaster187/TeslaLogger/issues/1040#issuecomment‑1857882993

**Comment by sgaert** [comment]
Ich kompiliere den TL seit dem Problem bei mir selbe und tausche die exe aus.
Im ende mache ich es wie shadowstrike114 es hier beschreibt. https://github.com/shadowstrike114/TeslaLogger/commit/e885269b9bfce6aa32a1a7005840dfc9f013e322

**Comment by Funy17** [comment]
Oh, das kann ich leider wegen fehlender Kenntnisse nicht.

Könnte ich von dir die Dateien bekommen?

Am 15.12.2023 um 19:13 schrieb sgaert ***@***.***>:

﻿
Ich kompiliere den TL seit dem Problem bei mir selbe und tausche die exe aus.
Im ende mache ich es wie shadowstrike114 es hier beschreibt. ***@***.***

**Comment by Funy17** [comment]
Hallo,
ist es möglich dass ich für meinen TL auf Ubuntu 16.04 auch diese Dateien ( .EXE ) bekomme. Dann kann ich den TL wieder mit der Datenbank mariaDB 10.11.x betreiben?

Vielen Dank 
Reinhard 

Am 15.12.2023 um 19:13 schrieb sgaert ***@***.***>:

﻿
Ich kompiliere den TL seit dem Problem bei mir selbe und tausche die exe aus.
Im ende mache ich es wie shadowstrike114 es hier beschreibt. ***@***.***

**Comment by Funy17** [comment]
Hallo zusammen,
ich komme einfach nicht weiter. 
Welche Dateien muss ich wo austauschen um den Teslalogger mit der sqlDatenbank 10.11.4 zu verbinden?
Kann mir wirklich niemand helfen?
Schade.

**Comment by sgaert** [comment]
Seit einer der letzten Version geht MariaDB 10.11.8 wie der ohne Anpassungen. Kann erstmal geschlossen werden.
