### ISSUE TITLE
Tesla supercharging table is not been updating

### ISSUE THREAD

**Issue by shankarc** [bassmaster187/TeslaLogger#1047]
The tesla super charging is not  been updating ( teslalogger.teslacharging  table) lately. I have charged recently, but it does no appear in the table

![image](https://github.com/bassmaster187/TeslaLogger/assets/1361636/767fdb84-e6e6-471f-aa0c-b9a2b7a6882b)

**Comment by superfloh247** [comment]
fixed with 1.54.22.0 - please update

**Comment by shankarc** [comment]
Thanks

**Comment by superfloh247** [comment]
is it fixed?

**Comment by shankarc** [comment]
Yes, It's fixed thanks
