### ISSUE TITLE
Update auf 1.54.23.0 will nicht installiert werden…

### ISSUE THREAD

**Issue by albi** [bassmaster187/TeslaLogger#1048]
Wenn ich auf Aktualisierung klicke, passiert rein gar nichts. Die gewohnte Reboot-Meldung erscheint, nach kurzer Zeit erscheint wieder das Dashboard und mir wird wieder die 1.54.23.0 angeboten.

**Comment by superfloh247** [comment]
log file or it didn't happen

**Comment by bassmaster187** [comment]
Ich habs nochmal kompiliert und eingecheckt. Bitte nochmal updaten

**Comment by albi** [comment]
ja ging jetzt.
