### ISSUE TITLE
Grafana Status Seite Odometer & Reichweite funktioniert nicht mehr

### ISSUE THREAD

**Issue by dbmtrde** [bassmaster187/TeslaLogger#1052]
Grafana Status Seite Odometer & Reichweite funktioniert nicht mehr.
Current Status wird in Grafana Online angezeigt, obwohl in Teslalogger als "Einschlafen" zeigt.

**Comment by bassmaster187** [comment]
Habs gerade bei mir ausprobiert. Es scheint zu funktionieren.
![image](https://github.com/bassmaster187/TeslaLogger/assets/6816385/23f964bc-2837-423b-bbaf-8ea166715823)

Aber das Model 3 von meiner Frau wird genauso angezeigt, wie du es sagst. Vermutlich weil es seit mehreren Tagen nicht mehr bewegt wurde. Stell mal den Zeitraum um, dann sollte es gehen, wenn dein Fahrzeug auch mehrere Tage nicht bewegt wurde.

![image](https://github.com/bassmaster187/TeslaLogger/assets/6816385/abead74d-f2ff-4ee5-b757-1f2c3ef7b7bf)

![image](https://github.com/bassmaster187/TeslaLogger/assets/6816385/14705ab2-496f-4f09-bbff-8a3d1609cc1e)

**Comment by dbmtrde** [comment]
Danke für den Hinweis, hast recht, sobald man Timeframe ändert, dann funktioniert es wieder. Kann die Abfrage ggf. optimiert werden, sodass letzte bekannte km stand dort angezeigt wird?
