### ISSUE TITLE
Geofence Seite funktioniert nicht

### ISSUE THREAD

**Issue by dbmtrde** [bassmaster187/TeslaLogger#1053]
Geofence Seite /admin/geofencing.php seite wird als leer angezeigt.

**Comment by bassmaster187** [comment]
https://github.com/bassmaster187/TeslaLogger/commit/680011bf47b94088de6e68b5de86c599524b1334

**Comment by bassmaster187** [comment]
Bitte manuell updaten.

**Comment by dbmtrde** [comment]
Hat geklappt, Danke :)
