### ISSUE TITLE
Überlappende Ladestandorte Total Alsfeld / SuC Alsfeld

### ISSUE THREAD

**Issue by rowich** [bassmaster187/TeslaLogger#1054]
Kollege meldet mir, dass sein SuC Ladevorgang auf der Raststätte Pfefferhöhe/Alsfeld als Ladevorgang bei Total Energies gespeichert wurde:
https://teslalogger.de/charging_time.php?id=222450

Ich finde weder einen SuC Alsfeld noch einen SuC Pfefferhöhe. Allerdings scheint der Radius "80" zum Total-Ladepunkt auch deutlich zu gross zu sein. Lässt sich anhand des Links oben der SuC korrekt erfassen und der Total-Ladepunkt sinnvoll verkleinern?

![image](https://github.com/bassmaster187/TeslaLogger/assets/49855876/550978b3-c6fa-496e-b1c4-a57094b7872d)

Ich vermute mal, dass sich trotz Korrektur die Angabe in der Ladehistory nicht mehr ändern wird. Korrekt?

**Comment by beckerstef** [comment]
Total Ladestation scheint zusätzlich auch einen falschen Mittelpunkt zu haben, wenn man sich die paar Ladungen unten rechts im Bildausschnitt anschaut.
<img width="1275" alt="Bildschirmfoto 2023-06-08 um 14 32 33" src="https://github.com/bassmaster187/TeslaLogger/assets/37812574/bc74aa4a-07ec-4a5a-8833-705b1b6dad30">

**Comment by rowich** [comment]
Sollte mit Pull Request 1056 gelöst sein. Ich habe versucht, das im rechten Panel zu verlinken, habe das aber nicht hinbekommen.
https://github.com/bassmaster187/TeslaLogger/pull/1056

**Comment by rowich** [comment]
Konnte mit https://github.com/bassmaster187/TeslaLogger/pull/1056 erfolgreich gelöst werden.

![image](https://github.com/bassmaster187/TeslaLogger/assets/49855876/776f64fb-ea36-4df7-b88b-e9b0c793160f)
