### ISSUE TITLE
Apostrophe im Charger-Namen verhindert setzen der Ladekosten

### ISSUE THREAD

**Issue by sclub** [bassmaster187/TeslaLogger#1057]
Bei der Adresse "fr-26140 Saint-Rambert-d'Albon, Route des Fouillouses Nord" kann ich keine Ladekosten setzen, der Klick auf "Set" führt zu einer Seite, bei der alles leer ist.

![image](https://github.com/bassmaster187/TeslaLogger/assets/12498295/ea18a23a-60f5-4d64-98c5-d7816e0cb5a1)

![image](https://github.com/bassmaster187/TeslaLogger/assets/12498295/13436031-05da-4edb-97d9-925284c2f479)

Da es bei allen anderen Einträgen bisher immer ging, ist meine starke Vermutzung, dass es am ' liegt.

**Comment by bassmaster187** [comment]
Bitte manuelles update machen und nochmal testen.
