### ISSUE TITLE
Synology docker 

### ISSUE THREAD

**Issue by ramonsmits** [bassmaster187/TeslaLogger#107]
I'm trying to setup a TeslaLogger as a docker image on my Synology NAS but failing. Anyone had any success?

Docker version 18.09.8, build 2c0a67b
docker-compose version 1.24.0, build 0aa59064

The docker version probably is too old but I'm not sure if the error is docker related

```
database uses an image, skipping
grafana uses an image, skipping
webserver uses an image, skipping
Building teslalogger
Step 1/5 : FROM mono:6.0.0.313
 ---> 43761a6b9c3c
Step 2/5 : RUN echo "Europe/Berlin" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
 ---> Using cache
 ---> a2560d071073
Step 3/5 : RUN apt-get update &&   apt-get install -y --no-install-recommends git &&   apt-get install -y --no-install-recommends mariadb-client &&   apt-get clean &&   apt-get autoremove -y &&   rm -rf /var/lib/apt/lists/* &&   echo "export TERM=xterm" >> /root/.bashrc  &&   echo "DOCKER" >> /tmp/teslalogger-DOCKER
 ---> Running in 2cae1453af81
Err:1 http://security.debian.org/debian-security stretch/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:2 http://deb.debian.org/debian stretch InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://download.mono-project.com/repo/debian stable-stretch/snapshots/6.0.0.313 InRelease
  Temporary failure resolving 'download.mono-project.com'
Err:4 http://deb.debian.org/debian stretch-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://download.mono-project.com/repo/debian/dists/stable-stretch/snapshots/6.0.0.313/InRelease  Temporary failure resolving 'download.mono-project.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package git
ERROR: Service 'teslalogger' failed to build: The command '/bin/sh -c apt-get update &&   apt-get install -y --no-install-recommends git &&   apt-get install -y --no-install-recommends mariadb-client &&   apt-get clean &&   apt-get autoremove -y &&   rm -rf /var/lib/apt/lists/* &&   echo "export TERM=xterm" >> /root/.bashrc  &&   echo "DOCKER" >> /tmp/teslalogger-DOCKER' returned a non-zero code: 100
```

**Comment by fatfurrycat** [comment]
Hi, 

I've managed to get this working with the same versions of docker as you're using. 
I'm running on DSM 6.1.7-15284 Update 3. YMMV on other versions. 

1) From Synology Package Centre, install both Docker and Git Server. 
2) Once installed, click on each package and ensure that they are in the 'Running' state. 
3) SSH to your Synology and login as 'admin'. 
4) When you're logged in, type 'sudo -i' and become root user. The password is the same as admin.
5) In Package Centre, click on Docker, and check the 'Installed Volume'. Make a note of it. 
6) In your SSH session, cd to this volume. e.g. cd /volume1/docker
7) Run git clone https://github.com/bassmaster187/TeslaLogger in the Terminal. 
8) When finished, follow rest of instructions here: https://github.com/bassmaster187/TeslaLogger/blob/master/docker_setup.md

The above page mentions the following to test:
Try to connect to Grafana with you favorite browser: http://localhost:3000 (admin/admin)

This is incorrect for Synology. The URL should be http://synology ip:3000
e.g. http://192.168.0.100:3000
The username is admin, but the password is teslalogger. 

This should get you up and running on Synology. I'm still testing, and will update if I find any issues. 

So far, I've been able to capture journey data, and also charging, so it's looking good.

**Comment by bassmaster187** [comment]
I try it on my DS718plus and it seems like it works fine.

https://github.com/bassmaster187/TeslaLogger/blob/master/docker_setup_synology.md
