### ISSUE TITLE
Aktuelles Update gemacht aber die Meldung "Bitte aktualisieren Sie auf die neueste docker-compose.yml-Datei…" verschwindet nicht…

### ISSUE THREAD

**Issue by albi** [bassmaster187/TeslaLogger#1070]
habe im terminal auch docker aktualisiert nach der anleitung in dem link der meldung. dennoch erscheint die meldung ich müsste docker-compose.yml aktualisieren.

@bassmaster187

**Comment by bassmaster187** [comment]
Welche Grafana Version wird jetzt angezeigt?

**Comment by albi** [comment]
uff ich komme auf keines der dashboards. grafana scheint gar nicht zu laufen.

**Comment by albi** [comment]
@bassmaster187 Bin schon auf Buster seit langem. Die Teslalogger Instanz wurde auch schon auf Buster installiert. Hab eben grad noch die Update Infos dazu gesehen, die mich aber nicht betreffen.

**Comment by bassmaster187** [comment]
was sagt denn das logfile vom Grafana Container?

**Comment by albi** [comment]
kannst du mir helfen wo ich das finde? oder das normale log file? soll ich das posten?

**Comment by bassmaster187** [comment]
docker logs teslalogger-grafana-1

**Comment by albi** [comment]
Kannst du mir etwas mehr Infos geben wo ich das eingeben soll? Sorry ich bin nicht bewandert mit Docker/Grafana usw.

**Comment by bassmaster187** [comment]
Das ist einfach ein Befehl um das Logfile auszugeben. Das kannst du überall in der Eingabeaufforderung / Terminal eingeben

**Comment by albi** [comment]
Error response from daemon: No such container: teslalogger-grafana-1 kommt da bei mir

**Comment by albi** [comment]
nach einigem hin und her hab ich es nun aber geschafft. hab nochmal die rechte an grafana eingestellt und das update nochmal laufen lassen. nun ist die meldung weg und teslalogger ist aktuell.
