### ISSUE TITLE
backup.sh not executable since upgrade to 1.54.25.0 via docker

### ISSUE THREAD

**Issue by carposio** [bassmaster187/TeslaLogger#1072]
**Describe the bug**
I upgraded teslalogger to 1.54.25.0 today by following the docker upgrade instructions. Grafana failed to start but running the `chmod`   command as described in the upgrade instructions fixed Grafana. Afterwards, I ran a backup as usually but it somehow failed with a permission error  as well, see below.

Running the following commands fixed the issue for me:
```
chmod a+x TeslaLogger/bin/backup.sh
docker compose build
docker compose up -d
```

**To Reproduce**
Running the backup command via docker:
`docker exec -it teslalogger-teslalogger-1 /etc/teslalogger/backup.sh`
shows this error message:
`exec failed: unable to start container process: exec: "/etc/teslalogger/backup.sh": permission denied: unknown`

**Expected behavior**
Docker backup command succeeds

** Teslalogger Type **
Docker

** Do you use Tasker or iBeacon **
no

**Comment by Magwua** [comment]
I ran the backup command from the website/portal top green bar after a clean install and then restore of my DB. The backup worked without issue. (ps. thanks for reminding me to make a fresh backup)

**Comment by carposio** [comment]
I followed the docker update instructions just now and it seems to be working fine now. Might have been a temporary issue
