### ISSUE TITLE
Eingabe "Kosten pro Ladung" Validation-Fehler

### ISSUE THREAD

**Issue by albi** [bassmaster187/TeslaLogger#1074]
Aktuellstes TeslaLogger und auch sonst alles aktuell. Ich versuche via Safari 16.5.1 (latest) auf macOS (latest) die Eingabe der Gesamtkosten. Das wirft bei mir Fehler aus. Vermutlich die Validation auf dem Feld zu scharf oder falsch eingestellt. Egal ob ich das mit Komma oder Punkt eingebe, es funktioniert nicht.

<img width="595" alt="Bildschirmfoto 2023-06-29 um 21 05 16" src="https://github.com/bassmaster187/TeslaLogger/assets/89451/3f573368-725c-4b8d-9fa9-b4c5109c3640">

**Comment by albi** [comment]
Chrome gibt mehr Infos. Scheint als wären nur Integer erlaubt.

<img width="603" alt="Bildschirmfoto 2023-06-29 um 21 10 22" src="https://github.com/bassmaster187/TeslaLogger/assets/89451/8be02680-4d6b-4c50-9156-d5a146bd8f7a">

**Comment by albi** [comment]
@bassmaster187 

Ziemlich dringendes Problem

**Comment by bassmaster187** [comment]
bitte manuelles update machen und nochmal testen

**Comment by albi** [comment]
Funktioniert nun wieder.
