### ISSUE TITLE
Show in admin panel if Teslalogger is waiting for car to go to sleep

### ISSUE THREAD

**Issue by bassmaster187** [bassmaster187/TeslaLogger#108]
05.01.2020 17:55:53 : Waiting for car to go to sleep 1
05.01.2020 17:56:56 : Waiting for car to go to sleep 2
05.01.2020 17:57:57 : Waiting for car to go to sleep 3
05.01.2020 17:59:00 : Waiting for car to go to sleep 4
05.01.2020 18:00:01 : Waiting for car to go to sleep 5
05.01.2020 18:01:04 : Waiting for car to go to sleep 6
05.01.2020 18:02:05 : Waiting for car to go to sleep 7
05.01.2020 18:03:08 : Waiting for car to go to sleep 8
05.01.2020 18:04:09 : Waiting for car to go to sleep 9
05.01.2020 18:05:12 : Waiting for car to go to sleep 10
05.01.2020 18:06:13 : Waiting for car to go to sleep 11
05.01.2020 18:07:16 : Waiting for car to go to sleep 12
05.01.2020 18:08:17 : Waiting for car to go to sleep 13
05.01.2020 18:09:20 : Waiting for car to go to sleep 14
05.01.2020 18:10:21 : Waiting for car to go to sleep 15
05.01.2020 18:11:24 : Waiting for car to go to sleep 16
05.01.2020 18:12:25 : Waiting for car to go to sleep 17
05.01.2020 18:13:28 : Waiting for car to go to sleep 18

**Comment by superfloh247** [comment]
I think this can be closed after the merge or pr 202
