### ISSUE TITLE
2023 M3 LR RWD wird als M3 SR+ LFP 2021	erkannt

### ISSUE THREAD

**Issue by tastbro** [bassmaster187/TeslaLogger#1122]
Teslalogger Version: 1.55.0.0

Mein 2023 M3 LR RWD wird falsch erkannt.
VIN: LRW3E7ES7PCXXXXXX

02.11.2023 04:28:04 : #1[Car_1:22]: Car: M3 SR+ LFP 2021 - 0.138 Wh/km
02.11.2023 04:28:04 : #1[Car_1:22]: VIN decoder: Model 3 2023 AWD:False MIC:True battery:NMC motor:n/a MIG:False

**Comment by bassmaster187** [comment]
Ist das der neue Highland?

**Comment by tastbro** [comment]
Nein, ist noch ein "alter".

**Comment by Ventusfahrer** [comment]
> Ist das der neue Highland?

Ich habe einen - wird der noch gesucht für irgendwelche Erkenntnisse?

**Comment by bassmaster187** [comment]
> > Ist das der neue Highland?
> 
> Ich habe einen - wird der noch gesucht für irgendwelche Erkenntnisse?

Ja, kannst du bitte ein mal von unter 50% auf 90% laden. Und schick mir bitte dein Tasker Token.

**Comment by bassmaster187** [comment]
Admin Panel / Einstellungen / ganz unten

**Comment by Ventusfahrer** [comment]
Alles klar.
Token kommt per E-Mail, der Rest wird wohl noch ein paar Tage dauern, habe heute Mittag gerade voll geladen...

Kann aber das Laden kurz per Mail oder Antwort hier ankündigen.

**Comment by Ventusfahrer** [comment]
Ich muss gleich nochmal weg. Danach hat er dann unter 50 % und wird dann geladen

**Comment by Ventusfahrer** [comment]
![image](https://github.com/bassmaster187/TeslaLogger/assets/5901190/d8d4e579-af9f-4e88-aae6-9486b1beb5d2)

d8c1501c

**Comment by Adminius** [comment]
@tastbro please test the newest version 1.57.1.0

**Comment by tastbro** [comment]
After the update my car is now correctly recognized, thank you very much! :)
