### ISSUE TITLE
ScanMyTesla / Tasker Token changed

### ISSUE THREAD

**Issue by rowich** [bassmaster187/TeslaLogger#1143]
Just detected that Teslalogger is no longer recording data from Teslalogger and checked the token value.
In SMT, I had years ago the typical 8 character code
In the Teslalogger settings, it's a new, different code with trailing _1

![image](https://github.com/bassmaster187/TeslaLogger/assets/49855876/9db9e9c7-dbfe-4a84-8f91-85679811ee0a)

**Comment by rowich** [comment]
Communication with Teslalogger und ScanMyTesla works again since I updated ScanMyTesla with the new, changed Token (inkluding _1). The value for "ScanMyTesla last received:" is still empty, no even weird data here

Question still open: Why did the token changed?

**Comment by rowich** [comment]
At least today after updating to 1.56.0 I realized, that my Taker Token used for ScanMyTesla has again changed. May (I am not using the car currently every day) also after last software update of the car (to 2023.44.30.9)

**Comment by rowich** [comment]
It happened again (probably after updating to v1.57), and it's again a token with trailing _1. I did not recorded the inital one, but it strongly looks like the same from dec-21

**Comment by rowich** [comment]
Just getting feedback from the swiss tesla community, that a couple of people seems to have the same issue. One just told me: I stopped using SMT, it's missing now too much data.

**Comment by bassmaster187** [comment]
I'll check it tonight

**Comment by bassmaster187** [comment]
fixed in 1.57.1

**Comment by rowich** [comment]
Thanks for the fix. I am going to observe this during the next days. For now I can confirm that the manual initiated update was successful and the registered token is the usual one without trailing "_1". No token change behaviour after restart and restart-update so far.
