### ISSUE TITLE
Logger not logging, Database connection not working

### ISSUE THREAD

**Issue by Scotty1928** [bassmaster187/TeslaLogger#1154]
** Append Logfile **
Logfile ist > 2 GB, daher auf meinem NAS: https://nas.justbackups.io/sharing/ix6S16s0V
Pw: bassmaster

**Describe the bug**
Fahrzeuge werden nicht mehr gelogged, Login zu Grafana unmöglich, Zugriff auf "/admin/password.php" wirft Fehlermeldung "errortext = 'Error: Connection refused - URL: http://localhost:5000/getallcars'"

**To Reproduce**
unbekannt

**Expected behavior**
Fahrzeuge sollen loggen, keine Fehlermeldungen, Grafana Login soll funktionieren

** Teslalogger Type **
Raspberry gekauft von emobility solutions

** Do you use Tasker or iBeacon **
Ja, Tasker

**Comment by Scotty1928** [comment]
Erhalte bei erneutem Zugriffsversuch auf "/admin/password.php" nun folgendes:

JSON Parse Error!
JSON:

**Comment by nsotnikov** [comment]
Habe bei einem Kollegen das selbe Verhalten gesehen, auf dem RPI 5 mit 6 GB Ram und letztem Docker sowie RaspiOS. Noch keine Lösung gefunden.

**Comment by bassmaster187** [comment]
Geht es mit der neuen Version?

**Comment by nsotnikov** [comment]
Ja. Wir haben es gelöst in dem wir das orig. Netzteil und eine schnellere SD-Karte genommen haben. Dann lief der Setup problemlos.
