### ISSUE TITLE
Geofence Seite lädt nicht mehr

### ISSUE THREAD

**Issue by albi** [bassmaster187/TeslaLogger#1159]
Nach dem letzten Update soeben komme ich nicht mehr auf die Geofence Seite. Es lädt schlichtweg nicht.

**Comment by sweidenbach** [comment]
Es gab ein Problem mit einem falschen Zeichen in der .csv das kürzlich adressiert wurde.
Mit dem aktuellen Stand, inkl. müsste es behoben sein:
https://github.com/bassmaster187/TeslaLogger/pull/1156

**Comment by albi** [comment]
ist behoben

**Comment by albi** [comment]
Nein irgendwie lädt die Geofence Seite doch nicht. Safari sagt die Webseite wird neu geladen weil ein Problem aufgetaucht ist. Danach versucht es Safari erneut und bricht ab. Chrome zeigt ein wenig der Geofence Seite an, aber bricht dann ab und nichts geht mehr. Ich kann links in de rListe nicht scrollen und gar nichts.

**Comment by bassmaster187** [comment]
Problem ist wohl, dass die geofence.csv (öffentliche Ladesäulen) sehr groß geworden ist und jetzt sehr lange braucht.

**Comment by bassmaster187** [comment]
mach mal bitte ein Update

**Comment by albi** [comment]
jetzt lädt es flott! sehe auch nur meine eigens angelegten geofences, war das vorher auch so?

**Comment by bassmaster187** [comment]
Nein, vorher hat er auch alle Ladesäulen angezeigt. Ich bin gerade dabei eine Lösung zu finden.

**Comment by albi** [comment]
Vielleicht einen Filter anlegen der erstmal nur die eigenen POIs lädt und dann die anderen auch sinnvoll gruppieren? Auswählen kann man aber nur eine Gruppe exklusiv. Würde auch insgesamt mehr Übersicht bringen. Das war schon sehr voll alles.

**Comment by sweidenbach** [comment]
Als "Verbrecher" der langen Liste, insb. in Deutschland würde ich auch eine sinnvolle Gruppierung je nach Zoomstufe vorschlagen.
ENBW hat das z.B. gut gelöst, siehe hier: https://www.enbw.com/elektromobilitaet/produkte/mobilityplus-app/ladestation-finden/map

**Comment by bassmaster187** [comment]
@sweidenbach Du bist schuld :-) 

Besser? 
![image](https://github.com/bassmaster187/TeslaLogger/assets/6816385/0e6adcec-fd2b-4853-92eb-3bee0fb98575)

**Comment by albi** [comment]
ach genau clustering macht natürlich auch sinn :)

**Comment by bassmaster187** [comment]
Kann geschlossen werden?

**Comment by albi** [comment]
von meiner seite ja
