### ISSUE TITLE
JSON parse error / DB connection refused

### ISSUE THREAD

**Issue by Scotty1928** [bassmaster187/TeslaLogger#1172]
Nicht so toll, wenn der Bug Report kommentarlos gelöscht wird, ich suche mir einen Wolf und zweifle an meinem Gedächtnis... Hilfe beim Lösen meines Problems brauche ich nämlich weiterhin.

Weiterhin auf /admin/password.php:
JSON Parse error

Ausserdem meldet er "DB connection refused" dutzende Male im Log: https://nas.justbackups.io/sharing/nbl7o8cmv

Passwort: bassmaster

Ich bin auch gerne bereit, eine erneute Spende zu machen, sobald der Logger wieder läuft. Das Ding ist für mich ziemlich wertvoll!

**Comment by bassmaster187** [comment]
Wir haben nichts gelöscht. Vermutlich ist was abhanden gekommen, als vor ein paar Tagen GitHub einen Ausfall hatte. 
Ich kann das Logfile nicht öffnen: Zip Ordner ist ungültig.

**Comment by Scotty1928** [comment]
Entschuldige meine falsche Verdächtigung bitte!
[logfile.zip](https://github.com/bassmaster187/TeslaLogger/files/14158551/logfile.zip)
Ich habe nun die logfile.zip erneut hochgeladen, nachdem ich sie auf Funktion geprüft habe.

**Comment by bassmaster187** [comment]
so wie es aussieht, funktioniert die Datenbank gar nicht mehr. Probier mal bitte das:
https://github.com/bassmaster187/TeslaLogger/blob/master/docs/en/faq.md#logfile-unable-to-connect-to-any-of-the-specified-mysql-hosts

**Comment by Scotty1928** [comment]
Ohman. Es hätte so einfach sein können. Ich muss mich wohl wirklich mal intensiv mit dem Thema beschäftigen, dann wäre ich gewandter... :joy:

Danke dir!
