### ISSUE TITLE
Wrong Update Informaion in Admin Panel after installing the TeslaFleetAPI

### ISSUE THREAD

**Issue by Ventusfahrer** [bassmaster187/TeslaLogger#1173]
![image](https://github.com/bassmaster187/TeslaLogger/assets/5901190/4cbb6b25-61ab-438b-a278-5f30b5f3d691)

I do not expect the 1.56.1.0 being an update for 1.56.4.0

**Comment by bassmaster187** [comment]
Fixed after update
