### ISSUE TITLE
Trip partly missing 

### ISSUE THREAD

**Issue by GerdMayer** [bassmaster187/TeslaLogger#1180]
** Append Logfile **
[logifile-missing-trip.txt](https://github.com/bassmaster187/TeslaLogger/files/14223729/logifile-missing-trip.txt)

**Describe the bug**
Teslalogger:	1.57.0.0, FleetApi,  Tesla M3 Highland

Ich parkte am 09.02.2024  von 14:55 bis ca. 15:10, Teslalogger startete erst um 15:22.
Die Daten von 15:10 bis 15:22 fehlen.

**To Reproduce**

**Expected behavior**

**Screenshots**

** Teslalogger Type **
 Docker 

Did you update the Image with apt-get update & upgrade?
 Nein

** Do you use Tasker or iBeacon **
Nein

**Additional context**

**Comment by bassmaster187** [comment]
After version 1.57.3 Model 3 and Model Y with FleetAPI are not affected anymore. You can see this in your logfile:
> 29.02.2024 12:45:36 : #3[Car_3:21]: API not suspended!

If you still see missing trips, feel free to reopen the isse
