### ISSUE TITLE
Link zu den release Notes im Firmware Tracker 

### ISSUE THREAD

**Issue by bicmac** [bassmaster187/TeslaLogger#1194]
Kann man ggf in den Flotten Firmware Tracker zu den einzelnen Versionen ggf. einen Link zu den Release Note einbauen?
Sozusagen das die erste Spalte mit der VErsionsnummer immer gleich auf die Releasenotes verlinkt?

<img width="1337" alt="image" src="https://github.com/bassmaster187/TeslaLogger/assets/44036062/9d250e7a-a627-4373-bf6a-c5c5aa953c1b">

Als Link könnte man ja Beispielsweise https://www.notateslaapp.com verwenden.
Für die 2024.2.7 Version wäre da der Link https://www.notateslaapp.com/de/software-updates/version/2024.2.7/versionshinweise

**Comment by bassmaster187** [comment]
fertig

https://teslalogger.de/firmware.php

![image](https://github.com/bassmaster187/TeslaLogger/assets/6816385/4b0a1895-ef94-4481-a6fc-ce5b95c1cb8d)

**Comment by bicmac** [comment]
Cool danke :-)

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Christian P. ***@***.***>
Gesendet: Friday, February 23, 2024 8:05:18 AM
An: bassmaster187/TeslaLogger ***@***.***>
Cc: Roga, Enrico ***@***.***>; Author ***@***.***>
Betreff: Re: [bassmaster187/TeslaLogger] Link zu den release Notes im Firmware Tracker (Issue #1194)


fertig

https://teslalogger.de/firmware.php

image.png (view on web)<https://github.com/bassmaster187/TeslaLogger/assets/6816385/4b0a1895-ef94-4481-a6fc-ce5b95c1cb8d>
