### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by comradekingu** [bassmaster187/TeslaLogger#1206]
No license, or in the very least no commonly placed license file here.

Would need consent from all contributors.
Also a requirement for libre hosting at Weblate.

AGPLv3+ is good.

**Comment by bassmaster187** [comment]
Project is under GPL3 license. 
https://github.com/bassmaster187/TeslaLogger/commit/76047e8d334da9f3bba3eab49888e8dc174e0fbf

**Comment by comradekingu** [comment]
Great

Would make sense to add "General-public-license-3-or-later" here https://hosted.weblate.org/projects/teslalogger/teslalogger/#information

Can be done in
https://hosted.weblate.org/settings/teslalogger/teslalogger
and
https://hosted.weblate.org/settings/teslalogger/glossary/

**Comment by bassmaster187** [comment]
done
