### ISSUE TITLE
Wrong vehicle type displayed

### ISSUE THREAD

**Issue by tommymann1982** [bassmaster187/TeslaLogger#1209]
I own an M3 RWD Long Range (2019). In the Teslalogger, however, the vehicle is displayed as M3 SR+ 2019. There seems to be no way to change the vehicle type. This means that my Long Range model is compared with M3 SR+ models, which is not correct and also distorts the statistics. 

![image](https://github.com/bassmaster187/TeslaLogger/assets/120057759/a3c7c14d-e6e3-49c1-9af3-a3b080905850)

**Comment by DanubeRS** [comment]
I also noticed this with a 2024 LR showing as SR+

It could be that the VIN is being incorrectly decomposed

**Comment by bassmaster187** [comment]
could you please send me your Tasker Token next to your VIN: https://www.impala64.de/blog/kontakt/

**Comment by tommymann1982** [comment]
> could you please send me your Tasker Token next to your VIN: https://www.impala64.de/blog/kontakt/

done. Thanks

**Comment by bassmaster187** [comment]
will be detected after first charging or with next release.

https://github.com/bassmaster187/TeslaLogger/commit/9ffadb94d0dec983bae668e4de3bfff629c2fd29

**Comment by danpadure** [comment]
I am on 1.57.12.0 (I would think this is a newer release) and the car (LR) is still detected as SR+
I tried charging it, but it's the same.
What do you mean by "first charging"?

**Comment by danpadure** [comment]
I did a complete update in docker, now it does not say anything about the car model

**Comment by danpadure** [comment]
I checked Webhelper file and it does not seem to match correctly the car type:
Vehicle Config: car_type:'model3' car_special_type:'base' trim_badging:'74d'
It's a LR 2021 with 82kWh battery, only made in Q2 2021

**Comment by danpadure** [comment]
9.04.2024 20:54:46 : #5[Car_5:20]: Voltage at 50% SOC:0V Date:1/1/0001 12:00:00 AM
19.04.2024 20:54:46 : #5[Car_5:20]: Car: M3 SR+ 2021 - 0.126 Wh/km
19.04.2024 20:54:46 : #5[Car_5:20]: VIN decoder: Model 3 2021 AWD:True MIC:False battery:n/a motor:3 dual MIG:False
19.04.2024 20:54:46 : #5[Car_5:20]: Vehicle Config: car_type:'model3' car_special_type:'base' trim_badging:'74d'
19.04.2024 20:54:46 : #5[Car_5:20]: No meter config

**Comment by danpadure** [comment]
I tried forking it to fix the code, but I can't understand the way you decode the cars
I don't understand how you decode and combine the model name and wh/km data

**Comment by danpadure** [comment]
I woke up this morning and the car shows up as M3 LR
@bassmaster187 did you fix anyting somehow? Or how did it change?
Anyway, is it correct to show up as M3LR?  what year is "M3 LR FL"?

**Comment by danpadure** [comment]
Did another update form the app, now it shows as M3 LR FL

**Comment by bassmaster187** [comment]
If it gets back to SR+ I'll try to debug it. (note: VIN / Taskertoken sent by email on 19.04.2024 21:04)

**Comment by danpadure** [comment]
> If it gets back to SR+ I'll try to debug it. (note: VIN / Taskertoken sent by email on 19.04.2024 21:04)

I don't understand how it can change: one day SR+, then LR then LR FL without doing anything  ?
Isn't detection done only once?

PS: Today stil LR FL

**Comment by bassmaster187** [comment]
Some detections are based on the typical range. That can change by temperature or a bad battery.
