### ISSUE TITLE
Add more device_class attributes to MQTT entities/auto discovery

### ISSUE THREAD

**Issue by Turmoil1112** [bassmaster187/TeslaLogger#1213]
**Is your feature request related to a problem? Please describe.**
Home Assistant offers a wide range of device_classes which automatically translate entitiy states and add icons. They are already used for many sensors in TeslaLoggers new MQTT implementation. But there are some sensors which could be converted to binary_sensors and outfitted with fitting device classes.
[Device classes for binary_sensors on HA docu](https://www.home-assistant.io/integrations/binary_sensor/#device-class).
[Example for a MQTT binary_sensor](https://www.home-assistant.io/integrations/binary_sensor/#device-class).

**Describe the solution you'd like**
Here are a few examples I've used with the first MQTT implementation:
teslalogger/car/VIN/**driving**
device_class: moving
payload_on: "true"
payload_off: "false"
![Bildschirmfoto 2024-03-02 um 18 52 26](https://github.com/bassmaster187/TeslaLogger/assets/124815066/7f862ea0-c76e-4cf0-97ba-021ef414b88f)

teslalogger/car/VIN/**charge_port_door_open**
Also a binary_sensor unless you want to add port opening functionality, then it propably becomes a switch. Here I manually choose a specific icon (CCS2 Plug).
device_class: opening
payload_on: "true"
payload_off: "false"
icon: mdi:ev-plug-ccs2
![Bildschirmfoto 2024-03-02 um 18 52 36](https://github.com/bassmaster187/TeslaLogger/assets/124815066/824db0ae-d17e-4af1-b526-7a48c4b226d7)

Other sensors which could also be binary_sensors include:
- sleeping
- falling_asleep
- plugged_in
- battery_heater
- locked
- fast_charger_present

For the switches icons could be added:
- sentry_mode (mdi:cctv)
- is_preconditioning (mdi:heat-wave)
- online (mdi:car-connected)

**Describe alternatives you've considered**
An alternative is static mapping of [MQTT entities in configuration.yaml](https://www.home-assistant.io/integrations/mqtt/#yaml-configuration-listed-per-item) or even using [customizing](https://www.home-assistant.io/docs/configuration/customizing-devices/).

**Additional context**
If there is any interest in adding device_classes and icons I could add a complete list of the sensors with fitting device_classes and manual icons.

**Comment by Adminius** [comment]
> If there is any interest in adding device_classes and icons I could add a complete list of the sensors with fitting device_classes and manual icons.

yes, please, you can also do changes here as a pull request.
[https://github.com/bassmaster187/TeslaLogger/blob/master/TeslaLogger/MQTTAutoDiscovery.cs](https://github.com/bassmaster187/TeslaLogger/blob/master/TeslaLogger/MQTTAutoDiscovery.cs)

Example: 
```
            autoDiscovery["charge_port_door_open"] = new Dictionary<string, string>();
            autoDiscovery["charge_port_door_open"]["type"] = "binary_sensor";
            autoDiscovery["charge_port_door_open"]["name"] = "Charge port opened";
            autoDiscovery["charge_port_door_open"]["pl_on"] = "true";
            autoDiscovery["charge_port_door_open"]["pl_off"] = "false";
            autoDiscovery["charge_port_door_open"]["icon"] = "mdi:ev-plug-ccs2";
            autoDiscovery["charge_port_door_open"]["class"] = "opening";
```

**Comment by Adminius** [comment]
#1222
