### ISSUE TITLE
Webinterface no longer working (language.php:54)

### ISSUE THREAD

**Issue by flosoft** [bassmaster187/TeslaLogger#1227]
** Append Logfile **
[Thu Mar 07 12:20:48.572617 2024] [php:warn] [pid 18] [client 172.25.0.9:52540] PHP Warning:  Undefined variable $filename2 in /var/www/html/admin/language.php on line 54
[Thu Mar 07 12:20:48.572664 2024] [php:error] [pid 18] [client 172.25.0.9:52540] PHP Fatal error:  Uncaught ValueError: Path cannot be empty in /var/www/html/admin/language.php:54\nStack trace:\n#0 /var/www/html/admin/language.php(54): file_put_contents()\n#1 /var/www/html/admin/index.php(3): require_once('/var/www/html/a...')\n#2 {main}\n  thrown in /var/www/html/admin/language.php on line 54

**Describe the bug**
Webinterface returns a white page.

**Expected behavior**
Should return the webinterface

** Teslalogger Type **
Docker

**Comment by bassmaster187** [comment]
Please try the new version
