### ISSUE TITLE
Docker Setup ERROR

### ISSUE THREAD

**Issue by mikeh2010** [bassmaster187/TeslaLogger#123]
docker-compose stop
git fetch
git checkout origin/master -- docker-compose.yml
docker-compose build
docker-compose up

ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

Any help appreciated

**Comment by bassmaster187** [comment]
I think you have a Raspberry PI as a host. The Docker Container are not supposed to run on a 32bit host, so you either install a 64bit OS on your Raspberry or purchase an ready to go image for your raspberry.

**Comment by mikeh2010** [comment]
Thanks. Works well using aarch64.
