### ISSUE TITLE
ScanMyTesla / teslalogger.de token

### ISSUE THREAD

**Issue by ramonsmits** [bassmaster187/TeslaLogger#124]
How to obtain a ScanMyTesla / teslalogger.de token? In the code base I only see that the token is read from configuration.

Also, why is teslalogger.de used as a man in the middle? Why isn't for example an MQTT broker being used? I'm not against using teslalogger.de but it would be welcome if this can be overriden.

Why not immediately have ScanMyTesla call the TeslaLogger on the raspberry? I expected that because the current solution requires the internet while if I have my phone and a raspberry pi on the same wifi network I do not need the internet at all.

**Comment by bassmaster187** [comment]
It uses teslalogger.de as a relay server. 
As we don't want to tell everyone how to enable portforwarding / firewalls in their routers, we use the simple way for non computer nerds. 
Plus there are a lot of users without a public ip address, so they are not able to been connected directly. 

In the next few weeks there will be a option for wifi only smartphones. So they will cache all the data untill their home-wifi ist visible and then send all the data.
