### ISSUE TITLE
Autopilot driving info missing in trips

### ISSUE THREAD

**Issue by GerdMayer** [bassmaster187/TeslaLogger#1241]
** Append Logfile **
[TL-log.txt](https://github.com/bassmaster187/TeslaLogger/files/14590611/TL-log.txt)

**Describe the bug**
I migrated to Fleet API and allowed TeslaLogger access in my Tesla account.
When driving with autopilot, autopilot in not visible in trips
TeslaLogger is not present in Control->Locks.

**To Reproduce**

**Expected behavior**
Like documented in: https://github.com/bassmaster187/TeslaLogger/blob/master/docs/en/Fleet_API.md

**Screenshots**

** Teslalogger Type **
Docker at Raspberry P4
Did you update the Image with apt-get update & upgrade?
No

** Do you use Tasker or iBeacon **
No

**Additional context**
If you need additional information, please let me know.

**Comment by bassmaster187** [comment]
Do you have an old Model S/X (pre 2021)?

**Comment by GerdMayer** [comment]
No it's a Model 3 Highland, see log:
13.03.2024 11:51:38 : #1[Car_1:21]: Car: M3 SR+ LFP 2021 - 0.138 Wh/km
13.03.2024 11:51:38 : #1[Car_1:21]: VIN decoder: Model 3 2024 AWD:False MIC:True battery:LFP motor:3/Y single MIG:False
13.03.2024 11:51:38 : #1[Car_1:21]: Vehicle Config: car_type:'model3' car_special_type:'base' trim_badging:'50'

Why does TeslaLogger identify it as M3 SR+ LFP 2021 it's Model 3 2024

**Comment by Adminius** [comment]
1. Your problem, pls. update to 1.57.9.0 Version (just released)
2. Could you please post your VIN (without last 6 digits)

**Comment by GerdMayer** [comment]
1. I installed 1.57.9 and from 15.03.2024 12:18:53 to  15.03.2024 12:34:19 I was partly driving with autopilot, but autopilot is not visisble in trips, attached the log:
[log-1-57-9.txt](https://github.com/bassmaster187/TeslaLogger/files/14615712/log-1-57-9.txt)
2. My VIN is: LRW3E7FS7RC

**Comment by MartinRinas** [comment]
same here. running on 1.57.9.0, migrated to FleetAPI and had two trips with good amount of AP today. Nothing to see in the trip details for this.
VIN: LRWYGCEKXMC

I do not have the virtual key in the car, that process never worked, the Tesla app never opened when I clicked on that button, is that perhaps why I don't see AP?
[logfile (1).zip](https://github.com/bassmaster187/TeslaLogger/files/14628257/logfile.1.zip)

**Comment by MartinRinas** [comment]
got it, thanks. I am an owner on my car, that's fine. Seems I need to debug why the virtual key install sequence never launched the Tesla app on my phone. There is a redirect happening when I hit the button, but it only seems to reload the page I am on.

**Comment by MartinRinas** [comment]
ha! got my virtual key added.
I'm using Microsoft launcher on my Android phone, scanning the QR code there didn't work but always brought me to the page with the QR code. Scanning the QR code with the Google App opened the Tesla app and the virtual key got added.

**Comment by bassmaster187** [comment]
> ha! got my virtual key added.

Are you now receiving telemetry data? Maybe you need to restart Teslalogger to resend the config to your car.

**Comment by MartinRinas** [comment]
> > ha! got my virtual key added.
> 
> Are you receiving telemetry data, now? Maybe you need to restart Teslalogger to resend the config to your car.

well, I have received telemetry data previously as well, i.e. the trip was there. But I couldn't see AP vs. non-AP parts of the trips. I haven't been driving since the virtual key has been installed, will report back here.

**Comment by MartinRinas** [comment]
I think adding the virtual key did the trick here. I am seeing cell temp & imbalance now, this wasn't the case previously. 
![image](https://github.com/bassmaster187/TeslaLogger/assets/29856849/29c955ba-527e-4fb8-bfa2-2286d314541e)

**Comment by rowich** [comment]
Just reading the discussion here. I am having the same issue, but the solution might be different as I am not using my owner account for Teslalogger (and also have similar issues [with open issue for that], as Teslalogger is not able to set Sentry, Charge Limit etc) - still not sure how to solve that. If anyone has an idea, please send me that. Keep you informed, if I can solve it on my own.

**Comment by MartinRinas** [comment]
So I did a trip with AP today (only a few km, but nevertheless). Unfortunately, the AP section remains labeled as human driving. 
[logfile (2).zip](https://github.com/bassmaster187/TeslaLogger/files/14731256/logfile.2.zip)
Would be the highlighted section of the road, AP trip should start just before 10:28
![image](https://github.com/bassmaster187/TeslaLogger/assets/29856849/e14823e4-593f-494e-896d-14493604d98f)
