### ISSUE TITLE
Tasker Token: | Warning: file_get_contents(/etc/teslalogger/TASKERTOKEN): failed to open stream: No such file or directory in /var/www/html/admin/settings.php on line 149

### ISSUE THREAD

**Issue by DariBer** [bassmaster187/TeslaLogger#126]
I have a problem with Tasker Token in my Docker on Ubuntu 18.04.

I get this error message at "Settings"

Tasker Token: | Warning: file_get_contents(/etc/teslalogger/TASKERTOKEN): failed to open stream: No such file or directory in /var/www/html/admin/settings.php on line 149

**Comment by bassmaster187** [comment]
Please check your logfile if your Tesla Credetials are OK.
