### ISSUE TITLE
Grafana container keeps restarting on Synology NAS running DSM 6.1.7-15284 Update 3

### ISSUE THREAD

**Issue by fatfurrycat** [bassmaster187/TeslaLogger#129]
I'm attempting to run TeslaLogger on my Synology NAS. 
Docker components are slightly behind the recommended:
doDocker version 18.09.8, build 2c0a67b
docker-compose version 1.24.0, build 0aa59064

However, this didn't stop me building and launching TeslaLogger. 
All containers come up okay, apart from Grafana, which keeps restarting:
grafana_1      | WARNING: no logs are available with the 'db' log driver
teslalogger_grafana_1 exited with code 1
grafana_1      | WARNING: no logs are available with the 'db' log driver
teslalogger_grafana_1 exited with code 1
grafana_1      | WARNING: no logs are available with the 'db' log driver
teslalogger_grafana_1 exited with code 1
... ad inifinitum.

Checking in the logs for the grafana container, I see two obvious errors:
t=2020-02-17T14:25:40+0000 lvl=warn msg="Could not scan dir \"/var/lib/grafana/plugins\" error: open /var/lib/grafana/plugins: permission denied"
and
t=2020-02-17T14:25:40+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Datasource provisioning error: open /etc/grafana/provisioning/datasources/datasource.yml: permission denied"

I'm unable to get a shell into the contain to investigate, as it keeps stopping before I can check. 
Any ideas why I might be getting the permission denied message, or how I might fix it? 

In addition, if I attempt to connect to the http://synology ip:8888, I the following error in the browser:
Forbidden
You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe
Apache/2.4.38 (Debian) Server at 192.168.0.100 Port 8888

and the following in the docker log:
[Mon Feb 17 15:14:50.720998 2020] [core:crit] [pid 17] (13)Permission denied: [client 172.18.0.1:57066] AH00529: /var/www/html/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/html/' is executable

Another issue I've noticed is that although the database container seems to initialise without error, if I use msql -u root -p to login, a 'SHOW TABLES;" on the teslalogger database returns no output. I'm guessing something is amiss there, as surely there should be some tables at this point? 

Any help would be much appreciated. 

Thanks, 

Andy.

**Comment by bassmaster187** [comment]
Maybe @tabsl  can help you, as he is much more into docker than I am.

**Comment by fatfurrycat** [comment]
Thanks @bassmaster187 
Hope to hear from @tabsl in due course.

**Comment by proudcommerce** [comment]
@fatfurrycat it seems there are some permission problems.

you´ll find a lot of search results for this. ;-) eg. https://github.com/jlesage/docker-handbrake/issues/19 or https://www.synology-forum.de/showthread.html?98775-Grafana-permission-denied-bei-Container-Start or https://emby.media/community/index.php?/topic/32018-permission-denied-w-synology-docker/

have you already checked this?

**Comment by tabsl** [comment]
@fatfurrycat it seems there are some permission problems.

you´ll find a lot of search results for this. ;-) eg. jlesage/docker-handbrake#19 or https://www.synology-forum.de/showthread.html?98775-Grafana-permission-denied-bei-Container-Start or https://emby.media/community/index.php?/topic/32018-permission-denied-w-synology-docker/

have you already checked this?

**Comment by fatfurrycat** [comment]
I've managed to get it working. 
I've moved the built containers to the default Synology location (/volume1/docker) and it all started working. 

It appears that there are some special permissions required, which my previous location didn't have. As the Synology docker created the location above, it has all the permissions correctly set. 

There appear to be some localisation issues currently, but everything appears to be running okay. Going to do some drives in the car, and see what gets captured. 

Has there been an official English translation? For example, even though I've set English in the settings, I'm still seeing 'Schlafen' in the dashboard when the car is asleep. Also, the Grafana dashboards all appear in German.

**Comment by bassmaster187** [comment]
The English translation should done. Maybe there are some Grafana Dashboards needing some translations. I'll take care of it. But we should make sure the synology permissions works fine and my script is able to translate everything. Please make some Screenshots of Dashboards needing some love...

Could you please make a "how to install docker on synology". I know somebody else already managed to get it working, but he won't share his knowledge :-(

**Comment by fatfurrycat** [comment]
I'll be happy to write up how I got it installed and running on my Synology. 
Will also send over some screenshots where some translation might be needed. As you say, it appears to mostly be in Grafana dashboards.

**Comment by bassmaster187** [comment]
Please check the Screenshots on the main github page: https://github.com/bassmaster187/TeslaLogger#screenshots
As you can see, everything is translated. Maybe after releasing new features, I forgot to traslate some strings, but you should have at least translated what is shown in the screenshots. if not, there may be a problem with some write permissions.

**Comment by fatfurrycat** [comment]
Okay. Some instructions on how to get Teslalogger working on Synology. 
I'm running on DSM 6.1.7-15284 Update 3. YMMV on other versions. 

1) From Synology Package Centre, install both Docker and Git Server. 
2) Once installed, click on each package and ensure that they are in the 'Running' state. 
3) SSH to your Synology and login as 'admin'. 
4) When you're logged in, type 'sudo -i' and become root user. The password is the same as admin.
5) In Package Centre, click on Docker, and check the 'Installed Volume'. Make a note of it. 
6) In your SSH session, cd to this volume. e.g. cd /volume1/docker
7) Run git clone https://github.com/bassmaster187/TeslaLogger in the Terminal. 
8) When finished, follow rest of instructions here: https://github.com/bassmaster187/TeslaLogger/blob/master/docker_setup.md

The above page mentions the following to test:
Try to connect to Grafana with you favorite browser: http://localhost:3000 (admin/admin)

This is incorrect for Synology. The URL should be http://<synology ip>:3000
e.g. http://192.168.0.100:3000
The username is admin, but the password is teslalogger. 

This should get you up and running on Synology. I'm still testing, and will update if I find any issues. 

So far, I've been able to capture journey data, and also charging, so it's looking good.

**Comment by bassmaster187** [comment]
Thanks. I created a Synology How-to: https://github.com/bassmaster187/TeslaLogger/blob/master/docker_setup_synology.md
