### ISSUE TITLE
MQTT - send further data

### ISSUE THREAD

**Issue by spitzlbergerj** [bassmaster187/TeslaLogger#130]
Please add further data to the MQTT telegrams:

**Monitoring the charging process:**
time_to_full_charge oder minutes_to_full_charge
scheduled_charging_pending
scheduled_charging_start_time

**Indicate if the vehicle is locked:**
charge_port_door_open
locked
if applicable, further data according to https://tesla-api.timdorr.com/vehicle/state/vehiclestate

**Special Modes:**
in_service

Thanks
Josef

**Comment by Adminius** [comment]
@spitzlbergerj did you checked if all values you interesting are now implemented?

**Comment by spitzlbergerj** [comment]
Hi @Adminius,

the following data is currently distributed via MQTT:

{"charging":false,"driving":false,"online":false,"sleeping":true,"falling_asleep":false,"speed":0,"power":0,"odometer":11359.055141059273,"ideal_battery_range_km":286.72127717784895,"battery_range_km":286.72127717784895,"outside_temp":21,"battery_level":64,"charger_voltage":0,"charger_phases":0,"charger_actual_current":0,"charge_energy_added":0,"charger_power":0,"charge_rate_km":0,"charge_port_door_open":false,"time_to_full_charge":0,"car_version":"2021.4.18.2 6c676ce09ea5","trip_start":"17:45","trip_start_dt":"2021-06-14T15:45:56Z","trip_max_speed":28,"trip_max_power":12,"trip_duration_sec":102,"trip_kwh":0.11027310888868085,"trip_avg_kwh":748.06381945818418,"trip_distance":0.14741136520751752,"ts":"2021-06-17T21:48:45Z","latitude":xxxxxx,"longitude":xxxxxx,"charge_limit_soc":81,"inside_temperature":28,"battery_heater":false,"is_preconditioning":false,"sentry_mode":false,"country_code":"de","state":"xxxxxx","display_name":"xxxxxxx","TLGeofence":"zu Hause","TLGeofenceIsHome":true,"TLGeofenceIsCharger":true,"TLGeofenceIsWork":false}

so a few data fields are now in, others - also from another feature request of mine - are not yet in.

Regards
Josef

**Comment by Adminius** [comment]
Did you also checked https://github.com/bassmaster187/TeslaLogger/blob/master/TeslaLogger/WebServer.md ?

e.g. http://raspberry:5000/debug/TeslaAPI/1/drive_state

**Comment by spitzlbergerj** [comment]
Ah, ok, I didn't know that yet . Great. Thank you very much. Thus settled
