### ISSUE TITLE
Tesla fleet API: Result.Statuscode: 429 (TooManyRequests) cmd: vehicle_data

### ISSUE THREAD

**Issue by tommymann1982** [bassmaster187/TeslaLogger#1304]
Since this morning 5am teslalogger says my car is offline. 
Christian, is it possibel, that the server isnt working? 
@bassmaster187 

The LogFile is reporting an TooManyRequests error. 
![Screenshot_20240607-200407](https://github.com/bassmaster187/TeslaLogger/assets/120057759/eeb1f76e-6b99-42e0-a35f-0b122db95a44)

**Comment by bassmaster187** [comment]
Other apps have the same problem:
https://github.com/teslamotors/vehicle-command/issues/255

**Comment by tommymann1982** [comment]
This isnt good

**Comment by bassmaster187** [comment]
### Workaround:
It seems like the old owners API is not affected about the Rate Limit. So switching back to owners API might be a temporary solution.

- Go to settings
- My Tesla credentials
- Edit
- Use any other method than Fleet API. e.g. In local browser

**Comment by tommymann1982** [comment]
well this doesnt seem to work either 
![image](https://github.com/bassmaster187/TeslaLogger/assets/120057759/000c44a3-b0a0-46cc-ab54-4ad961ace73a)

**Comment by tommymann1982** [comment]
Now, I have this screen 
The Car seems to be online now, but last data are 10 hours old. I am missing 1 charging session and several trips. F.E. Last trip wasnt at 8.38 am, but around 16.30h. 


![image](https://github.com/bassmaster187/TeslaLogger/assets/120057759/52d00a6d-ed53-4cf7-b43e-35863d70fe8b)

**Comment by tommymann1982** [comment]
Today there were no issues.
@bassmaster187 you can close the thread. Thanks for your help

**Comment by bill340** [comment]
Not really! Issues are still there!

**Comment by IMgoRt** [comment]
Was working Saturday, broke again sometime Sunday PM

**Comment by bassmaster187** [comment]
> Not really! Issues are still there!

You don't use Fleet API anymore and still receive 429 errors?

![image](https://github.com/bassmaster187/TeslaLogger/assets/6816385/749d4b61-eaa0-4f9e-bf99-a8c3870dab4b)

**Comment by GerdMayer** [comment]
Using Fleet API, I receive 429 errors. 

Using Virtual Key I receive this and then **Vehicle is Offline !!!**

10.06.2024 13:41:06 : #1[Thread Pool Worker:10]: Command counter: 200
10.06.2024 13:42:10 : #1[Thread Pool Worker:10]: Result.Statuscode: 408 (RequestTimeout) cmd: vehicle_data?endpoints=drive_state%3Blocation_data&let_sleep=true
10.06.2024 13:42:11 : #1[Car_1:28]: IsDriving = NULL!

10.06.2024 13:42:21 : #1[Thread Pool Worker:32]: Result.Statuscode: 408 (RequestTimeout) cmd: vehicle_data?endpoints=charge_state&let_sleep=true
10.06.2024 13:42:22 : #1[Car_1:28]: isCharging = NULL
.....
10.06.2024 13:49:56 : #1[Thread Pool Worker:56]: Result.Statuscode: 408 (RequestTimeout) cmd: vehicle_data?endpoints=vehicle_state&let_sleep=true
10.06.2024 13:49:57 : #1[Car_1:28]: change TeslaLogger state: Online -> Start

10.06.2024 13:49:57 : #1[Thread Pool Worker:53]: Result.Statuscode: 408 (RequestTimeout) cmd: vehicle_data?endpoints=drive_state%3Blocation_data&let_sleep=true
10.06.2024 13:49:58 : #1[Car_1:28]: IsDriving = NULL!

10.06.2024 13:50:07 : TeslaLogger process statistics
Thread count: 20
WorkingSet64: 113590272
PeakWorkingSet64: 123826176
PrivateMemorySize64: 157290496
VirtualMemorySize64: 1646551040
StartTime: 6/10/2024 1:32:02 PM
Database sizes: DB teslalogger
table pos has 13mb
table mothership has 6mb
10.06.2024 13:50:08 : #1[Car_1:28]: STOP communication with Tesla Server to enter sleep Mode! https://teslalogger.de/faq-1.php
10.06.2024 13:50:08 : #1[Car_1:28]: Waiting for car to go to sleep 0
10.06.2024 13:50:09 : #1[Car_1:28]: Car is offline now
10.06.2024 13:50:09 : #1[Car_1:28]: Restart communication with Tesla Server! 3
10.06.2024 13:50:09 : #1[Car_1:28]: Restart communication with Tesla Server! 2
10.06.2024 13:50:10 : #1[StreamAPIThread_1:33]: Stream Data Error: Vehicle is offline

10.06.2024 13:50:14 : #1[Car_1:28]: ScanMyTesla FastMode: False
10.06.2024 13:50:14 : #1[Car_1:28]: CloseDriveState EndDate: 2024-06-10 13:34:46
10.06.2024 13:50:14 : Reverse geocoding by GeocodeCache
10.06.2024 13:50:14 : Reverse geocoding by GeocodeCache
10.06.2024 13:50:14 : #1[Car_1:28]: state: offline

**Comment by bill340** [comment]
> > Not really! Issues are still there!
> 
> You don't use Fleet API anymore and still receive 429 errors?
> 
> ![image](https://private-user-images.githubusercontent.com/6816385/338101444-749d4b61-eaa0-4f9e-bf99-a8c3870dab4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjE5MDYsIm5iZiI6MTcxODEyMTYwNiwicGF0aCI6Ii82ODE2Mzg1LzMzODEwMTQ0NC03NDlkNGI2MS1lYWEwLTRmOWUtYmY5OS1hOGMzODcwZGFiNGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMTYwMDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNiZmE2YTQ2MTA2MTVhNjg0YzIxZTBmNzc3MTVjMjFjZjkzYjg1NzM2YzVhZWZjNmNiNjM0YzMwMWRlMzgyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6slnsaTMeIn8a6_V66pQppTAXt1KhKEBX--C_iYO9Qk)

It works without Fleet-API, but I cannot send any commands without Fleet-API.

**Comment by bill340** [comment]
Would it be possible to set the refresh rate to 5min when using Fleet-API, so that it does not run into a timeout and still being able to send commands?

**Comment by TillMatthis** [comment]
> Now, I have this screen The Car seems to be online now, but last data are 10 hours old. I am missing 1 charging session and several trips. F.E. Last trip wasnt at 8.38 am, but around 16.30h.
> 
> ![image](https://private-user-images.githubusercontent.com/120057759/337889199-52d00a6d-ed53-4cf7-b43e-35863d70fe8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODg0NDAsIm5iZiI6MTcxODE4ODE0MCwicGF0aCI6Ii8xMjAwNTc3NTkvMzM3ODg5MTk5LTUyZDAwYTZkLWVkNTMtNGNmNy1iNDNlLTM1ODYzZDcwZmU4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxMDI5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDhmY2UyNmI5NzMxYTdlZWYwNDk4NDVkODBiNmExYTYzMjkyM2FlMTViMDY4MGI5ZDUxYjViMTE5YTExN2QxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zTT-maT5_GW_I_ifZzCvJlf2wnE2pbcuMfKDTlHSTeU)

I'm having the same problem sins 1.58.1.0

**Comment by bill340** [comment]
> We use a couple of commands to run Teslalogger. I have a different idea to combine Fleet Telemetry with Commands to be able to have a refresh rate of 30 seconds. But I need to make a couple of changes

That. would be great, as I am using teslalogger to send commands from evcc with the teslalogger charger template.
Before that change it worked really great!
https://github.com/evcc-io/evcc/pull/13062

**Comment by Adminius** [comment]
> That. would be great, as I am using teslalogger to send commands from evcc with the teslalogger charger template. Before that change it worked really great! [evcc-io/evcc#13062](https://github.com/evcc-io/evcc/pull/13062)

FleetAPI only allows 5 charing commands per car per day  => usless

If you familar with linux and raspi:
https://github.com/evcc-io/evcc/discussions/14252#discussioncomment-9748552

**Comment by dbmtrde** [comment]
> > Not really! Issues are still there!
> 
> You don't use Fleet API anymore and still receive 429 errors?
> 
> ![image](https://private-user-images.githubusercontent.com/6816385/338101444-749d4b61-eaa0-4f9e-bf99-a8c3870dab4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzIzNDMsIm5iZiI6MTcxODIzMjA0MywicGF0aCI6Ii82ODE2Mzg1LzMzODEwMTQ0NC03NDlkNGI2MS1lYWEwLTRmOWUtYmY5OS1hOGMzODcwZGFiNGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMjI0MDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjNlNTYxYTRiNTY3MzQ3NjE5ZDIxZjNjY2IxMzlmNDhiNGU0NDVlNjllOTc5NmY5MjZjOTI3MGFkOGM2NDk5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.myM2IH3vezr-GdtYbRcZY4pMlZF_0S8SQfsg-G20d8w)

Hi Christian, 
the error also occurs without Fleet API (I have never used it)

```
13.06.2024 00:41:57 : #1[Thread Pool Worker:39857]: Result.Statuscode: 429 (TooManyRequests) cmd: vehicle_data?endpoints=climate_state&let_sleep=true Sleep: 28103ms

13.06.2024 00:41:59 : #2[Thread Pool Worker:39804]: Result.Statuscode: 429 (TooManyRequests) cmd: vehicle_data?endpoints=drive_state%3Blocation_data&let_sleep=true Sleep: 33337ms

13.06.2024 00:42:25 : #1[Car_1:17]: GetOutsideTempAsync: NULL

13.06.2024 00:42:32 : #2[Car_2:19]: IsDriving = NULL!
```

**Comment by chk2902** [comment]
BTW, at the moment, Teslalogger notes too many requests and the car is "offline" (unexpected state for the failing API in my opinion). Yet in my app, which queried the data every 5 minutes (up to a few minutes ago, I now reduced it a bit), the fleet API works (same car, same credentials), also Tronity did show up-to-date data. Maybe some scopes of the API are restricted while others aren't?

I use `vehicle_data?endpoints=charge_state%3Blocation_data`

**Comment by IMgoRt** [comment]
> BTW, at the moment, Teslalogger notes too many requests and the car is "offline" (unexpected state for the failing API in my opinion). Yet in my app, which queried the data every 5 minutes (up to a few minutes ago, I now reduced it a bit), the fleet API works (same car, same credentials), also Tronity did show up-to-date data. Maybe some scopes of the API are restricted while others aren't?
> 
> I use `vehicle_data?endpoints=charge_state%3Blocation_data`

Just to add - in the UK my electricity supplier (octopus) uses the fleet API multiple times overnight to start and stop charging at times that are most advantageous to it for wholesale energy prices
So it doesn't seem to be hit by rate limits

**Comment by Adminius** [comment]
> So it doesn't seem to be hit by rate limits

maybe because they already paying for more requests/commands? A lot of such companies got contracts with NDA so they can use it already... 

Or maybe because Octopus and Tesla are "friends"? ;)

**Comment by chk2902** [comment]
I don't know about that, or if Tronity pays, but until now I don't pay anything to Tesla for my requests.

Ah, but now, a little math helps: 5 minutes interval are 288 requests. 🤔 Sorry about my misleading comment - if Teslalogger uses more, that's different.

**Comment by Adminius** [comment]
> until now I don't pay anything to Tesla for my requests.

Not you, but logger-team. And if, you will pay to logger-team

**Comment by chk2902** [comment]
@Adminius No, "my" requests are personal from my own app's code. Teslalogger and Tronity run in parallel using their own requests for the same car.

**Comment by STRUBartacus** [comment]
Now the normal API (600) has also been given a limit.

**Comment by albi** [comment]
seems so. no data even without fleet-api checked.

**Comment by Adminius** [comment]
It looks like it now good time to test fleet API again :D

**Comment by tommymann1982** [comment]
Today it really stoped working again. The car is offline since 5.45am
TeslaLogger reports weird data (fE Last charging, when the car wasnt charging with time a stamp in the future, wrong SOC status, non existend teslalogger update)

![Screenshot_20240614-135935](https://github.com/bassmaster187/TeslaLogger/assets/120057759/93669ca0-b0b7-4d0b-96f0-9d4cac447668)

**Comment by kaygee60** [comment]
Totally not working, fleet api or not. Does not update at all, car is shown as offline - although having charged and been driving. No errors in protocol.

**Comment by bill340** [comment]
Same here... Not using sleep api, but also not working. Following error in log:

15.06.2024 18:36:21 : #1[Thread Pool Worker:7]: Result.Statuscode: 429 (TooManyRequests) cmd: vehicle_data?endpoints=vehicle_config&let_sleep=true Sleep: 26620000ms, ratelimit-limit: 600, ratelimit-remaining: 0, ratelimit-reset: 26620, sleep till: 16.06.2024 02:00:01
15.06.2024 18:36:22 : #2[:1]: LastTaskerToken not found - Stop using fast TaskerToken request! Reply: never!

**Comment by bill340** [comment]
15.06.2024 19:12:05 : #2[Thread Pool Worker:21]: Update Tesla Token From Refresh Token!
15.06.2024 19:12:06 : #2[Thread Pool Worker:21]: HttpStatus: OK
15.06.2024 19:12:06 : #2[Thread Pool Worker:21]: UpdateRefreshToken
15.06.2024 19:12:06 : #2[Thread Pool Worker:21]: UpdateRefreshToken OK: 1 - encrypted:r2TIfMgoc/xxxxxxxx
15.06.2024 19:12:06 : #2[Thread Pool Worker:21]: UpdateTeslaToken
15.06.2024 19:12:06 : #2[Thread Pool Worker:21]: update tesla_token OK: 1 - eyJhbGciOiJSUzI1NiIsxxxxxx
15.06.2024 19:12:06 : #2[Thread Pool Worker:8]: Result.Statuscode: 429 (TooManyRequests) cmd: vehicle_data?endpoints=vehicle_config&let_sleep=true Sleep: 24474000ms, ratelimit-limit: 600, ratelimit-remaining: 0, ratelimit-reset: 24474, sleep till: 16.06.2024 02:00:00

**Comment by Adminius** [comment]
Try this branch. You need FleetAPI+Virtual Key for it

https://github.com/bassmaster187/TeslaLogger/tree/Free-FleetAPI

**Comment by tommymann1982** [comment]
@Adminius did you paste wrong link ? That link is for teslalogger instalation proces.

**Comment by bill340** [comment]
It seems to work initially, but the log fills up and the machine gets into an overload:

15.06.2024 21:34:41 : #2[Thread Pool Worker:52]: StartChargingState Task GetCurrentState(): Online
15.06.2024 21:34:41 : #2[Thread Pool Worker:103]: StartChargingState Task start
15.06.2024 21:34:41 : #2[Thread Pool Worker:103]: StartChargingState Task latestPos: 104589
15.06.2024 21:34:41 : #2[Thread Pool Worker:103]: StartChargingState Task GetCurrentState(): Online
15.06.2024 21:34:41 : #2[Thread Pool Worker:62]: StartChargingState Task start
15.06.2024 21:34:41 : #2[Thread Pool Worker:62]: StartChargingState Task latestPos: 104589
15.06.2024 21:34:41 : #2[Thread Pool Worker:62]: StartChargingState Task GetCurrentState(): Online
15.06.2024 21:34:41 : #2[Thread Pool Worker:57]: StartChargingState Task start
15.06.2024 21:34:41 : #2[Thread Pool Worker:57]: StartChargingState Task latestPos: 104589
15.06.2024 21:34:41 : #2[Thread Pool Worker:57]: StartChargingState Task GetCurrentState(): Online
15.06.2024 21:34:42 : #2[Thread Pool Worker:48]: StartChargingState Task start
15.06.2024 21:34:42 : #2[Thread Pool Worker:48]: StartChargingState Task latestPos: 104589
15.06.2024 21:34:42 : #2[Thread Pool Worker:48]: StartChargingState Task GetCurrentState(): Online
15.06.2024 21:34:42 : #2[Thread Pool Worker:47]: StartChargingState Task start
15.06.2024 21:34:42 : #2[Thread Pool Worker:47]: StartChargingState Task latestPos: 104589
15.06.2024 21:34:42 : #2[Thread Pool Worker:47]: StartChargingState Task GetCurrentState(): Online
15.06.2024 21:34:42 : #2[Thread Pool Worker:46]: StartChargingState Task start
15.06.2024 21:34:42 : #2[Thread Pool Worker:46]: StartChargingState Task latestPos: 104589
15.06.2024 21:34:42 : #2[Thread Pool Worker:46]: StartChargingState Task GetCurrentState(): Online
15.06.2024 21:34:42 : #2[Thread Pool Worker:45]: StartChargingState Task start

**Comment by bill340** [comment]
In evcc what is trying to get the charging state I get the following error in the log:

[lp-2 ] ERROR 2024/06/15 19:38:14 charger status: Get "http://192.168.2.5:5010/currentjson/2": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by Adminius** [comment]
> @Adminius did you paste wrong link ? That link is for teslalogger instalation proces.

This link is for special brunch that should work with limited amount of requests. It's beta, so not in main branch and not yer available via normal update

**Comment by bill340** [comment]
Ok, I reinstalled this branch not to 1.58.1.3
For now it works, also with the queries from evcc.
Lets wait a day and see it it runs into Tesla-api timeouts again...

**Comment by tommymann1982** [comment]
Is it necessary to make a clean install or can we just reinstall the old Version?

**Comment by Adminius** [comment]
It enough to change .exe file

**Comment by bill340** [comment]
So far it ie really working nice... Tested with several charge-commands, etc. coming from evcc via TeslaLogger. 
No problems so far. Hopefully the api-limit does not kick in again...

**Comment by Adminius** [comment]
Official Tesla FleetAPI Limit for *charging* commands is 5 per day. Not suitable for EVCC.  If works today, it's luck only.
Thee only stable solution for future ist BLE :/
...or pay for more command, but there is no official prices yet...

**Comment by MNAktie** [comment]
I hope that it works for  you guys now. I have no idea how to update before it goes out like a normal update. Really looking forward to that 👍

**Comment by bill340** [comment]
Unfortunatly the errors are back:

16.06.2024 11:36:27 : #2[Thread Pool Worker:5]: Command: vehicle_data?endpoints=drive_state&let_sleep=true [0]
16.06.2024 11:36:27 : #2[Thread Pool Worker:5]: Result.Statuscode: 429 (TooManyRequests) cmd: vehicle_data?endpoints=drive_state&let_sleep=true Sleep: 51813000ms, ratelimit-limit: 300, ratelimit-remaining: 0, ratelimit-reset: 51813, sleep till: 17.06.2024 02:00:00, FleetAPI

**Comment by tommymann1982** [comment]
@bill340 with the new beta version or the "old" version

**Comment by bill340** [comment]
with the new beta... 1.58.1.4

**Comment by bill340** [comment]
I guess the updates while driving are causing this... I have another Tesla that was not moved since yesterday, but did several charging commands, etc... (more than 5) and on this one it is still working...
The other Tesla did a short drive today (2x 20min) and now it is in rate limit already...

**Comment by Adminius** [comment]
Do you have any other software, like EVCC oder Homeassistant that uses Tesla integration direct via Tesla Server?

**Comment by bill340** [comment]
I do have EVCC running... Custom chargers are configured to run via TeslaLogger...
But Teslas are with evcc template... Could that cause the problem? 

vehicles:
  - name: cherry
    type: template
    template: tesla
    title: Cherry   # Wird in der Benutzeroberfl채che angezeigt (optional)
    accessToken: ...
    refreshToken: ...
    vin: XP7YGCEK8RB... # Erforderlich, wenn mehrere Fahrzeuge des Herstellers vorhanden sind (optional)
    capacity: 79 # Akkukapazit채t in kWh (optional)          

chargers:
  - name: TeslaLoggerWallBoxTif
    type: custom
    status:
      source: combined
      charging:
        source: http
        uri: http://192.168.2.5:5010/currentjson/2
        jq: .charging
      plugged:
        source: http
        uri: http://192.168.2.5:5010/currentjson/2
        jq: if .plugged_in and .TLGeofenceIsHome then true else false end
    enabled:
      source: http
      uri: http://192.168.2.5:5010/currentjson/2
      jq: .charging
    enable:
      source: http
#      uri: http://192.168.2.5:5010/command/2/charge_start_stop?${enable}
      uri: "http://192.168.2.110:8080/api/1/vehicles/LRWYGCEKXNC351138/command/{{if .chargeenable}}charge_start{{else}}charge_stop{{end}}"
      method: POST
      body: ""   
    maxcurrent:
      source: http
#      uri: http://192.168.2.5:5010/command/2/set_charging_amps?${maxcurrent}
      uri: http://192.168.2.110:8080/api/1/vehicles/LRWYGCEKXNC351138/command/set_charging_amps
      method: POST
      body: '{"charging_amps": "{{.maxcurrent}}"}' 
    wakeup:
      source: http
#      uri: http://192.168.2.5:5010/command/2/wake_up
      uri: http://192.168.2.110:8080/api/1/vehicles/LRWYGCEKXNC351138/command/wake_up
      method: POST
      body: ""

**Comment by Adminius** [comment]
> * template: tesla

This uses your reqests...

Use,TeslaLogger Vehicle integration

**Comment by bill340** [comment]
Ok, did change it... 
However can only check again tomorrow on this car that is in ratelimit already today... :(
TeslaLogger template does not deliver the parameter for the charge limit, that is set in the car, as the evcc template does, right?

**Comment by Adminius** [comment]
No, it's not. I don't if it's possible on custom vehicle, if yes, we can integrate it

**Comment by MNAktie** [comment]
When do you think this one will come as a normal update?

**Comment by bassmaster187** [comment]
I want to make some additional tests and fix 2 known bugs. So maybe the next 3 days.

**Comment by MNAktie** [comment]
Thanks, looking forward to it.

**Comment by bill340** [comment]
Everything working now, but in evcc I start getting these errors since the last 2 versions:

ERROR 2024/06/17 08:54:56 charger status: Get "http://192.168.2.5:5010/currentjson/2": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Is Teslamate not answering fast enough? What can I do?

**Comment by bill340** [comment]
Today I have again an error on the mail Page in the upper left corner (Vehicle Info):

Fatal Error: | TooManyRequests 

But nothing at all in the log... Still an issue with request timing?

24.06.2024 12:52:25 : #2[Thread Pool Worker:5975]: *** FT: Telemetry Server Data
24.06.2024 12:53:25 : #2[Thread Pool Worker:5975]: *** FT: Telemetry Server Data
24.06.2024 12:53:25 : #2[Thread Pool Worker:5975]: *** FT: Telemetry Server Data
24.06.2024 12:54:25 : #2[Thread Pool Worker:5986]: *** FT: Telemetry Server Data
24.06.2024 12:54:25 : #2[Thread Pool Worker:5986]: *** FT: Speed: 0.000
24.06.2024 12:54:25 : #2[Thread Pool Worker:5986]: *** FT: Telemetry Server Data
24.06.2024 12:54:34 : #2[Thread Pool Worker:5975]: *** FT: Telemetry Server Alerts
24.06.2024 12:54:52 : #2[Thread Pool Worker:5984]: Command: nearby_charging_sites?detail=true [792]
24.06.2024 12:54:55 : #2[Thread Pool Worker:5986]: *** FT: Telemetry Server Data
24.06.2024 12:54:55 : #2[Thread Pool Worker:5986]: *** FT: Driving by speed ***
24.06.2024 12:54:55 : #2[Thread Pool Worker:5986]: *** FT: Speed: 25.476
24.06.2024 12:55:25 : #2[Thread Pool Worker:5975]: *** FT: Telemetry Server Data
24.06.2024 12:55:25 : #2[Thread Pool Worker:5975]: *** FT: Telemetry Server: Cruise State
24.06.2024 12:55:25 : #2[Thread Pool Worker:5975]: *** FT: Speed: 41.632
24.06.2024 12:55:25 : #2[Thread Pool Worker:5975]: *** FT: Telemetry Server Data
24.06.2024 12:55:55 : #2[Thread Pool Worker:5975]: *** FT: Telemetry Server Data
24.06.2024 12:55:55 : #2[Thread Pool Worker:5975]: *** FT: Telemetry Server: Cruise State
24.06.2024 12:55:55 : #2[Thread Pool Worker:5975]: *** FT: Speed: 25.476
24.06.2024 12:56:28 : #2[Thread Pool Worker:5986]: *** FT: Telemetry Server Data
24.06.2024 12:56:28 : #2[Thread Pool Worker:5986]: *** FT: Speed: 17.398
24.06.2024 12:56:28 : #2[Thread Pool Worker:5986]: *** FT: Telemetry Server Data
24.06.2024 12:56:28 : #2[Thread Pool Worker:5984]: *** FT: Telemetry Server Data
24.06.2024 12:56:28 : #2[Thread Pool Worker:5986]: *** FT: Telemetry Server Data

**Comment by Shrekmachine** [comment]
Does not work since 4 days with Virtual Key
Fatal Error: Car not found

**Comment by bill340** [comment]
Also in the log now...
Can you reduce the request rate? I think very 5min should be good, so we do not excess 300 requests in 24hrs...

24.06.2024 13:13:37 : #2[Thread Pool Worker:7]: Command: vehicle_data?endpoints=drive_state&let_sleep=true [0]
24.06.2024 13:13:37 : #2[Thread Pool Worker:7]: Result.Statuscode: 429 (TooManyRequests) cmd: vehicle_data?endpoints=drive_state&let_sleep=true Sleep: 45983000ms, ratelimit-limit: 300, ratelimit-remaining: 0, ratelimit-reset: 45983, sleep till: 25.06.2024 02:00:00, FleetAPI
24.06.2024 13:13:37 : #2[Thread Pool Worker:21]: *** FT: Telemetry Server Data
24.06.2024 13:13:41 : #2[Thread Pool Worker:27]: *** FT: Telemetry Server Alerts

**Comment by bassmaster187** [comment]
Tesla disabled the limit of command calls in favor for their paid subscription
