### ISSUE TITLE
Out of range value for column 'carid' at row 1 (New car old 2 days)

### ISSUE THREAD

**Issue by roskodav** [bassmaster187/TeslaLogger#1321]
** Append Logfile **
teslalogger-1  | 21.06.2024 23:22:19 : MySql.Data.MySqlClient.MySqlException (0x80004005): Out of range value for column 'carid' at row 1
teslalogger-1  |   at MySql.Data.MySqlClient.MySqlStream.ReadPacketAsync (System.Boolean execAsync) [0x00127] in <5af83e1b1b3246d78d7a16668621fd41>:0 
teslalogger-1  |   at MySql.Data.MySqlClient.NativeDriver.GetResultAsync (System.Int32 affectedRow, System.Int64 insertedId, System.Boolean execAsync) [0x000fa] in <5af83e1b1b3246d78d7a16668621fd41>:0 
teslalogger-1  |   at MySql.Data.MySqlClient.Driver.GetResultAsync (System.Int32 statementId, System.Int32 affectedRows, System.Int64 insertedId, System.Boolean execAsync) [0x00083] in <5af83e1b1b3246d78d7a16668621fd41>:0 
teslalogger-1  |   at MySql.Data.MySqlClient.Driver.NextResultAsync (System.Int32 statementId, System.Boolean force, System.Boolean execAsync) [0x000b9] in <5af83e1b1b3246d78d7a16668621fd41>:0 
teslalogger-1  |   at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync (System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x0020f] in <5af83e1b1b3246d78d7a16668621fd41>:0 
teslalogger-1  |   at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync (System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x0077a] in <5af83e1b1b3246d78d7a16668621fd41>:0 
teslalogger-1  |   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync (System.Data.CommandBehavior behavior, System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x004c1] in <5af83e1b1b3246d78d7a16668621fd41>:0 
teslalogger-1  |   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync (System.Data.CommandBehavior behavior, System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x009da] in <5af83e1b1b3246d78d7a16668621fd41>:0 
teslalogger-1  |   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync (System.Data.CommandBehavior behavior, System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x00aeb] in <5af83e1b1b3246d78d7a16668621fd41>:0 
teslalogger-1  |   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync (System.Boolean execAsync, System.Threading.CancellationToken cancellationToken) [0x000c2] in <5af83e1b1b3246d78d7a16668621fd41>:0 
teslalogger-1  |   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery () [0x00012] in <5af83e1b1b3246d78d7a16668621fd41>:0 
teslalogger-1  |   at TeslaLogger.SQLTracer.TraceNQ (MySql.Data.MySqlClient.MySqlCommand cmd, System.Int64& lastInsertedId, System.String callerFilePath, System.Int32 callerLineNumber) [0x00053] in <c01ec69bfc5f42ffaacfff453c3442e5>:0 
teslalogger-1  |   at TeslaLogger.DBHelper.AddMothershipDataToDB (System.String command, System.Double duration, System.Int32 httpcode, System.Int32 carid) [0x00102] in <c01ec69bfc5f42ffaacfff453c3442e5>:0 
teslalogger-1  |   at TeslaLogger.DBHelper.AddMothershipDataToDB (System.String command, System.DateTime start, System.Int32 httpcode, System.Int32 carid) [0x00026] in <c01ec69bfc5f42ffaacfff453c3442e5>:0 
teslalogger-1  |   at TeslaLogger.WebHelper.DoGetVehiclesRequest (System.String& resultContent, System.Net.Http.HttpClient client, System.String adresse, System.Threading.Tasks.Task`1[System.Net.Http.HttpResponseMessage]& resultTask, System.Net.Http.HttpResponseMessage& result) [0x000ba] in <c01ec69bfc5f42ffaacfff453c3442e5>:0 
teslalogger-1  |   at TeslaLogger.WebHelper.GetAllVehicles (System.String& resultContent, Newtonsoft.Json.Linq.JArray& vehicles, System.Boolean throwExceptionOnUnauthorized, System.Boolean doNotCache) [0x000f4] in <c01ec69bfc5f42ffaacfff453c3442e5>:0 
**Describe the bug**
Fleet token and local browser token. Both same error
**To Reproduce**
1) Install fresh instalation on ubuntu
2) Buy new Tesla Model Y ( Old 2 days)
3) Wait until all container start
4) Go to AdminPage
5) Folow steps In Local Browser
<img width="420" alt="image" src="https://github.com/bassmaster187/TeslaLogger/assets/5636055/f1bc8132-68a4-451d-9a95-fd218d436160">
Click ok 
<img width="401" alt="image" src="https://github.com/bassmaster187/TeslaLogger/assets/5636055/f8b125c5-5619-433b-9d80-9f1845fee1e0">

**Expected behavior**
Dropdown is not empty

** Teslalogger Type **
Docker
Did you update the Image with apt-get update & upgrade? Yes

** Do you use Tasker or iBeacon **
No 

** Notes ** 
TeslaFi have similar problem.

**Comment by aeozyalcin** [comment]
Having the same issue. Car is not new, I have been using it with TeslaMate for a year no problem. Trying to switch to TeslaLogger, I am getting the same error as OP.

**Comment by bassmaster187** [comment]
Sorry for the delay. Purchasing a new car took some time :-) 

Please update zu 1.58.3 and retry the authentification process.

**Comment by aeozyalcin** [comment]
Can confirm, working for me now on 1.58.7.
