### ISSUE TITLE
Scrambled location data

### ISSUE THREAD

**Issue by ostorezio** [bassmaster187/TeslaLogger#1331]
** Append Logfile **
Nothing relevant apparently, mostly a number of entry like this one:
09.07.2024 12:59:06 : #1[Thread Pool Worker:3575]: *** FT: Telemetry Server Data
09.07.2024 12:59:06 : #1[Thread Pool Worker:3575]: *** FT: Speed: 22.991
09.07.2024 12:59:06 : #1[Thread Pool Worker:3575]: *** FT: Insert Location
09.07.2024 12:59:19 : #1[StreamAPIThread_1:3381]: shift_state: D Power: 8 Datetime: 09.07.2024 12:59:19
09.07.2024 12:59:22 : #1[Thread Pool Worker:3552]: Command: vehicle_data?endpoints=drive_state%3Blocation_data%3Bclimate_state%3Bvehicle_state%3Bcharge_state%3Bvehicle_config&let_sleep=true [367]

**Describe the bug**
Geolocation (lat, lon) data during trip gets scrambled, i.e on the map the trip is shown with jumps or overlaps, as in this screenshot, the trip was a one-way, from right to left.
<img width="815" alt="Screen Shot 2024-07-09 at 2 09 18 PM" src="https://github.com/bassmaster187/TeslaLogger/assets/87861096/e1d576e0-a8aa-47a4-9398-1937a2d56673">

**To Reproduce**
Go to the baker, and look at the trip on the map

**Expected behavior**
The trip shown on map should be continuous and derivable function, no jumps, no overlaps, no back&forth.

**Screenshots**
I did a database analysis for the same trip, here's the lat/lon vs time:

![lat_lon_vs_time](https://github.com/bassmaster187/TeslaLogger/assets/87861096/8ff9ec85-8759-4544-bf6b-0b194c0e0d3c)

In the real trip, latitude should go north all the time whereas longitude should be mainly east to west, as you can see in the graph, both lat and lon has spikes

  Here is the georefences graph:
![lat_lon](https://github.com/bassmaster187/TeslaLogger/assets/87861096/06ee0fb0-71f8-4ead-8855-8b1c9a327be2)

  The trip has been one way, but from the graph it looks more or less like a round trip with overlapped legs, back & forth

** Teslalogger Type **
Raspberry Pi 4 Model B Rev 1.4
Linux raspberry 4.19.118-v7l+
Teslalogger:	1.58.9.0

** Do you use Tasker or iBeacon **
No

**Additional context**
Is that a Tesla telemetry issue? GPS scrambling?

**Comment by bassmaster187** [comment]
could you please send me an email with your VIN and the date / time of your problem.
I can just check it next week, because I'm in vacation right now

**Comment by ostorezio** [comment]
Sure, your email is?
As for the time, it happens all the time, since a few releases back.
See also Issue #1300, I have a lot of missing/incorrect data.

**Comment by ostorezio** [comment]
The lon/lat errors show a strange pattern, periodic-like, look at this:

![lat_lon_vs_time_1](https://github.com/bassmaster187/TeslaLogger/assets/87861096/3ad2be66-6ad7-4751-ab60-30f94387d1ac)

**Comment by misiu11** [comment]
I have a similar problem. The position data is very inaccurate. The recording is also very late and sometimes even stops completely. The web display is also not correct.
It still shows that my vehicle is open although it is definitely locked. 

Teslalogger runs as a VM with Debian 12 in a Docker container.
Scan my tesla is also included.

**Comment by KapUttyy** [comment]
Seems to be solved for me this morning.

**Comment by ostorezio** [comment]
Yep!
1.59.1 does the trick
