### ISSUE TITLE
No more vehicle update "Unhandled State: NULL"

### ISSUE THREAD

**Issue by Maddimax** [bassmaster187/TeslaLogger#1333]
[logfile.txt](https://github.com/user-attachments/files/16161777/logfile.txt)

**Describe the bug**
The car is shown as "Offline", and the log shows "#1[Car_1:19]: Unhandled State: NULL"

** Teslalogger Type **
Docker

** Do you use Tasker or iBeacon **
No

**Additional context**
Started happening today.

**Comment by marcofuchs89** [comment]
+1
Got the same issue since yesterday.
Driving data yesterday was collected fine, today i get the same messages 

```log
0.07.2024 14:14:51 : #1[Car_1:19]: ScanMyTesla FastMode: False
10.07.2024 14:14:51 : #1[Car_1:19]: CloseDriveState EndDate: 2024-07-10 14:11:42
10.07.2024 14:14:51 : Reverse geocoding by GeocodeCache
10.07.2024 14:14:52 : #1[Car_1:19]: Unhandled State: NULL
```

I've noticed, that the information regarding the use of Fleet API is not listed on the main page anymore - is it safe to use the Fleet-API and Virtual Key again?

**Comment by ThmsD** [comment]
Owners API seems to be deactivated by Tesla. Fleet API should work for logging.

**Comment by Maddimax** [comment]
Fleet api works for me as well.

**Comment by bassmaster187** [comment]
# Important update !!!
Tesla has been changed the API and our parser didn't like the update. 
Please update to V1.59.0

#1334
