### ISSUE TITLE
Charging average speed sometimes too high (higher than max)

### ISSUE THREAD

**Issue by endurance1968** [bassmaster187/TeslaLogger#135]
![2020-03-06_21h05_04](https://user-images.githubusercontent.com/38796027/76119683-3b4e5300-5ff0-11ea-9d50-4ccf90b58ec7.png)

average cannot be higher then max. Looks like chargingsession starttime was too late or stopped to early

**Comment by endurance1968** [comment]
Other examples are listed in https://tff-forum.de/viewtopic.php?f=58&t=24537&p=928556&sid=770ba39b4fc5f0e915fdc3fcb48f121b#p928556

**Comment by endurance1968** [comment]
Other examples are listed in https://tff-forum.de/viewtopic.php?f=58&t=24537&p=928556&sid=770ba39b4fc5f0e915fdc3fcb48f121b#p928556

**Comment by Adminius** [comment]
![image](https://user-images.githubusercontent.com/17052262/77441573-de251080-6de9-11ea-8d61-0f62f2a2738b.png)

![image](https://user-images.githubusercontent.com/17052262/77441673-fe54cf80-6de9-11ea-8cf6-3059c3bcaf2b.png)

All this charging sessions were in winter (nov-jan).

Theory:
If battery is cold, some kWh are frozen and not available. But at charging station the battery goes hot and unlock this kWhs. But (Tesla, why?!) they will be added to"charged" kWh... 
That means, TeslaLogger can nothing do in this case :/

**Comment by Adminius** [comment]
fixed in grafana
@endurance1968 close?
