### ISSUE TITLE
E-Mobility Links Dead

### ISSUE THREAD

**Issue by xercesbluebutterfly** [bassmaster187/TeslaLogger#1378]
It seems that the https://e-mobility-driving-solutions.com/ site is offline and I am too much of a noob to build this out on my 3B+ from your repo. Tried using the Docker method but the 3B+ just seems to hang from the overhead. 
Wondering if there is a way to get the Pi 3B+ (and other) images hosted here or somewhere else?

**Comment by karamba8124** [comment]
Same for me, would like to install the Pi 4b+ Image. But no other source to download this image is available instead of "e-mobility...", which is offline.
Anyone with an alternate download link? Would be nice ;-)

**Comment by bassmaster187** [comment]
Please send me an email with a request  for an image. 
I'll try to setup a new shop. 

https://www.impala64.de/blog/kontakt/

**Comment by bassmaster187** [comment]
I setup a new shop. Please try to purchase the image there. Right now it's just german, but I'll start to translate it the next few days. Please leave a feedback if everything was ok or you had any problems.

https://teslalogger.de/shop

**Comment by xercesbluebutterfly** [comment]
Have not purchased the image, because I ended up getting things working with the latest LITE Pi OS and then donating on your link.
But the site opens and looks to work, my browser's translation function makes everything clear enough. Thank you for continuing to support this.

**Comment by ibrahimcengiz** [comment]
i have installed mine using this tutorial. Working very well!

https://couchpirat.de/te33e-teslalogger-auf-dem-raspberry-pi-unter-raspbian-raspberry-os-installieren/?utm_source=chatgpt.com
