### ISSUE TITLE
Cannot add / edit any geofence / Panel not shown

### ISSUE THREAD

**Issue by bill340** [bassmaster187/TeslaLogger#1386]
I cannot add / edit any geofence.
The panel on the left side is not shown. Only the map.
<img width="1268" alt="Bildschirmfoto 2024-12-04 um 14 56 59" src="https://github.com/user-attachments/assets/f0d7514c-c739-49c9-824a-e743f122c92c">

**Comment by bassmaster187** [comment]
Do you already have own geofence points? If not, you need to add new geopoints by clicking on a start address at trips dashboard.

**Comment by bill340** [comment]
Thank you!! That was it!!
