### ISSUE TITLE
Admin dashboard language.php syntax error

### ISSUE THREAD

**Issue by mbruinenberg** [bassmaster187/TeslaLogger#150]
Warning: syntax error, unexpected '(' in /etc/teslalogger/language-en.txt on line 25 in /var/www/html/admin/language.php on line 22

**Comment by mbruinenberg** [comment]
![image](https://user-images.githubusercontent.com/40057997/76624467-a8ed0880-6535-11ea-9506-5173c57dc6f6.png)

**Comment by mbruinenberg** [comment]
![image](https://user-images.githubusercontent.com/40057997/76624553-cb7f2180-6535-11ea-98d2-2674c47220f0.png)

**Comment by bassmaster187** [comment]
What enviroment do you have? 
Version? Raspberry, Docker or anything selfemade?

Did you try an update & reboot?

**Comment by mbruinenberg** [comment]
Docker-compose setup on Raspberry.

Updates are working properly but the language-en file seems to have an 'syntax error' on line 25.
I now manally remove the '(' and ')' parentheses. Then the 'Warning' message in dashboard is gone.

**Comment by bassmaster187** [comment]
Please update and try again. Should be fixed. 

https://github.com/bassmaster187/TeslaLogger/commit/e1931dfbb487c834e46d4ea51e1376ccb4a066b6

**Comment by mbruinenberg** [comment]
Hi Christian,

Thanks!

The update fixed the English language message property.

Kind regards
