### ISSUE TITLE
Supercharger CH-Kriegstetten

### ISSUE THREAD

**Issue by rowich** [bassmaster187/TeslaLogger#151]
Teslalogger wasn't able to replace the address according to geofence.csv

This is what geofence.csv contains
Supercharger CH-Kriegstetten, 47.1753676, 7.5967831

This is my "private" setting, detected from the car and manually added
Supercharger CH-Kriegstetten,47.175635,7.59883,30

**Comment by bassmaster187** [comment]
could you please make a pull request?

**Comment by rowich** [comment]
Pull request #153 created.
