### ISSUE TITLE
MQTT - send a special status during the attempt to sleep

### ISSUE THREAD

**Issue by spitzlbergerj** [bassmaster187/TeslaLogger#154]
I use the states sent via MQTT from TeslaLogger to trigger further actions in my home automation. In addition, I request further data from the vehicle via [teslams ](https://github.com/hjespers/teslams) as long as teslalogger does not yet provide this data via MQTT ([see Issue #130](https://github.com/bassmaster187/TeslaLogger/issues/130)).

But I have to stop these queries via teslams as soon as the vehicle tries to sleep. I could reliably determine this point in time using a separate MQTT telegram from teslalogger.

The status could then be called online2sleep or offline2sleep to make the actual status visible.

**Comment by Adminius** [comment]
Implemented: "falling_asleep": false

@bassmaster187 close?
