### ISSUE TITLE
EntityName. Line 20, position 48. (/etc/teslalogger/TeslaLogger.exe.config)

### ISSUE THREAD

**Issue by DariBer** [bassmaster187/TeslaLogger#159]
I get some error messages when I start TeslaLogger (docker version)
I rund docker on a Ubuntu 18.04 and in the log files I see this:

teslalogger_1  | [ERROR] FATAL UNHANDLED EXCEPTION: System.Configuration.ConfigurationErrorsException: Error Initializing the configuration system. ---> System.Configuration.ConfigurationErrorsException: An error occurred while parsing EntityName. Line 20, position 48. (/etc/teslalogger/TeslaLogger.exe.config) ---> System.Xml.XmlException: An error occurred while parsing EntityName. Line 20, position 48.

teslalogger_1  | Unhandled Exception:
teslalogger_1  | System.Configuration.ConfigurationErrorsException: Error Initializing the configuration system. ---> System.Configuration.ConfigurationErrorsException: An error occurred while parsing EntityName. Line 20, position 48. (/etc/teslalogger/TeslaLogger.exe.config) ---> System.Xml.XmlException: An error occurred while parsing EntityName. Line 20, position 48.

**Comment by DariBer** [comment]
I can also see this in the log when I try to do some changes in the settings( seems to be permission, but I don't know what file to change the permission for.. as I can't see the file that the log is referring to (se bellow)

webserver_1    | [Thu Apr 02 12:14:15.039758 2020] [php7:warn] [pid 22] [client 192.168.50.245:56189] PHP Warning:  file_put_contents(/etc/teslalogger/settings.json): failed to open stream: Permission denied in /var/www/html/admin/settings_write.php on line 31, referer: http://192.168.50.65:8888/admin/settings.php

webserver_1    | 192.168.50.245 - - [02/Apr/2020:12:14:15 +0200] "POST /admin/settings_write.php HTTP/1.1" 200 240 "http://192.168.50.65:8888/admin/settings.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15"

webserver_1    | 192.168.50.245 - - [02/Apr/2020:12:14:17 +0200] "GET /admin/settings.php HTTP/1.1" 200 1699 "http://192.168.50.65:8888/admin/settings.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15"

webserver_1    | [Thu Apr 02 12:14:17.758744 2020] [php7:warn] [pid 22] [client 192.168.50.245:56189] PHP Warning:  syntax error, unexpected '(' in /etc/teslalogger/language-en.txt on line 25\n in /var/www/html/admin/language.php on line 22, referer: http://192.168.50.65:8888/admin/settings.php

webserver_1    | [Thu Apr 02 12:14:17.758777 2020] [php7:notice] [pid 22] [client 192.168.50.245:56189] PHP Notice:  Undefined variable: json_data in /var/www/html/admin/settings.php on line 5, referer: http://192.168.50.65:8888/admin/settings.php

**Comment by DariBer** [comment]
seems it's my password that causing the error message. in my password I have special characters like * ( & @ and it seems like the & is "Line 20, position 48"

I have bought the TeslaLogger image from you to my RPi, and it works fine there with my password. So I know that it should work

**Comment by pbertra** [comment]
The first problem is clearly due to special characters. You should maybe try to respresent them with the correct XML value. For example & should be &amp;
No issue with permission on my side. I followed the instructions to start everything and did not change anything for uid or gid on the container... But these files are now owned by root with rights 644

**Comment by DariBer** [comment]
Got it to work, did a xml value check on my password (changed the value for & sign) and now it works. It seems when that started to work that it also changed automatically the permissions. Don’t have that error message anymore.
