### ISSUE TITLE
Startup of TeslaLogger should focuss in "Home" setting (configurable) on the last trip / charging event 

### ISSUE THREAD

**Issue by Jagganaut** [bassmaster187/TeslaLogger#16]
If i open the TeslaLogger i'm interested in data from the last trip or the last charging.
That could be left like already in the app (-3 hours) or could be adapted to that 
kind of intuitive setting "Last Trip" "Last Charging". It takes only some time/clicks to 
adjust that properly .. but that is every time necessary in my case.
It's not an issue  ... i would see that as an enhancement. The periods to determine a 
trip could be configurable too or fixed to a setting of 1 or 2 hours without movement of the car.

**Comment by bassmaster187** [comment]
Please update to the latest version and check if that's what you are looking for.
