### ISSUE TITLE
after update to 1.40.0.0 the "share charge curves" doesn't disappear after pressing yes

### ISSUE THREAD

**Issue by DariBer** [bassmaster187/TeslaLogger#160]
After I update to 1.40.0.0 and get the question "Share charge curves / degradation curves anonymously" I press yes, but nothing happens, The question is still there. And in the log file I can see this.

03.04.2020 08:38:27 : ShareData: NOT Sharing Data! :-(

I'm running docker on Linux Ubuntu 18.04

**Comment by bassmaster187** [comment]
It seems like it's a permission problem. I'll search a workaround for this

**Comment by DariBer** [comment]
I can also see, that you have worked with the translation, great :-)
When the car goes in sleep mode, it say
"Status: Schlafen" That's the only thing I can see that haven't been translated.
Do you want me to open a new ticket or is it OK to have it here?

**Comment by bassmaster187** [comment]
It's ok.

**Comment by bassmaster187** [comment]
https://github.com/bassmaster187/TeslaLogger/commit/9be9653a47d9e2546b82629d6b0cfe97f68d17ff
