### ISSUE TITLE
message "Share charge curves..." still there after accepted

### ISSUE THREAD

**Issue by DariBer** [bassmaster187/TeslaLogger#161]
the message "Share charge curves / degradation curves anonymously" is still there after I have pressed yes.

Now I can see in the log that it sends an OK and share the data, but the message and No/Yes is still there. This my log file now

04.04.2020 16:39:17 : ShareData: Your charging data / degradation data will be shared anonymously to the community. Thank you!

I use version. Teslalogger: 1.40.1.0 Docker version on Ubuntu 18.04

**Comment by bassmaster187** [comment]
https://github.com/bassmaster187/TeslaLogger/commit/9889966b0a4be2034a13659526b4dc381b7827b4
