### ISSUE TITLE
Docker Backup

### ISSUE THREAD

**Issue by DariBer** [bassmaster187/TeslaLogger#163]
When I press the "Backup" button in the admin page, I get an blank page with the text OK. But I can't find any backup files. There's no info in the logfile.

Where should the log file be stored? as I can't find them.

**Comment by bassmaster187** [comment]
backup is located in /etc/teslalogger/backup

**Comment by pbertra** [comment]
backup.sh is not executable. I had the same issue. Had to chmod u+x backup.sh to make it work.

> 172.19.0.1 - - [19/Apr/2020:17:39:11 +0200] "GET /admin/current_json.php HTTP/1.1" 200 679 "http://homeautomation.lan:8888/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
> sh: 1: /etc/teslalogger/backup.sh: Permission denied
