### ISSUE TITLE
Enter charging costs

### ISSUE THREAD

**Issue by bassmaster187** [bassmaster187/TeslaLogger#164]

**Comment by Adminius** [comment]
for supercharger, we can add prices to geofence file directly, see also #156 
but for all other the price depends on used RFID card or app.
Idea: add a price.csv file with network (Ionity, Fastned, EnBW and so on) pricing.
f.i.:
Network - Price in cent/kWh
Ionity 35
Fastned 35
EnBW 39

**Comment by bassmaster187** [comment]
Maybe we should write down all needs before we start developing this feature.

**Comment by Scotty1928** [comment]
I'd recommend not only having the option to enter charging cost but also be able to provide two prices for things like home charging and minute based charging at certain locations.

Also we'd need the ability to use different currencies, like CHF, NOK or GBP besides € and the ability to convert this based on the day-to-day exchange rate.

**Comment by fibsmaster** [comment]
please dont forget session bases prices.
so for now we need something like that: 
29k = 29 per kw/h
19m = 19 per minute
790s = 790 per session

**Comment by Adminius** [comment]
Idea:
pricing.csv
NETWORK | AC/DC | PRICE | TYPE | CURRENCY
```
Ionity | DC | 0.79 | kWh | EUR
EnBW | AC | 0.29 | kWh | EUR
EnBW | DC | 0.39 | kWh | EUR
XYZ | AC | 7.90 | session | SEK
Fortum | DC | 2.00 | min | NOK
Fortum | DC | 2.50 | kWh | NOK
```
Forum has min+kWh simultaneously... so both should be counted.
May be it's easier this way: 
```
NETWORK | AC/DC | CURRENCY | PRICE1 | TYPE1 | PRICE2 | TYPE2
Ionity | DC | EUR | 0.79 | kWh | | 
Fortum | DC | NOK | 2.00 | min | 2.50 | kWh
```
Still not perfect... but more or less flexible
for HomeCharging it could be "special Private-Network"?

AC / DC is already implemented.

**Comment by bassmaster187** [comment]
How to treat changes in prices?
Maybe 2 columns with start date and end date?

**Comment by fibsmaster** [comment]
PRICE_MODEL,AC/DC,CURRENCY,PRICE_PER_KWH,PRICE_PER_MINUTE,PRICE_PER_SESSION,INITIAL_PRICE,EXTRA_FEE_PER_MINUTE
Supercharger,DC,EUR,0.33/0.34/0,,,,
Hamburg-Enegie,AC,EUR,0.27,,5.9,,

This were my first thoughts to implement prices.
I need to have different prices for one Network.
e.g.:
When charging more than x KWH I will go for the session fee, when charging less than x KHW I will use Plugsurfing KWH based.

Only way for me would be:
Adding all different prices in pricing.csv and let Teslalogger check if there are multiple prices.
Show last Charge on admin page and let me select the price.

Same for Supercharger 0.33, 0.34 and 0 if you have free KM left.

Changes will be no deal if you keep your prices.csv up to date und TL is calculating the total when charging is done and we get another field in the DB "costs"

**Comment by fibsmaster** [comment]
Well... I think it's too complex to automate.
So many different prices and circumstances.
I will now go for another solution. I thought about a new DB-Field chargingstate.costs default NULL
In Grafana it will be displayed as "-" rendered as link, pointing to a php file where you can enter the price for this column. In most cases I either have an invoice/receipt or chaging history in some app.
Ok, it will be a pain in the ass for someone charging every day. But it would also suck to doublecheck every single calculated value.

**Comment by Scotty1928** [comment]
So we'll be able to enter charging costs for every single charge event? That'd be a good compromise.

**Comment by bassmaster187** [comment]
I mostly use Maingau for all chargers, so maybe a default card for a network should be selectable.

**Comment by huesekram** [comment]
I added a table to define my charging tarifs. After charging I then link the tarif to the charge event. I have choosen this since for example Ionity you can charge at multiple prices from flatrate over very decent Maingau cost/kWh to excessive ad hoc cost.
When I select the tarif I can also add the kWh from the invoice. This allows to calculate charging efficiency.
Just an idea that is flexible and easy to implement

**Comment by superfloh247** [comment]
simples charging costs like flat rate or price per kWh could be implemented using POI special flags, eg.
+cco:0.29€/kWh
+cco:5.24€/flat
+cco:0.10€/min
no combinations or conditions like "Standgebühr nach 4h"

**Comment by huesekram** [comment]
this does not solve the problem that you can use the same charge point with different tarifs, e.g. Ionity 
Depending on the kWh you are loading it can be cheaper to use the Maingau card (cost / kWh) or Chargemap (flat rate)

**Comment by superfloh247** [comment]
better simple than nothing?

**Comment by Scotty1928** [comment]
What would solve the problem to some extend is entering the total cost after a first "reference charging session". The logger could then just calculate a per kwh price which is applied for the following sessions afterwards, until a new total cost is entered, which in turn is used for this and following sessions. It might deviate based on charging curve but i believe it would be negligibly low.

**Comment by bassmaster187** [comment]
Done in 1.43.9.0 but I leave it open for further ideas / bugs

**Comment by joriws** [comment]
For further ideas, cost should also have TOD (time of day) based option to be able set 22-08 (night) different price from 08-22 (day). For improving the times should be user settable.

Then on teslalogger screen when evaluating cost you multiply kwh charged at night time plus kwh charged at day time.

This day/night is not for fast chargers, but for home charging where it is possible to have day/night tariff at least in Scandinavia. 

--

There is also a seasonal option winter/non-winter but maybe that is already too complicated.

--

Some Tesla owners also have 1h resolution stock electricity tariff for cheapest charging hour tariff. So maybe support for that could be considered too as I don't believe there is any other system capable evaluating charging cost than teslalogger. Maybe it would work by downloading hourly stock rates from public APIs, add margin (configurable) of electricity provider and teslalogger then uses per hour price to multiply with kwh loaded in that hour.

[(https://www.nordpoolgroup.com/trading/Day-ahead-trading/)]

**Comment by rowich** [comment]
Swotzerland has low/high price schemes with high tariff 6-21 during the
week and low from Saturday 12 to Monday 6. So, if there would be such a
configuration, it must be very flexible. Looks not very easy to handle
properly.

Am 21.07.2021 um 09:39 schrieb joriws:
