### ISSUE TITLE
[FR] Summer/Winter tires

### ISSUE THREAD

**Issue by Adminius** [bassmaster187/TeslaLogger#168]
Sommer/Winterreifen Tausch markieren und jeweils gefahrene km Zählen.

Realisierungsvorschlag:
Tire.scv:
Sommer/Winter|Set|Datum
Code: Alles auswählen
S|1|06.06.2019
W|1|01.11.2019
S|1|26.04.2020
W|1|15.10.2020
S|2|15.04.2021

Sommer/Winter dürfte wohl klar sein.
Set: Welcher Satz-Reifen. Da ich letzten Sommer viel Spaß hatte, muss ich wohl zum nächsten Sommer neue Sommerreifen kaufen, somit wäre es ein neuer Satz (S|2).
Grafana hat dann ein neues Board: Reifenset (oder ähnlich).
Dann werden Saisons dargestellt:
Sommer 2019: Set 1, von 0 km bis 16987 km
Winter 2020: Set 1, von 16987 km bis 27123 km
Sommer 2020: Set 1, von 27123 km bis 38456km

usw. Und irgendwie muss man km-Gesamtleitung des jeweiligen Sets darstellen (evtl. einfach zusätzliche Spalte).
km-Stand einfach am Ende des Tages nehmen um keine Rocket-Science daraus zu machen.
Nur ein Problem sehe ich: Ich hatte bei km 0 noch keinen Logger. Da könnte ich vorstellen, dass man in der Tire.csv als zusätzliche Spalte auch km-Stand (optional) angibt. Dann muss TL nicht drüber nachdenken :)

**Comment by 955i** [comment]
Hallo,
wie sieht es denn mit einer Umsetzung aus, der nächste Radwechsel steht ja bald an.  ;-)
Würde mich sehr freuen, wenn ich die Laufleistung der Radsätze auch in Grafana finden könnte.

Vielen Dank

**Comment by Adminius** [comment]
It's now possible:
Menu: Extras->Journeys
