### ISSUE TITLE
Wrong battery level after reboot

### ISSUE THREAD

**Issue by RetoHB** [bassmaster187/TeslaLogger#175]
Battery level is wrong in Dashboard/Admin panel after Teslalogger reboot. Stays incorrect until next trip is driven. Simply waking car up does not help.

**Comment by superfloh247** [comment]
should be fixed with https://github.com/bassmaster187/TeslaLogger/commit/b4a76defc21b9694a4e0089ad4b93b7106944a28
please retest with TeslaLogger 1.42.0.0 or newer
