### ISSUE TITLE
Docker image 

### ISSUE THREAD

**Issue by cleanev** [bassmaster187/TeslaLogger#178]
Hello all,

I started with this [link](https://github.com/bassmaster187/TeslaLogger/blob/master/docker_setup.md)
and followed it thru all the way till I ended up with an error for mariadb, it seems. Any help appreciated.

Using Raspberry 3B+ with 64GB MicroSD card

pi@raspberrypi:~/TeslaLogger $ docker-compose up -d
Creating network "teslalogger_default" with the default driver
Creating volume "teslalogger_teslalogger-grafana" with default driver
Creating volume "teslalogger_teslalogger-grafana-usr" with default driver
Creating volume "teslalogger_teslalogger-tmp" with default driver
**Pulling database (mariadb:10.4.7)...
10.4.7: Pulling from library/mariadb
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries**

docker & docker-compose versions
pi@raspberrypi:TeslaLogger $ docker -v
Docker version 19.03.8, build afacb8b
pi@raspberrypi:TeslaLogger $ docker-compose -v
docker-compose version 1.25.5, build unknown

**Comment by bassmaster187** [comment]
MariaDB doesn't work with a 32Bit host OS. So you either have to use a 64bit OS on your Raspberry or you have to use the official Image:
https://e-mobility-driving-solutions.com/produkt/teslalogger-image/?lang=en
