### ISSUE TITLE
drop shadow in dashboard

### ISSUE THREAD

**Issue by Scotty1928** [bassmaster187/TeslaLogger#179]
there's a drop shadow for "wird geladen", but not for the rest. please add that for all the text on the dashboard, for obvious reasons in the attached screenshot.

https://i.imgur.com/Tw1Yyo2.png

**Comment by Adminius** [comment]
Hi, shadow is defined here:
https://github.com/bassmaster187/TeslaLogger/blob/master/TeslaLogger/www/admin/dashboard.css#L62
you can delete it or add similar line to other lines.
