### ISSUE TITLE
Japanese strings not showing up properly

### ISSUE THREAD

**Issue by claudacate** [bassmaster187/TeslaLogger#181]
The starting and destination address show up as question marks, because the string coding aren't in  UTF8.  Is there anyway to change that?

**Comment by bassmaster187** [comment]
please update to the latest version. If you use Docker, then you have to change the connectionstring in Teslalogger.exe.config.

```
<setting name="DBConnectionstring" serializeAs="String">           
<value>Server=database;Database=teslalogger;Uid=root;Password=teslalogger;CharSet=utf8;</value>
</setting>

```

Are you interested in translating Teslalogger to japanese? It's just one file and it can be done in 15 minutes: 
https://github.com/bassmaster187/TeslaLogger/blob/master/TeslaLogger/bin/language-en.txt

![image](https://user-images.githubusercontent.com/6816385/81512510-4cce1700-9321-11ea-8cce-bbf3aae18db3.png)

**Comment by bassmaster187** [comment]
because of no feedback, i suppose the bug is solved.

**Comment by claudacate** [comment]
I am so sorry for this late reply.  Yes the issue has been resolved.  Thank you for the assistance
