### ISSUE TITLE
Tesla API credentials via ENV not config file

### ISSUE THREAD

**Issue by kevinelliott** [bassmaster187/TeslaLogger#182]
For docker users, it would be better to store the Tesla API credentials via ENV rather than in a config file. This is because that would allow us to generate safe images for Docker Hub (or other repos) without worry of credentials being inside, and we can dynamically change those credentials at docker runtime.

Alternatively, if not in ENV, it should be done via a web UI and stored into the DB. But at the very least it should not be tied to a file system configuration file.

**Comment by Adminius** [comment]
similar to #81

**Comment by VibroAxe** [comment]
@bassmaster187 There's two ways to do this through docker. One is to use volume mapping to load a separate version of the config file into the container (allowing those variables to be set). The other is to use a startup script to bootstrap, change the .config file and then run the .exe

Happy to submit a PR (either to documentation or code as appropriate) which would then mean you can build this with dockerhub or GitHub actions. Any preference?

**Comment by bassmaster187** [comment]
Actually it is not necessary anymore to provide  tesla credentials trough config file. Just go to setting / tesla credentials and insert a new car. I'll change the docs the next few days.
