### ISSUE TITLE
User-Backup Script

### ISSUE THREAD

**Issue by bassmaster187** [bassmaster187/TeslaLogger#200]
**Is your feature request related to a problem? Please describe.**
After the backup will be made, it must moved to a different location.

**Describe the solution you'd like**
There Should be a script my-backup.sh to be able to do thinks after the backup is done. e.g. move the files to dropbox / NAS...

Please provide ready to go templates for popular cloud services / ftp / NAS

**Comment by Adminius** [comment]
webdav or nextcloud or GoogleDrive would be great.

**Comment by rowich** [comment]
I am picking the current file using a "Scheduled Task" (aka Cron Job)
and a script running outside of Teslalogger. Saving another set of
credentials on Teslalogger is no real option from my point of view.

Am 28/05/2020 um 09:23 schrieb Eugen:

**Comment by Adminius** [comment]
How about GDrive?https://linuxnewbieguide.org/using-google-drive-from-the-linux-command-line/

command line upload is possible

**Comment by bassmaster187** [comment]
rclone seams to have almost everything we need:
https://rclone.org/

**Comment by Adminius** [comment]
https://github.com/bassmaster187/TeslaLogger/blob/master/backup_to_google_drive.md
