### ISSUE TITLE
Tag Home and Work

### ISSUE THREAD

**Issue by bassmaster187** [bassmaster187/TeslaLogger#201]
**Describe the solution you'd like**
Make it possible to tag "Home" and "Work" in geofence-public.csv. 
- We can make more statistics (e.g. charging home / public)
- chargings tagged with home and work will never been uploaded. That can happen, if GPS coverage is bad or a fast charger is nearby.
- We can draw a "Home" icon on statistics.

**Comment by superfloh247** [comment]
special flag in geofence-private.csv?
+home
+work

**Comment by superfloh247** [comment]
https://github.com/superfloh247/TeslaLogger/commit/9573851d6de645eae8a9e84cf55f29ac981ad25c

**Comment by Adminius** [comment]
@superfloh247 & @bassmaster187 
It's done, close?

**Comment by superfloh247** [comment]
There is no useful application yet :)

**Comment by Adminius** [comment]
yeah... but the implementation for tagging is done -> close ;)

**Comment by bassmaster187** [comment]
done
