### ISSUE TITLE
Synology docker installation: DBCONNECTION not allowed to connect to MariaDB server

### ISSUE THREAD

**Issue by tomac01** [bassmaster187/TeslaLogger#208]
Hi,
I installed the TeslaLogger according to the instructions for installation in the docker on Synology. So far everything works, except for one:
According to the log, the MariaDB refuses to register with the following error:
DBCONNECTION Host '172.18.0.5' is not allowed to connect to this MariaDB server

What could be the problem?

Thanks in advance!

**Comment by bassmaster187** [comment]
That's strange as it works on many synology installations.

Could you please check these points and post the results, so I can compare them with a working synology installation:
https://github.com/docker-library/mysql/issues/275#issuecomment-292208567

**Comment by tomac01** [comment]
ok, i am here now:

after I created "root @%" and set the password of root, the connection worked.

Unfortunately there is now another error that leads me to assume that the entire DB schema for teslalogger-DB was not created. according to the docker instructions, there is nothing to do.

>show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| test               |
+--------------------+


Did I forget something?

Here is the error according to the log:
DBCONNECTION Authentication to host 'database' for user 'root' using method 'mysql_native_password' failed with message: Unknown database 'teslalogger'

**Comment by bassmaster187** [comment]
ok, it really seams, the init script didn't run smoothly. Could you please look in the logfile of mariadb container if there are any errors? 

I was told anybody got other issus with docker, becuase of write permissions in docker folder or maybe because docker was not started as root or anything.

**Comment by tomac01** [comment]
I can't find an error.log.

There is nothing under "/ var / log / mysql".

The command: "show global variables like 'log_error';" outputs the following:
+ --------------- + ------- +
| Variable_name | Value |
+ --------------- + ------- +
| log_error | |
+ --------------- + ------- +

Do you have a tip where else to look?

**Comment by bassmaster187** [comment]
At the first start, it might take a long time until MariaDB is ready and Teslalogger can connect to the Database, so you might wait a couple of minutes depending on the power of your cpu. It is very importat you don't interrupt the creation of the database.

Docker usualy don't write to /var/log - it redirect them to docker. Either you use "docker logs" command: https://docs.docker.com/engine/reference/commandline/logs/
Or synology has got a gui for that (at least mine)...
Go to Docker / Container / double click teslalogger_database_1 / log 

![image](https://user-images.githubusercontent.com/6816385/84184343-751a7400-aa8d-11ea-816c-f1afe21f63a2.png)

**Comment by bassmaster187** [comment]
It seems like the creation of the database on my DS718+ took 5 Minutes:

```
21.02.2020 16:22:35 : TeslaLogger Version: 1.38.2.0
21.02.2020 16:22:35 : Logfile Version: 1.0.7.0
21.02.2020 16:22:35 : SRTM Version: 0.0.3.0
21.02.2020 16:22:35 : Docker: YES!
21.02.2020 16:22:35 : Creating empty settings.json
21.02.2020 16:22:35 : chmod 666 /etc/teslalogger/settings.json
21.02.2020 16:22:35 : Current Culture: en-US
21.02.2020 16:22:35 : Mono Runtime: 6.0.0.313 (tarball Sun Jul 14 09:55:10 UTC 2019)
21.02.2020 16:22:35 : Grafana Version: 6.3.5
21.02.2020 16:22:35 : DBConnectionstring: Server=database;Database=teslalogger;Uid=root;Password=teslalogger;
21.02.2020 16:22:35 : Car#:0
21.02.2020 16:22:35 : KeepOnlineMinAfterUsage: 15
21.02.2020 16:22:35 : SuspendAPIMinutes: 21
21.02.2020 16:22:35 : SleepPositions: 5000
21.02.2020 16:22:36 : UseScanMyTesla: False
21.02.2020 16:22:36 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:22:51 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:23:06 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:23:21 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:23:36 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:23:51 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:24:06 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:24:21 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:24:36 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:24:51 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:25:06 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:25:21 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:25:36 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
21.02.2020 16:27:18 : TeslaLogger Version: 1.38.2.0
```

**Comment by tomac01** [comment]
yeah, the reinstallation did it.

Maybe I interrupted the DB creation process the first time ... I don't know.

Now the connection is ok.

Thanks for the quick replies!

**Comment by dtscha1** [comment]
I've got the same issue on my Synology DS620slim NAS on docker. I did the installation two times, but every time the DB connection fails:

03.02.2021 23:06:18 : TeslaLogger Version: 1.46.0.0
03.02.2021 23:06:20 : Teslalogger Online Version: 1.46.0.0
03.02.2021 23:06:20 : Logfile Version: 1.0.10.0
03.02.2021 23:06:20 : SRTM Version: 0.0.3.0
03.02.2021 23:06:20 : Docker: YES!
03.02.2021 23:06:20 : Current Culture: en-US
03.02.2021 23:06:20 : Mono Runtime: 5.20.1.34 (tarball Tue Jul 16 22:52:22 UTC 2019)
03.02.2021 23:06:21 : Connection refused
03.02.2021 23:07:11 : Grafana Version: ?
03.02.2021 23:07:11 : OS Version: Unix 4.4.59.0
03.02.2021 23:07:14 : Update Settings: all
03.02.2021 23:07:14 : DBConnectionstring: Server=database;Database=teslalogger;Uid=root;Password=teslalogger;charset=utf8mb4
03.02.2021 23:07:14 : KeepOnlineMinAfterUsage: 15
03.02.2021 23:07:14 : SuspendAPIMinutes: 21
03.02.2021 23:07:14 : SleepPositions: 5000
03.02.2021 23:07:14 : UseScanMyTesla: False
03.02.2021 23:07:14 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:07:29 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:07:44 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:07:59 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:08:14 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:08:29 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:08:44 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:08:59 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:09:14 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:09:29 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:09:44 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:09:59 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:10:14 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
03.02.2021 23:10:29 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.

**Comment by mss1010** [comment]
For me this was solved, after I recreated the environment with

`docker-compose down` and `docker-compose up -d`

**Comment by mareeekkkk** [comment]
Having the same issue, while installing on Synology DSM7. 
Followed the instructions but got the following log. I waited for around 10 minutes without touching anything but there is some communication problem to the database. Also tried all the above, adding % root to the user list in mysql. This then gives me the errror `DBCONNECTION Authentication to host 'database' for user 'root' using method 'mysql_native_password' failed with message: Unknown database 'teslalogger'`

Cant find the solution to this.. Also reinstalling didn't fix it for me eighter. 

```
06.03.2024 16:15:18 : Runtime: 4.0.30319.42000
06.03.2024 16:15:18 : TeslaLogger Version: 1.57.7.0
06.03.2024 16:15:18 : Teslalogger Online Version: 1.57.7.0
06.03.2024 16:15:18 : Logfile Version: 1.0.15.0
06.03.2024 16:15:18 : SRTM Version: 0.0.4.0
06.03.2024 16:15:18 : OS: Debian GNU/Linux 10 (buster)
06.03.2024 16:15:18 : Docker: YES!
06.03.2024 16:15:18 : Creating empty settings.json
06.03.2024 16:15:18 : chmod 666 /etc/teslalogger/settings.json
06.03.2024 16:15:18 : chmod 777 /etc/teslalogger/backup
06.03.2024 16:15:18 : chmod 777 /etc/teslalogger/Exception

06.03.2024 16:15:19 : Current Culture: en-US
06.03.2024 16:15:19 : Mono Runtime: 6.12.0.122 (tarball Mon Feb 22 17:42:49 UTC 2021)
06.03.2024 16:15:19 : Grafana Version: CF
06.03.2024 16:15:19 : OS Version: Unix 4.4.302.0
06.03.2024 16:15:19 : Update Settings: all
06.03.2024 16:15:19 : DBConnectionstring: Server=database;Database=teslalogger;Uid=root;Password=teslalogger;CharSet=utf8mb4;
06.03.2024 16:15:19 : KeepOnlineMinAfterUsage: 5
06.03.2024 16:15:19 : SuspendAPIMinutes: 30
06.03.2024 16:15:19 : SleepPositions: 5000
06.03.2024 16:15:19 : UseScanMyTesla: False
06.03.2024 16:15:19 : StreamingPos not found in settings.json
06.03.2024 16:15:19 : StreamingPos: False
06.03.2024 16:15:19 : Free disk space: 21544008mb
06.03.2024 16:15:19 : Wait for DB (1/30): Connection refused.
06.03.2024 16:15:34 : Wait for DB (2/30): Connection refused.
06.03.2024 16:15:49 : Wait for DB (3/30): Connection refused.
06.03.2024 16:16:04 : Wait for DB (4/30): Connection refused.
06.03.2024 16:16:19 : Wait for DB (5/30): Connection refused.
06.03.2024 16:16:34 : Wait for DB (6/30): Connection refused.
06.03.2024 16:16:49 : Wait for DB (7/30): Connection refused.
06.03.2024 16:17:04 : Wait for DB (8/30): Connection refused.
06.03.2024 16:17:19 : Wait for DB (9/30): Connection refused.
06.03.2024 16:17:34 : Wait for DB (10/30): Connection refused.
06.03.2024 16:17:49 : Wait for DB (11/30): Connection refused.
06.03.2024 16:18:04 : Wait for DB (12/30): Connection refused.
06.03.2024 16:18:19 : Wait for DB (13/30): Connection refused.
06.03.2024 16:18:34 : Wait for DB (14/30): Connection refused.
06.03.2024 16:18:49 : Wait for DB (15/30): Connection refused.
06.03.2024 16:19:04 : Wait for DB (16/30): Connection refused.
06.03.2024 16:19:19 : Wait for DB (17/30): Connection refused.
06.03.2024 16:19:34 : Wait for DB (18/30): Connection refused.
06.03.2024 16:19:49 : Wait for DB (19/30): Connection refused.
06.03.2024 16:20:04 : Wait for DB (20/30): Connection refused.
06.03.2024 16:20:19 : Wait for DB (21/30): Connection refused.
06.03.2024 16:20:34 : Wait for DB (22/30): Connection refused.
06.03.2024 16:20:49 : Wait for DB (23/30): Connection refused.
06.03.2024 16:21:04 : Wait for DB (24/30): Connection refused.
06.03.2024 16:21:19 : Wait for DB (25/30): Connection refused.
06.03.2024 16:21:34 : Wait for DB (26/30): Connection refused.
06.03.2024 16:21:49 : Wait for DB (27/30): Connection refused.
06.03.2024 16:22:04 : Wait for DB (28/30): Connection refused.
06.03.2024 16:22:19 : Wait for DB (29/30): Connection refused.
06.03.2024 16:22:34 : Wait for DB (30/30): Connection refused.
06.03.2024 16:22:49 : Connection refused

```
