### ISSUE TITLE
Filters for Grafana Table Columns

### ISSUE THREAD

**Issue by superfloh247** [bassmaster187/TeslaLogger#210]
I'd like to have Filters for Grafana Table Columns.
Eg. show only rows in "Ladehistorie" where the Address contains Ikea.

**Comment by bassmaster187** [comment]
Grafana doesn't support filtering. It's only possible to have some predefined template variables and filter them in sql query.
https://github.com/grafana/grafana/issues/3956

Another option is to get rid of Grafana's build in table and use (JQuery) Datatable:
https://grafana.com/grafana/plugins/briangann-datatable-panel

**Comment by bassmaster187** [comment]
done
