### ISSUE TITLE
Plausibility check for scanmytesla integration

### ISSUE THREAD

**Issue by brau01ma** [bassmaster187/TeslaLogger#224]
the data for a Model 3 from scanmytesla are very often out of the possible range.  A check should be installed that only plausible values ​​are transferred to Teslalogger.

**Comment by Adminius** [comment]
It should be implemented on SMT side

**Comment by bassmaster187** [comment]
d2a43cf52cb609146d22c9ef67d3add6b90470fd
e3ea833e1827afb3842231bf906601fc973860ea
