### ISSUE TITLE
Git clone timing issue beim update

### ISSUE THREAD

**Issue by endurance1968** [bassmaster187/TeslaLogger#235]
Sieht so aus als würde das git clone zum update nach dem reboot in Probleme laufen, da das System noch nicht sauber initialisiert.
Vermutlich wäre die Lösung das git clone VOR dem reboot durchzuführen oder aber den logger in abhängigkeit von anderen Prozessen die noch zu finden sind zu starten.
siehe https://tff-forum.de/t/teslalogger-mit-raspberry-pi-mysql-grafana-osm/22932/4479?u=endurance

**Comment by bassmaster187** [comment]
Es wird jetzt 10 mal versucht upzudaten und das mit Pause dazwischen. Problem sollte behoben sein. Wenn nicht, bitte wieder aufmachen.
