### ISSUE TITLE
Start Location late / therefore wrong. GPS issue, Teslalogger Issue or Tasker issue?

### ISSUE THREAD

**Issue by rowich** [bassmaster187/TeslaLogger#239]
I have a lot of times the case, that Teslalogger is marking the start of a trip with a wrong/late starting position.
I believe that Tasker is working well as it's a case happening maybe 5% of the time.

Typical Example here:
2020-06-22 13:05:54 | 2020-06-22 13:22:38 | ch-3097 Köniz, Schwarzenburgstrasse 111 | ch-3014 Bern, Mingerstrasse
2020-06-22 05:07:37 | 2020-06-22 06:10:23 | ch- Münchenstein, | Work@BE

It was not detecting the start early enough (GPS fix approx 1km away from home in the morning at 05:07)
Same again after leaving the destination "Work@BE" (GPS fix was approx 500m away at 13:05)

What data can I deliver to show the stuff around that, what can I check on my own? When it happens, it happens always after a deep sleep (more than 2hrs) and never after a short stop. Note: I have good GPS conditions at home, "Work@BE" is an underground parking lot, so that case could explanable, but it happens also with good GPS availability.

**Comment by superfloh247** [comment]
Is the car logged in to a Wifi at those locations?

**Comment by rowich** [comment]
sometimes. I have a mobile hotspot in the car, but if that device is out
of battery due to less usage right now, the car is bound to LTE.
Therefore, the car is not loosing connectivity due to driving away from
home, it's taking it's WLAN with it.

Am 02/07/2020 um 21:10 schrieb superfloh247:

**Comment by superfloh247** [comment]
My S 85 drops Wifi as soon as I shift from P to D, no matter if it's the mobile hotspot or home Wifi. Then the car is offline for approx 1 minute. TeslaLogger usually runs into a 100s timeout then.

**Comment by rowich** [comment]
OK, that could be an explanation. I have a mobile hotspot in the car.
Switch from WLAN to LTE in my Model 3 seems to be with no visible
interruption, but anyway, will keep an eye on this (if this is happening
while the mobile hotspot was active at time of entering the car).

100s seems to be long. In the area I am living at are a couple of areas
in which the car suddenly need to switch the mobile provider (swiss ->
french -> german -> back to swiss) which is always combined with a short
outage. 30s would be long enough from my point of view.

Am 04/07/2020 um 20:39 schrieb superfloh247:

**Comment by superfloh247** [comment]
Starting with version 1.43.4.0 the timeout for some requests is now 11 seconds.

**Comment by rowich** [comment]
Ok, great. Will check today/tomorrow if I still see the issue. Will try to start a ride from deep sleep without any special workaround - enter the car, "D", go.

**Comment by rowich** [comment]
v1.43.6, still exactly the same behaviour, unfortunately. I am missing the first Kilometer of every trip. I am now going to check behaviour with no mobile hotspot active in the car during sleep.

**Comment by rowich** [comment]
Happens only if the car was booked into a WLAN/Hotspot while sleeping. Not a Teslalogger Issue and probably nothing to change in Tesla logger. It does not happen if the car was always in LTE-Mode.
