### ISSUE TITLE
HTML "title" in config page contains a fixed "V1.9" specification since ages

### ISSUE THREAD

**Issue by rowich** [bassmaster187/TeslaLogger#256]
TeslaLogger Config page starts with the following code:

```
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="apple-mobile-web-app-title" content="Teslalogger Config">
    <link rel="apple-touch-icon" href="img/apple-touch-icon.png">
    <title>Teslalogger Config V1.9</title>
	<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
	<link rel="stylesheet" href="https://teslalogger.de/teslalogger_style.css">
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script src="https://code.jquery.com/jquery-migrate-1.4.1.min.js"></script>
```

The version seems to be hard coded in the HTML template. From my point of view, not needed, version could be removed from the data.

**Comment by Adminius** [comment]
It is a version auf Admin-Page. And current version is V1.9 ...

**Comment by rowich** [comment]
Cannot believe that: It's the same version since ages, while the
contained data, the design and the features have improved dramatically.

Am 20/07/2020 um 09:50 schrieb Eugen:

**Comment by bassmaster187** [comment]
@rowich  you're right. I forgot to update the version. Meanwhile we have dozens of updates in Admin-Page.

**Comment by rowich** [comment]
:-)
Just remove the version number. Redundant information.

Am 21/07/2020 um 13:18 schrieb Christian P.:
