### ISSUE TITLE
Question: how to export GPS trip data into a GPX file

### ISSUE THREAD

**Issue by rowich** [bassmaster187/TeslaLogger#261]
Any hint to get the stored GPS data used to draw the trip map into a (text-) file? GPX is a standardised XML style format.
I like to have my current roadtrip (couple of days, not only a single trip) GPS data into another software to visualise it. I probably can extract the data using Powershell or similar from the backup file or directly from the database but would like to have a hint for the table to look for and the fields to filter. I will share of course the result (script to convert the data).

-> [(https://support.relive.cc/kb/guide/en/what-is-relive-HhxKSHCzUD/Steps/34416,34418,34421,34420,34419)]

**Comment by superfloh247** [comment]
Combine DB view trip with DB table pos

**Comment by bassmaster187** [comment]
You could use the dashboard visited and select a custom time range after that you got your whole trip. That's how I made my photo books of my trips to foreign countries with my Tesla.

**Comment by rowich** [comment]
I know how to do that. But I want to export the RAW GPS data to import
into "relive.cc" (see attached URL to the original message). Goal is not
to get a map with a line (which is usually great as you said, for a
photo book etc) but an animated video.

Am 25/07/2020 um 20:57 schrieb Christian P.:

**Comment by superfloh247** [comment]
SELECT DATUM, LAT, LNG FROM POS WHERE DATUM > start AND DATUM < end

**Comment by rowich** [comment]
Great, thank you for the SQL select. Will provide a probably Powershell based script solution as soon I am back home to create GPX files out of the Teslalogger data.

**Comment by rowich** [comment]
initial release -> [https://github.com/rowich/Teslalogger2gpx]
