### ISSUE TITLE
new Feature: Journeys

### ISSUE THREAD

**Issue by superfloh247** [bassmaster187/TeslaLogger#264]
Idea: combine several trips into one journey.

Idea for implementation:
- select first and last trip in some UI (grafana? custom?) and combine into journey, add name to journey
- save journey name, first trip start pos and timestamp and last trip end pos and timestamp into new DB table "journeys"
- offer dashboard listing all journeys each with a link to dashboard "Verbrauch" for whole journey

**Comment by rowich** [comment]
seconded.

Am 04/08/2020 um 10:20 schrieb superfloh247:

**Comment by Adminius** [comment]
FR: add user defined names to journey

**Comment by superfloh247** [comment]
PR 712
