### ISSUE TITLE
MQTT Topics

### ISSUE THREAD

**Issue by ben-bole** [bassmaster187/TeslaLogger#281]
Hello,
I don't have a Tesla yet but I am developing a solution to open a garage door when the Tesla is within a geofence with node-red for an acquaintance.
To realize that I need proper documentation of all the MQTT-topics. Is it just me, or is there not something like this?

Hopefully, you can help me with that.

Best regards and stay safe,

Benedict

**Comment by bassmaster187** [comment]
Your Tesla is able to open the garage door automatically. You don't need to do anything.
