### ISSUE TITLE
Time to full charge

### ISSUE THREAD

**Issue by Adminius** [bassmaster187/TeslaLogger#295]
Add a new line in charging state:
Time to full charge:
![image](https://user-images.githubusercontent.com/17052262/91704437-e6912c80-eb7b-11ea-8f49-899aa54c459d.png)

Api:
charge_state -> 
5 Minutes:
"minutes_to_full_charge": 5,
"time_to_full_charge": 0.08,

6h 35m:
"minutes_to_full_charge": 395,
"time_to_full_charge": 6.58,

if (minutes_to_full_charge > 60){
   hours = floor(minutes_to_full_charge/60);
   minutes = minutes_to_full_charge % 60;
   string = hours + "h " + minutes + "m"
}else{
   string = minutes_to_full_charge + "m";
}

**Comment by superfloh247** [comment]
available from TeslaLogger internal web server:
https://github.com/bassmaster187/TeslaLogger/blob/multicarfeature/TeslaLogger/WebServer.md
not yet merged into master

**Comment by Adminius** [comment]
Server only or admin panel too? ;)
I need it on admin panel only (maybe also dashboard)

**Comment by bassmaster187** [comment]
https://github.com/bassmaster187/TeslaLogger/commit/72af5644092d18124f5fcbf1096e6c1874e83a24
