### ISSUE TITLE
TL did not get manual sentry_mode toggle in "park"drive_state

### ISSUE THREAD

**Issue by Adminius** [bassmaster187/TeslaLogger#296]
**Working behavior:**
Car in park drive_state
Sentry mode on/off state in automatic mode = car setting (e.g. home = off, all others = on).

**Not working behavior:**
Car in park drive_state.
e.g. home location, car setting = off.
But user enables sentry mode via Tesla App. TL didn't get this and thinks Sentry is still off.
Other case: sentry mode is on via automatic car setting (e.g. all other locations = on, except home = off)
But user turns Sentry via app off -> TL thinks Sentry is still on and doesn't let car go sleep :/

**Possible solution:**
poll vehicle_state also in parking state (solves also "not actual FW after update" problem).
Or change to vehicle_data API for all things (charging_state, drives_tate and so on). With vehicle_data we will have all data with one tesla-api-request only :)

**Comment by superfloh247** [comment]
should be fixed with 1.44.6.0 and later

**Comment by Adminius** [comment]
tested with 1.44.6.0.
Works perfect. thx!

**Comment by Adminius** [comment]
fixed
