### ISSUE TITLE
Teslalogger not logging anything anymore

### ISSUE THREAD

**Issue by pbertra** [bassmaster187/TeslaLogger#339]
After an update, Teslalogger is not logging anything anymore.

The log contains:
23.09.2020 19:40:17 : Connected!
23.09.2020 19:40:17 : 23.09.2020 19:40:17 : Connected!
23.09.2020 19:40:27 : #1: Error in GetTokenAsync: The given key 'access_token' was not present in the dictionary.

23.09.2020 19:40:27 : #1: Abort: Tesla_token == NULL
23.09.2020 19:40:27 : #1: *** Exit Loop !!!

Car status is offline, while it is not.

I get many Exceprions containing:

System.Collections.Generic.KeyNotFoundException: The given key 'access_token' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <254335e8c4aa42e3923a8ba0d5ce8650>:0
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object,st
ring)
  at TeslaLogger.WebHelper.GetTokenAsync () [0x00425] in <5aa76b20ba9341c19108d661e21825ae>:0
-------------------------
{"response":"https://myt-websvc-vip1.tesla.com:443/teslamobileservices/users/authenticate_=>_operation_timedout_with_10s_timeout_for_txid_`fa8388b8656
fb5e579b009ca443b5e79`"}

or:

System.Threading.Tasks.TaskCanceledException: A task was canceled.
  at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0
x004f5] in <6f0612d5fab3464ba6feeb141f20dbb0>:0
  at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, Sy
stem.Threading.CancellationToken cancellationToken) [0x000ca] in <6f0612d5fab3464ba6feeb141f20dbb0>:0
  at TeslaLogger.WebHelper.IsOnline () [0x0011b] in <be8c0232ab6645d9a67c6fa3696e3e5f>:0
-------------------------

So, nothing is working anymore... Help please

**Comment by pbertra** [comment]
Version 1.44.13.0... But I suspect problems appeared with the previous update

**Comment by rowich** [comment]
This is probably related to the service outage currently at Tesla.
my Teslalogger is also unable to connect to the car, and the online
accout login does not work.
I am assuming Teslalogger is not able to get a fresh token to logon due
to unreachable server infrastructure.

Be patient (and hope it's not the same reason why Garmin was recently
offline for 2 weeks)

Am 23/09/2020 um 19:48 schrieb pbertra:

**Comment by pbertra** [comment]
I had to restart the container this morning and it seems to be solved

**Comment by rowich** [comment]
Same for me.
The charging from last night was not recorded as the creation of the
Access Token was not possible. The new token was successfully created
after restarting today and access is fine again.

@Bassmaster: Would probably a good idea to retry periodically the token
creation if if it was not successfully before (due to infrastructure
issues as of yesterday)? Is quite good visible in my logfile from my
point of view.

Am 24/09/2020 um 08:40 schrieb pbertra:

**Comment by pbertra** [comment]
We could probably get some notification when the car is offline or the communication is impossible...

**Comment by bassmaster187** [comment]
@rowich periodically try to create a new token will ban you and you have to activate your account manually in mytesla.

**Comment by bassmaster187** [comment]
@pbertra : as Teslalogger has the email address of the tesla account, i could send a email. But my email server needs to know the email address, so such a feature needs an opt-in as I can collect all emails and could use it for spam or something...

**Comment by rowich** [comment]
ok, periodically retry seems to be no option. Also sending email is not an option for me. But a notification in the admin panel (why "offline" - only this case) could be one?

**Comment by pbertra** [comment]
OK. Retry seems a really bad idea.
Mail seems overkill.
What about an MQTT "status" message for teslalogger and it's connection? The user can then do something easily from this message, mail, push message, whatever he wants.

**Comment by bassmaster187** [comment]
OpenWB uses https://pushover.net/ for Notifications. 
Abetterrouteplanner uses https://www.pushbullet.com/ for Notifications.
