### ISSUE TITLE
Model Y Support?

### ISSUE THREAD

**Issue by relevante** [bassmaster187/TeslaLogger#386]
Hello,

I’m scheduled to pick up a Model Y this weekend and am thinking about setting this up on my Synology. Any ideas whether this will work with my MY? I see it’s not on the supported list but wonder if it might work, at least partially for now.

Thanks!

**Comment by bassmaster187** [comment]
As far as I know, there is no major difference between the models in the tesla API. So basically it should work. If not, I'll promise to fix it.

**Comment by relevante** [comment]
Great, thanks!

**Comment by relevante** [comment]
Just got it up and running. Looking forward to testing it out with the car on Sunday. Will report back as to how it goes.

One thing I noticed in the meantime: I'm assuming it's just a result of not having any data yet, but in some of the dashboards I see a red exclamation point icon with SQL error messages. E.g.

`Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and (pos.address like '%%') order by StartDate desc' at line 21`

I'm guessing it'll be fine once I get the car and get some data, but just wanted to bring it up now in case it's something I need to fix. Thanks again!

**Comment by bassmaster187** [comment]
The error is pretty much because you don't have a car to select in the dashboard

**Comment by relevante** [comment]
Thanks. So far it seems to be working great! I'm seeing some units inconsistencies I think on the Trips dashboard, but I'll open a new issue for that. Thanks again!
