### ISSUE TITLE
Editing geofence locations from the UI doesn't work

### ISSUE THREAD

**Issue by pbertra** [bassmaster187/TeslaLogger#388]
**Append Logfile**
No info about the issue in the logs

**Describe the bug**
When I click on the pen at the right of a location, I get the edit form but this form is empty: no field is filled in. And saving does nothing.

**To Reproduce**
Steps to reproduce the behavior: edit any POI you have in your private geofence file...

**Expected behavior**
The edit should allow to correctly edit the existing data

**Screenshots**
Not useful, just an empty form

**Teslalogger Type**
Docker, updated through the gui to the latest version

**Do you use Tasker or iBeacon**
Not relevant

**Additional context**
None

**Comment by bassmaster187** [comment]
It seems like it works on my machine:
https://youtu.be/gzerEj8z4nU

Could you please post the logs of your webserver container?

**Comment by pbertra** [comment]
Yes I see it's working on your machine, with chrome also.

Here is the excerpt of the logs:

192.168.2.60 - - [22/Oct/2020:08:40:23 +0200] "GET /admin/geoadd.php?id=6 HTTP/1.1" 200 4742 "http://192.168.2.49:8888/admin/geofencing.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
[Thu Oct 22 08:40:23.106159 2020] [php7:notice] [pid 18] [client 192.168.2.60:56537] PHP Notice:  Undefined index: lat in /var/www/html/admin/geoadd.php on line 4, referer: http://192.168.2.49:8888/admin/geofencing.php,
[Thu Oct 22 08:40:23.106430 2020] [php7:notice] [pid 18] [client 192.168.2.60:56537] PHP Notice:  Undefined index: lng in /var/www/html/admin/geoadd.php on line 5, referer: http://192.168.2.49:8888/admin/geofencing.php,
[Thu Oct 22 08:40:23.107078 2020] [php7:notice] [pid 18] [client 192.168.2.60:56537] PHP Notice:  Undefined variable: _SESSION in /var/www/html/admin/menu.php on line 25, referer: http://192.168.2.49:8888/admin/geofencing.php,
[Thu Oct 22 08:40:43.188648 2020] [php7:notice] [pid 16] [client 192.168.2.60:56538] PHP Notice:  Undefined index: lat in /var/www/html/admin/geoadd.php on line 4, referer: http://192.168.2.49:8888/admin/geofencing.php,
[Thu Oct 22 08:40:43.189089 2020] [php7:notice] [pid 16] [client 192.168.2.60:56538] PHP Notice:  Undefined index: lng in /var/www/html/admin/geoadd.php on line 5, referer: http://192.168.2.49:8888/admin/geofencing.php,
[Thu Oct 22 08:40:43.190292 2020] [php7:notice] [pid 16] [client 192.168.2.60:56538] PHP Notice:  Undefined variable: _SESSION in /var/www/html/admin/menu.php on line 25, referer: http://192.168.2.49:8888/admin/geofencing.php,
192.168.2.60 - - [22/Oct/2020:08:40:43 +0200] "GET /admin/geoadd.php?id=6 HTTP/1.1" 200 4742 "http://192.168.2.49:8888/admin/geofencing.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"

**Comment by bassmaster187** [comment]
hmm, everything seems to be ok. 

could you please zip your geocode-private.csv and send it by mail?

**Comment by pbertra** [comment]
Here it is

Le jeu. 22 oct. 2020 à 09:01, Christian P. <notifications@github.com> a
écrit :

**Comment by bassmaster187** [comment]
there is no attachment

**Comment by pbertra** [comment]
Yes there was, but it has probably been removed from the mail by github...

Le jeu. 22 oct. 2020 à 09:09, Christian P. <notifications@github.com> a
écrit :

**Comment by pbertra** [comment]
[geofence-private.zip](https://github.com/bassmaster187/TeslaLogger/files/5423595/geofence-private.zip)
I just slightly modified the coordinates of private locations...

**Comment by bassmaster187** [comment]
Could you please make a manual update (push update button) and retry. It seems like you have a different line ending.

**Comment by pbertra** [comment]
No I can edit a location properly!
But I don't see the map anymore  on the list page
![image](https://user-images.githubusercontent.com/8583637/96913953-a035bb00-14a4-11eb-8b46-9ec163b5275e.png)
And I only see 10 out of the 12 locations

**Comment by bassmaster187** [comment]
https://github.com/bassmaster187/TeslaLogger/commit/f037a979d29ea2c42eb2553c07ea2a5a7930f58d

https://github.com/bassmaster187/TeslaLogger/commit/a28e9f7c9db51a0dbcc4baa78ffc119dfaaa9635

**Comment by bassmaster187** [comment]
Sorry, please retry again

**Comment by pbertra** [comment]
Everything seems ok now
Thank you!

Le jeu. 22 oct. 2020 à 21:43, Christian P. <notifications@github.com> a
écrit :
