### ISSUE TITLE
Trip Dashboard Inconsistently Applying Miles Unit Selection

### ISSUE THREAD

**Issue by relevante** [bassmaster187/TeslaLogger#396]
I am using TeslaLogger in the US with a Model Y and have miles and kWh selected for units. On the Trips dashboard, some of the columns appear to be adjusting for miles and some are not. Here's a breakdown of what I'm seeing:

Avg Consumption kWh:
This appears to be giving Wh per 100 miles. Wh/mile is more common, but it's an easy conversion in your head, so no big deal for me.

Consumed kWh:
As expected

Duration Min:
As expected

mi:
As expected

RangeDiff:
I am not 100% sure, but I think this is reporting in km, based on what I'm seeing in Avg Consumption and miles. When I convert these numbers from km to miles, they seem logical. 

E.g. for my last trip on the highway, Avg Consumption is reporting as 40.83 (Wh/100 miles, I think), Consumed kWh is 16.22, and miles is 39.71, but RangeDiff is 85.34. Converted from km -> miles this would be 53, which seems logical and leads to working backward to a rated usage of 0.306Wh/mi for all of my trips.

<img width="1449" alt="Screen Shot 2020-10-28 at 9 52 36 AM" src="https://user-images.githubusercontent.com/72315/97445139-51a07a80-1903-11eb-974b-dccbd6a10e9b.png">

Avg TempF:
As expected

Max mph:
As expected

Max kW:
As expected

min kW:
As expected

Avg kW:
I'm not sure what's happening here exactly, but this doesn't match Consumed kWh when I take Avg kW * Duration Min / 60. The value based on Avg kW comes out around 65-75% less than the Consumed kWh value.

Avg mph:
This appears to be showing km/h

I'd also be happy to dig around and try to fix some of these, but I'm not really clear what the best way would be to get a good dev workflow going for my setup. I'm running TeslaLogger in Docker on a Synology NAS. My main computer is a Mac, but I do have a PC as well. If you could share a few pointers on dev workflow setup for my situation, I could probably help contribute on this and other things going forward.

Great work on this! It's really very cool, and I've already found real value in being able to get a better sense of what my range will be at highway speeds by easily grabbing a chunk of my drive last night that started and ended at the same altitude and looking at my consumption.

Thanks!

**Comment by relevante** [comment]
Actually re: dev environment, maybe it's better to just keep my current install running and use a Raspberry Pi with a second install for dev. Would running two installs pointed at the same account/car cause any issues?

**Comment by bassmaster187** [comment]
Bug is fixed in next version. 

Here is a draft for a development environment for Teslalogger: https://github.com/bassmaster187/TeslaLogger/blob/master/dev-howto.md

**Comment by bassmaster187** [comment]
Please update to 1.45.8.0 and check if bug is fixed.
