### ISSUE TITLE
Teslamate Import

### ISSUE THREAD

**Issue by riesi77** [bassmaster187/TeslaLogger#405]
**Is your feature request related to a problem? Please describe.**
I'm using Teslamate and thinking of moving over to TeslaLogger. However that's not possible without loosing my logged data afaik.

**Describe the solution you'd like**
Provide an import mechanism from Teslamate

**Comment by superfloh247** [comment]
That's already "work in progress". You can support and speed up that progress if you agree to share your TM database dump. Did I forget anything @bassmaster187 ?

**Comment by riesi77** [comment]
I can share it - but I don't want to share it in public. Do you have an E-Mail Address or sth where I can send it to?

**Comment by superfloh247** [comment]
of course not public - please wait for feedback by @bassmaster187 (he's a bit busy these days)

**Comment by bassmaster187** [comment]
@riesi77 Please send me a db backup to: mail@pogea.de 
your db won't be shared to anybody. If you don't found any issus with the import tool, I can delete your backup if you want me to.

**Comment by riesi77** [comment]
Mail sent.

**Comment by bassmaster187** [comment]
Here is the Teslamate Import Tool and the manual:
https://github.com/bassmaster187/TeslaLogger/tree/master/Teslamate-Import
