### ISSUE TITLE
ScanMyTesla iOS 

### ISSUE THREAD

**Issue by florianlentz** [bassmaster187/TeslaLogger#412]
When you are ready to insert the Data from ScanMyTesla iOS App ?

**Comment by bassmaster187** [comment]
As I don't have the environment for developing iOS Apps, Amund has to do it byhimself. I have a conf call tonight with him. After that I'll keep you updated.

**Comment by bassmaster187** [comment]
In two weeks, I'll try to merge the code to iOS version and Amund will try to compile it on iOS.

**Comment by florianlentz** [comment]
Hey, how far are you here?

**Comment by Adminius** [comment]
iOS Beta version can now send data to TeslaLogger
