### ISSUE TITLE
Ability to add monthly fixed cost for charging

### ISSUE THREAD

**Issue by mhjansen79** [bassmaster187/TeslaLogger#438]
I have a subscription for my charge card for charging my tesla. It would be great if this fixed subscription could be added in the admin panel (similar to the free super charging feature) and have this fixed monthly fee spread over the cost calculation for the charge sessions of the month.

**Comment by bassmaster187** [comment]
Is your charge card for just one network, one charger or pretty much all public chargers?

**Comment by mhjansen79** [comment]
I havent yet found a network that doesnt accept my charge card.

**Comment by Adminius** [comment]
@mhjansen79 hot to spread monthly over charge session? fix percent? or do we have to count every charging session (per month) an calculate a part of fee? How is month defined? 1st until last day (e.g. 31st) or more flexible?
what is your idea for that?
How can we know, that you used this card and another (without fee)?

You see, it is complex...

**Comment by mhjansen79** [comment]
Thanks for looking into this. I understand the complexity involved. The Dusseldorf card is also no longer interesting for those outside of Germany as now there is a requirement that at least 50% of the charging sessions must take place on their network, which I'm not able to hit.

**Comment by Adminius** [comment]
Does it mean your issue is "solved"? ;)

**Comment by mhjansen79** [comment]
issue is indeed no longer relevant. Solved No ;)
