### ISSUE TITLE
Docker Update on Buster 

### ISSUE THREAD

**Issue by florianlentz** [bassmaster187/TeslaLogger#452]
Hey. 

after Update on Debian Buster i don´t came up the Docker after docker-compose build

this: 

root@teslalogger:/TeslaLogger# docker-compose build
database uses an image, skipping
grafana uses an image, skipping
Building teslalogger
Step 1/5 : FROM mono:5.20.1.34
 ---> 429edcd2234d
Step 2/5 : RUN echo "Europe/Berlin" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
 ---> Using cache
 ---> 9ac6bf21cbdc
Step 3/5 : RUN apt-get update &&   apt-get install -y --no-install-recommends git &&   apt-get install -y --no-install-recommends mariadb-client &&   apt-get clean &&   apt-get autoremove -y &&   rm -rf /var/lib/apt/lists/* &&   echo "export TERM=xterm" >> /root/.bashrc  &&   echo "DOCKER" >> /tmp/teslalogger-DOCKER
 ---> Using cache
 ---> 703b981cc253
Step 4/5 : WORKDIR /etc/teslalogger
 ---> Using cache
 ---> b937dfd6b481
Step 5/5 : CMD ["mono", "./TeslaLogger.exe"]
 ---> Using cache
 ---> da2daccd3c55
Successfully built da2daccd3c55
Successfully tagged teslalogger_teslalogger:latest
Building webserver
Step 1/2 : FROM php:7.3-apache
 ---> b04d30bf66c0
Step 2/2 : RUN apt-get update &&   apt-get install -y --no-install-recommends mariadb-client &&   apt-get clean &&   apt-get autoremove -y &&   rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 2f455dcb89db
Successfully built 2f455dcb89db
Successfully tagged teslalogger_webserver:latest

any Idea to fix it ? my Docker understanding ist Zero ;-(

**Comment by bassmaster187** [comment]
you just build the docker. I'm pretty sure you want to start it:

`docker-compose up`
