### ISSUE TITLE
"Charging History" is shortening "Minutes" (last column) to "1K" instead of precise number of minutes if more than 1000 minutes

### ISSUE THREAD

**Issue by rowich** [bassmaster187/TeslaLogger#46]
I believe changing the "type" in the JSON definition from "short" to "locale" should do it. If you charge shorter, you should not see a difference.
![Anmerkung 2019-05-20 071025](https://user-images.githubusercontent.com/49855876/57997702-6651cf80-7ace-11e9-9db2-11fe6f6c981a.png)

**Comment by bassmaster187** [comment]
https://github.com/bassmaster187/TeslaLogger/commit/a57608bf02a18ec40af20424007c8d24bd47983f
