### ISSUE TITLE
Login Error running TeslaLogger-Docker (V 1.46.0.0) on Windows

### ISSUE THREAD

**Issue by eili77** [bassmaster187/TeslaLogger#471]
** Append Logfile **
see attached log...
[docker-log 2021-02-02 - 0805.txt](https://github.com/bassmaster187/TeslaLogger/files/5909372/docker-log.2021-02-02.-.0805.txt)

**Describe the bug**
teslalogger_1  | 02.02.2021 08:19:29 : #1: Login with : 'XilX@XXliXXh' / 'xxxxxxxxxxxxx'
teslalogger_1  | 02.02.2021 08:19:30 : 02.02.2021 08:19:30 : MqttClient Version: 1.8.0.0
teslalogger_1  | 02.02.2021 08:19:30 : 02.02.2021 08:19:30 : No MQTTHost settings -> MQTT disabled!
teslalogger_1  | 02.02.2021 08:19:30 : MQTT terminated
teslalogger_1  | 02.02.2021 08:19:31 : #1: **Error**: GetTokenAsync2 HttpStatus: OK / Expecting: Redirect !!!
teslalogger_1  | 02.02.2021 08:19:31 : #1: **Error**: GetTokenAsync2 Redirect Location = null!!! Wrong credentials?
teslalogger_1  | 02.02.2021 08:19:31 : #1: **Abort**: Tesla_token == NULL
teslalogger_1  | 02.02.2021 08:19:31 : #1: *** Exit Loop !!!

** Teslalogger Type **
Docker
Did you update the Image with apt-get update & upgrade?
Yes

** Do you use Tasker or iBeacon **
No

**Comment by eili77** [comment]
Error seems to be due to 2FA (2 Factor Authentication)... disabling 2FA on TESLA account resolves issue reported.

**Comment by bassmaster187** [comment]
Update Teslalogger to 1.46.1.0 and MFA is supported!
