### ISSUE TITLE
MQTT - send actual geolocation

### ISSUE THREAD

**Issue by f1x1t1x1f** [bassmaster187/TeslaLogger#476]
I use MQTT to trigger further actions in my home automation. It would be nice to have a MQTT with the actuel geolocation name.

**Comment by bassmaster187** [comment]
To not flood OpenStreetMap / Nominatim, Teslalogger is reverse geocoding only positions after a trip is done. Is that what you're up to or do you need a geolocation name for every single point?

**Comment by f1x1t1x1f** [comment]
> To not flood OpenStreetMap / Nominatim, Teslalogger is reverse geocoding only positions after a trip is done. Is that what you're up to or do you need a geolocation name for every single point?

I was thinking on a gelocation name, when i enter and exit an geofence. But only the private gelocations.

**Comment by superfloh247** [comment]
I think we can support that, if the requirement is just to translate lat,lng to entries from geofence+geofence-private

**Comment by f1x1t1x1f** [comment]
> I think we can support that, if the requirement is just to translate lat,lng to entries from geofence+geofence-private

yes, thats what i want.

**Comment by f1x1t1x1f** [comment]
I see you closed this issue and i updated my installation. But I'm still not getting the name of the geofence over MQTT. Am I missing somethin?

**Comment by bassmaster187** [comment]
It will be in the next release. We have to test all the new features and bugfixes. Maybe next week.
