### ISSUE TITLE
Log "Wait for MFA code !!!" repeated every 10 seconds

### ISSUE THREAD

**Issue by pbertra** [bassmaster187/TeslaLogger#481]
Since last update, logs are polluted with repeating messages every 10 seconds

08.02.2021 17:32:53 : #1: Charging Complete
08.02.2021 17:32:53 : #1: change TeslaLogger state: Charge -> Start

08.02.2021 17:32:54 : #1: try to get new Token
08.02.2021 17:32:54 : #1: No Refresh Token
08.02.2021 17:32:54 : #1: Login with : 'XatXiXX.bXXtXanX@iXaXXroXX.Xom' / 'xxxxxxxxx'
08.02.2021 17:32:56 : #1: Start waiting for MFA code !!!
08.02.2021 17:33:06 : #1: Wait for MFA code !!!
08.02.2021 17:33:16 : #1: Wait for MFA code !!!
08.02.2021 17:33:23 : CopyChargePrice at '🔌 🏠 Domicile'
08.02.2021 17:33:23 : CopyChargePrice: reference charging session found for '🔌 🏠 Domicile', ID 244 - cost_per_kwh:0.2158 cost_per_session:0 cost_per_minute:0 started: 2/8/2021 4:50:54 PM
08.02.2021 17:33:26 : #1: Wait for MFA code !!!
08.02.2021 17:33:36 : #1: Wait for MFA code !!!
08.02.2021 17:33:46 : #1: Wait for MFA code !!!
08.02.2021 17:33:56 : #1: Wait for MFA code !!!
08.02.2021 17:34:06 : #1: Wait for MFA code !!!
08.02.2021 17:34:16 : #1: Wait for MFA code !!!
08.02.2021 17:34:26 : #1: Wait for MFA code !!!
08.02.2021 17:34:36 : #1: Wait for MFA code !!!
08.02.2021 17:34:46 : #1: Wait for MFA code !!!
08.02.2021 17:34:56 : #1: Wait for MFA code !!!

I use the docker version, completely upgraded today afternoon with :
docker-compose stop
git fetch
git reset --hard origin/master
git checkout origin/master -- docker-compose.yml
docker-compose build
docker-compose up -d

I upgraded because the server was not seeing the car as asleep anymore but I don't know if it's related

**Comment by bassmaster187** [comment]
go to: Settings / Credentials / Edit / Reconnect

Enter your MFA code from your authentificator app

**Comment by pbertra** [comment]
OK
Solved the issue indeed.
Will I have to redo this periodically?

**Comment by bassmaster187** [comment]
No. Teslalogger should be able to get a new access token via refresh token.
