### ISSUE TITLE
charging history wrong

### ISSUE THREAD

**Issue by mss1010** [bassmaster187/TeslaLogger#484]
Hello, the first charging sessions I recorded are looking wrong. The first one here from SOC 49 to 85 is correct. It shows 26,72 kWh charged. This was a planned charging session.

Then in the morning I manually started charging again just for 34 minutes. For this one it shows 27,03 kWh charged, which is impossible with a 4KW charger ;-) It seems that it added up the last session and shows the total of two session within the shorter one. The car was not moved between that. Also, the charging cable was not unplugged.

I am using Docker to run the logger.

![Unbenannt](https://user-images.githubusercontent.com/36116339/107410347-795fcb00-6b0d-11eb-8efa-1c9bf098d531.PNG)

[logfile.txt](https://github.com/bassmaster187/TeslaLogger/files/5953472/logfile.txt)

FYI: In the attached logfile I removed personal information like the GPS position.

**Comment by Adminius** [comment]
#377

**Comment by mss1010** [comment]
> #377

ok thanks. I posted my feedback in that issue and will close this one here.
