### ISSUE TITLE
MQTT - send actual geolocation

### ISSUE THREAD

**Issue by f1x1t1x1f** [bassmaster187/TeslaLogger#488]
I see you closed this issue and i updated my installation. But I'm still not getting the name of the geofence over MQTT. Am I missing something?

_Originally posted by @f1x1t1x1f in https://github.com/bassmaster187/TeslaLogger/issues/476#issuecomment-777334478_

**Comment by bassmaster187** [comment]
The feature is in current version. May I close the feature request?

**Comment by f1x1t1x1f** [comment]
> The feature is in current version. May I close the feature request?

yes, sure. thank you.
