### ISSUE TITLE
Add software update status to current_json.txt

### ISSUE THREAD

**Issue by RetoHB** [bassmaster187/TeslaLogger#494]
Add vehicle state -> software_update -> status to current_json.txt
I would like to display a pending software update on my dashboard.

**Comment by superfloh247** [comment]
![Bildschirmfoto 2021-02-25 um 14 29 38](https://user-images.githubusercontent.com/26180993/109160335-f2019100-7775-11eb-89e1-5386178bd056.png)

**Comment by superfloh247** [comment]
I will implement it later/soon

**Comment by RetoHB** [comment]
Today "missed" another update. When can you add this? ;-)
