### ISSUE TITLE
logging too verbose since version 1.46.2

### ISSUE THREAD

**Issue by mss1010** [bassmaster187/TeslaLogger#495]
Since version 1.46.2 the logging in nohup.out is very verbose. While driving, it creates an entry 2-3 times per second.
Does it make sense to write all this data into the logfile? It should be enough if it´s written to the database, for it´s main purpose.

While charging it creates an entry like this

> Stream Data Error: vehicle_disconnected

every 15-30 seconds.

Also here I´m not sure if this makes sense.

So, my request is, to return to the logging logic from the last version, where only relevant data and errors were logged.

**Comment by bassmaster187** [comment]
We introduced the streaming API in 1.46.2, so it creates a lot of logging. We have more than 2000km test drive it, but we want to make sure everything works fine. In Next version we will reduce the additional loggig to a minimum.

**Comment by mss1010** [comment]
Sounds good, thanks for the information.
