### ISSUE TITLE
Is it possible to integrate with a MQTT server the position of the car?

### ISSUE THREAD

**Issue by Klagio** [bassmaster187/TeslaLogger#506]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by superfloh247** [comment]
it is already in there:
"latitude":42.446133,"longitude":23.358081

**Comment by Klagio** [comment]
> it is already in there:
> "latitude":42.446133,"longitude":23.358081

thanks but where  to set MQTT server options, and which is the MQTT topic?

**Comment by Adminius** [comment]
@Klagio in german only :/ (translations are welcome)
https://teslalogger.de/Teslalogger.pdf -> 2.3 -> edit file MQTTClient.exe.config
topic: tesla

**Comment by Schimi1983** [comment]
Hi,

i rhink he mean for "every state" a seperate Topic..... Like in the screenshot..
Now the complete data is in "one line"

![image](https://user-images.githubusercontent.com/4581474/135338562-61cd76b4-4989-43f7-992b-f76ace5a5826.png)

It would be great if it could be like this :-)
