### ISSUE TITLE
no access to dashboard from teslalogger

### ISSUE THREAD

**Issue by moneymakerleo** [bassmaster187/TeslaLogger#507]
How do I get in touch with dashboard = grafana, every time I wanted to get in touch it asks for my user & password as always, for some reason suddenly I can move on, username or password is wrong write it and I have tried to put to default password as "admin" but it does not work, why can I not get in touch with grafana suddenly, maybe there is a helpful person who can help me or look at a file from me if something has gone wrong somewhere.

![2021-02-24 (1)](https://user-images.githubusercontent.com/47917191/109002878-117db880-76a7-11eb-92fa-8303e18a71d1.png)
![2021-02-24 (2)](https://user-images.githubusercontent.com/47917191/109002897-17739980-76a7-11eb-907c-8f9122dcde4c.png)

**Comment by rowich** [comment]
default userid/password for Grafana is "admin/teslalogger"

Am 24.02.2021 um 13:49 schrieb moneymakerleo:

**Comment by moneymakerleo** [comment]
yes it is true it was then when it was new, I have used a different password for almost a year now, I can not reset it now

**Comment by moneymakerleo** [comment]
sorry but i'm not proof in this

**Comment by jandmc** [comment]
maybe try:
`grafana-cli admin reset-admin-password --homepath /usr/share/grafana <your new admin password>`
or in docker setup
`docker exec -ti <your container id> grafana-cli admin reset-admin-password --homepath /usr/share/grafana <your new password>`

**Comment by moneymakerleo** [comment]
Sorry I do not quite understand; password is ok but --homepath, yes I am new here can not make it work :-(

![image](https://user-images.githubusercontent.com/47917191/109125719-aedef800-774c-11eb-8557-48054b5082aa.png)

**Comment by jandmc** [comment]
the "--hompath" ist an command line argument which is followed by the installation directory of the grafana which in this ecample is "/usr/share/grafana"  (which is default when installed on raspberry pi)

if you execute it like:
`grafana-cli admin reset-admin-password --homepath /usr/share/grafana secretPassword`
You should be able to login to grafana using user _admin_ with password _secretPassword_

**Comment by moneymakerleo** [comment]
hmmm now i get this message ????
![pi 2](https://user-images.githubusercontent.com/47917191/109156685-6d147880-7771-11eb-95c6-1453075df3be.PNG)

**Comment by moneymakerleo** [comment]
Why should it be so hard to reset password!

**Comment by rowich** [comment]
it's always a mess if you forget your one-and-only master-password. And
it's good that this is not easy.
Regarding your "access denied", I am assuming you need to prefix the
command with "sudo" (but this need to be confirmed from a linux guy)

Am 25.02.2021 um 14:07 schrieb moneymakerleo:

**Comment by moneymakerleo** [comment]
Yes definitely some mess when you forget; my problem is just not because I forgot my login / password, it would just suddenly not be known by my normal password anymore not because I forgot it, it just would not be known by it, I am very happy for your help rowich & jandmc really much but unfortunately just not good enough for me friends, I think there must be someone who knows what was going on with my grafana login because it's a little annoying :-(

**Comment by jandmc** [comment]
hey, you need to have execution permission so as mentioned before add a "sudo" before the command and enter your raspberry pi password you login to the raspberry.
`sudo grafana-cli admin reset-admin-password --homepath /usr/share/grafana secretPassword`

**Comment by moneymakerleo** [comment]
Looks like I managed to change the password, but I can not open grafana why! And my raspberry pi has started running very slowly now, it has never done that before ???

![image](https://user-images.githubusercontent.com/47917191/109325346-1b91e980-7856-11eb-8e02-eee90e2cd89c.png)

**Comment by moneymakerleo** [comment]
Is there no one at all who has an idea on how to get into my dashboard access / code denied

**Comment by bassmaster187** [comment]
are you still not able to access grafana although you reset the password? Do you get any errors?

**Comment by moneymakerleo** [comment]
I do not understand, the teslalogger itself has also started to run very slowly This error occurs when I look at the teslalogger "Warning: session_start (): Cannot send session cache limiter - headers already sent (output started at / var / www / html / admin /index.php:1) in /var/www/html/admin/index.php on line 5 "..Grafana still says
   "invalid username or password" I give up soon- :(

**Comment by moneymakerleo** [comment]
Can I start over with new installation, but with all the old data from tesla!

**Comment by bassmaster187** [comment]
send me an email please: mail@pogea.de

**Comment by moneymakerleo** [comment]
Thank you so much for the very nice help Christian, everything is running now, nice.

**Comment by bassmaster187** [comment]
you're welcome

**Comment by 8514011** [comment]
> Looks like I managed to change the password, but I can not open grafana why! And my raspberry pi has started running very slowly now, it has never done that before ???
> 
> ![image](https://user-images.githubusercontent.com/47917191/109325346-1b91e980-7856-11eb-8e02-eee90e2cd89c.png)
I also encountered the same problem and was unable to log in to Grafana. How did you solve it?
