### ISSUE TITLE
Updated but receive error DBCONNECTION Unable to connect to any of the specified MySQL hosts.

### ISSUE THREAD

**Issue by Klagio** [bassmaster187/TeslaLogger#515]
27.02.2021 18:50:25 : TeslaLogger Version: 1.45.17.0
27.02.2021 18:50:25 : Teslalogger Online Version: 1.46.4.0
27.02.2021 18:50:25 : Logfile Version: 1.0.10.0
27.02.2021 18:50:25 : SRTM Version: 0.0.3.0
27.02.2021 18:50:25 : Docker: YES!
27.02.2021 18:50:25 : Current Culture: en-US
27.02.2021 18:50:25 : Mono Runtime: 5.20.1.34 (tarball Tue Jul 16 22:52:22 UTC 2019)
27.02.2021 18:50:25 : Grafana Version: 7.2.0
27.02.2021 18:50:25 : OS Version: Unix 5.4.0.66
27.02.2021 18:50:25 : Update Settings: all
27.02.2021 18:50:25 : DBConnectionstring: Server=127.0.0.1;Database=teslalogger;Uid=root;Password=teslalogger;CharSet=utf8mb4;
27.02.2021 18:50:25 : KeepOnlineMinAfterUsage: 15
27.02.2021 18:50:25 : SuspendAPIMinutes: 21
27.02.2021 18:50:25 : SleepPositions: 5000
27.02.2021 18:50:25 : UseScanMyTesla: False
27.02.2021 18:50:26 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
27.02.2021 18:50:41 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.
27.02.2021 18:50:55 : DBCONNECTION Unable to connect to any of the specified MySQL hosts.

**Comment by Klagio** [comment]
all dashboard disappeared ....

**Comment by bassmaster187** [comment]
Your Logfile shows it is a docker installation, but the DBConnectionstring might be wrong as MariaDB is on a different Container. 

Teslalogger.exe.config should look like:

```
<setting name="DBConnectionstring" serializeAs="String">
                <value>Server=database;Database=teslalogger;Uid=root;Password=teslalogger;CharSet=utf8;</value>
            </setting>
```

**Comment by Klagio** [comment]
will check, but have not done anything, and before was working

**Comment by bassmaster187** [comment]
If your problem still persist, please reopen the issue.
