### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by RichieB2B** [bassmaster187/TeslaLogger#52]
This issue is mostly a reminder for myself to create a docker image for TeslaLogger. I can probably use the Raspberry Pi image as a base for this.

**Comment by bassmaster187** [comment]
I'm actually doing a Dockerfile

**Comment by RichieB2B** [comment]
Great! I started looking into this, but didn't produce anything working yet.
We'll probably need a `docker-compose.yml` with Grafana and MariaDB in separate images.

**Comment by bassmaster187** [comment]
https://github.com/bassmaster187/TeslaLogger/blob/master/docker-compose.yml
https://github.com/bassmaster187/TeslaLogger/blob/master/Dockerfile

TODO:
- create Database on first start.
- update Dashboards in Grafana on Startup

**Comment by tabsl** [comment]
work in progress, see docker branch: https://github.com/bassmaster187/TeslaLogger/tree/docker

**Comment by ghostreader86** [comment]
I just searched [hub.docker.com](hub.docker.com) and found [TeslaMate](https://hub.docker.com/r/teslamate/teslamate). On the [GitHub Project Page](https://github.com/adriankumpf/teslamate) he is saying "TeslaLogger was a big inspiration especially during early development. Thanks!" I wonder if we can benefit from it.

**Comment by spacecosmos** [comment]
> I just searched [hub.docker.com](hub.docker.com) and found [TeslaMate](https://hub.docker.com/r/teslamate/teslamate). On the [GitHub Project Page](https://github.com/adriankumpf/teslamate) he is saying "TeslaLogger was a big inspiration especially during early development. Thanks!" I wonder if we can benefit from it.

I actually made a step-by-step guide on how to get the [TeslaMate](https://github.com/adriankumpf/teslamate) Docker up and running on [DigitalOcean](https://m.do.co/c/98c628ea4a8e). Not sure if you can use any of it, but please do if you want:

https://satheesh.net/2019/09/28/teslamate-digitalocean-docker-step-by-step-installation-guide/

PS! I just came over TeslaMate before knowing about TeslaLogger, so I just ended up using the former. Great work both of you! :) Cheers!
