### ISSUE TITLE
image

### ISSUE THREAD

**Issue by moneymakerleo** [bassmaster187/TeslaLogger#525]
How do I open so I can upload an image here, (\\ raspberry \ teslalogger-web \ admin \ wallpapers \ 1 \) when I try it is locked and I am not allowed to send the file / image

**Comment by Adminius** [comment]
Windows Explorer
![image](https://user-images.githubusercontent.com/17052262/110632531-05feb700-81a8-11eb-92d2-a5746d9b2028.png)

Login: pi
Password: teslalogger

**Comment by moneymakerleo** [comment]
so far so good when I then find a file that says the "access to destination directory was denied"

**Comment by Adminius** [comment]
@bassmaster187 chmod?

**Comment by moneymakerleo** [comment]
Yes sorry; beginner here. but how do i use exactly chmod to move a file permission.

**Comment by bassmaster187** [comment]
I'll try to change permissions in next version

**Comment by moneymakerleo** [comment]
nice.
