### ISSUE TITLE
Backup mit flexiblen DB-Angaben

### ISSUE THREAD

**Issue by DrMichael** [bassmaster187/TeslaLogger#53]
Hallo Christian,

könnte man in der admin/backup.php noch einbauen, dass er backup.py ausführt, wenn es existiert? (Kann leider kein php...)

Ich habe das mal geschrieben, um eben mit eventuell anderen Datenbankparametern zu arbeiten. Das backup.py liest die aus der TeslaLogger.exe.config.

Michael

PS: oder statt backup.sh direkt backup.py nehmen...

[backup.zip](https://github.com/bassmaster187/TeslaLogger/files/3413755/backup.zip)

**Comment by DrMichael** [comment]
Ah, hier nochmal eine backup.py. Die benutzt jetzt, wenn kein (vollständiger) DBConnectionstring gesetzt ist, die Standardwerte Server=localhost;Database=teslalogger;Uid=root;Password=teslalogger;

[backup.zip](https://github.com/bassmaster187/TeslaLogger/files/3416381/backup.zip)

**Comment by Adminius** [comment]
@DrMichael /etc/teslalogger/my-backup.sh
https://github.com/bassmaster187/TeslaLogger/blob/master/TeslaLogger/bin/backup.sh
@bassmaster187 close?

**Comment by DrMichael** [comment]
Ui, that one is old...:-)
