### ISSUE TITLE
sleep/wake up

### ISSUE THREAD

**Issue by moneymakerleo** [bassmaster187/TeslaLogger#533]
My Tesla model 3 from 28/6/2019 is woken up by something and I do not know what it is and it is not because I look at my app all the time, of course not but I can see it on my Tesla logger, just thinking once it has fallen asleep, why does it wake up without me doing anything active, it is completely spontaneous, it is be my network (wireless) there is well do something do not mean my bluetooth on the phone, the car keeps very close to the house .
When I see in my tesla logger that the car is awake I have tried to open my tesla app and there is contact immediately, whereupon I open the tesla app and the car sleeps, well then it takes some time before the car wakes up which is completely normal.
These points with red ring are when the car has slept and being awakened it without red ring is normal driving.
Some good ideas what happens would be nice- :)

![Skærmbillede 2021-03-17 103606](https://user-images.githubusercontent.com/47917191/111447657-ef0f1600-870d-11eb-9403-a62c16b47a83.png)

**Comment by bassmaster187** [comment]
there are many reasons and all are not Teslalogger related:
- recharging V12 Batterie
- receiving an update
- sending data to Tesla like Autopilot fail
- a bug (we had that last winter)
- running colant pump
- a widget, Tesla App, any other Application with Teslalogger credentials
- any other reason only tesla and Elon might know or not

if a car fall into sleep, Teslalogger will never ever wake it up.

**Comment by moneymakerleo** [comment]
I completely agree that tesla logger does not wake up the car once it is
asleep, it was not what I think, it was more what is going on, which is why
I have made a new password at tesla several times, just for the same reason
a widget, Tesla App, any other Application.
It is obviously very normal so would also just hear if there are more of
the same experience
"any other reason only tesla and Elon might know or not" yes that's right-
:)
The one with the 12 volt battery, of course.
So you mean if nothing else starts it from the outside then only tesla will
do it.
It's good to keep up with teslalogger, good tool.
  thanks for the quick reply.
ᐧ

Den ons. 17. mar. 2021 kl. 13.01 skrev Christian P. <
***@***.***>:

**Comment by superfloh247** [comment]
![1894723](https://user-images.githubusercontent.com/26180993/111467439-b9c1f280-8724-11eb-8db3-e2c19f087a8a.jpg)

**Comment by bassmaster187** [comment]
ohh, what i forgot: if you carry your keyfob in your pocket and your car might see it, sometimes it will wake up your car to be able to drive your car without waiting for the mcu to boot. So my suggestion: drop your keyfob as far away from your car as possible when you get home. Such informations you're getting after collecting data over years...

**Comment by moneymakerleo** [comment]
point taken, keyfob I had for tesla s, but now I have a Model 3 and no
keyfob, so it can not be because keyfob, right now experiencing something
crazy Elon sends out to most model 3 right now summon on trial to d
31/3/2021 in these hours here in denmark at least even if you have not
purchased it
ᐧ

Den ons. 17. mar. 2021 kl. 16.07 skrev Christian P. <
***@***.***>:

**Comment by bassmaster187** [comment]
As I don't own a Model 3, I don't know if your smarphone does the same if you have bluetooth turned on. You have to try id by yourself.

**Comment by moneymakerleo** [comment]
Yes.

ons. 17. mar. 2021 17.59 skrev Christian P. ***@***.***>:
