### ISSUE TITLE
geofence UI needs new checkbox: SetCargeLimit on arrival - and new radio group: (do not) combine charging sessions

### ISSUE THREAD

**Issue by superfloh247** [bassmaster187/TeslaLogger#535]
please add new checkbox to geofence UI

![Bildschirmfoto 2021-03-18 um 10 08 33](https://user-images.githubusercontent.com/26180993/111601129-5db5a780-87d2-11eb-9925-41e373fc75bd.png)

Effect: appends :A to +scl

Examples:
unchecked: +scl:80
checked: +scl:80:A

new radio boxes
( ) global default from settings --> no special flag
( ) combine charging sessions --> +ccs
( ) do not combine charging sessions --> +dnc

**Comment by superfloh247** [comment]
set on arrival is still missing

do not combine charging sessions is implemented

combine charging sessions is not implemented (needed to locally overwrite global setting)

**Comment by Adminius** [comment]
@superfloh247 done. close?
