### ISSUE TITLE
2nd car added to account, no prompt for MFA

### ISSUE THREAD

**Issue by IMgoRt** [bassmaster187/TeslaLogger#539]
Hi,
I've added a second car to my tesla account, but don't get prompted to enter MFA token anywhere (credentials/edit)

What PD do you require?

Thanks

**Comment by bassmaster187** [comment]
I tried it right now with a 2nd car and it asked me for a MFA token. Could you please send me your logfile.

**Comment by IMgoRt** [comment]
> I tried it right now with a 2nd car and it asked me for a MFA token. Could you please send me your logfile.

Anything specific you want me to do before sending it and send where to?

**Comment by IMgoRt** [comment]
Just updated to 1.47.2, now seeing "waiting for MFA" in the log not previously there) but no prompt for a code.

To clarify - I had a P100D on my account, which I've now sold and replaced with a P3D, I still see the P100D there but offline, the P3D appears as "Car 2" - manually added by me.  In TM the car just appeared

**Comment by bassmaster187** [comment]
please go to settings/credentials/edit 2nd car
and click on reconnect. It should prompt you for the mfa token.

**Comment by IMgoRt** [comment]
> please go to settings/credentials/edit 2nd car
> and click on reconnect. It should prompt you for the mfa token.

I get "Credentials Info:" at the top of the screen and "OK" at the bottom, no data input fields

**Comment by bassmaster187** [comment]
it should come after a couple of seconds:

![image](https://user-images.githubusercontent.com/6816385/111829248-bbd6ad80-88ec-11eb-9052-b661d42c5b38.png)

Otherwise please send me your logfile

**Comment by IMgoRt** [comment]
> it should come after a couple of seconds:
> 
> ![image](https://user-images.githubusercontent.com/6816385/111829248-bbd6ad80-88ec-11eb-9052-b661d42c5b38.png)
> 
> Otherwise please send me your logfile

Yes, 'd waited a few minutes before reporting, how do I send you the log?

Here's an extract:
20.03.2021 08:24:36 : #1: Wait for MFA code !!!
20.03.2021 08:24:46 : #1: Wait for MFA code !!!
20.03.2021 08:24:56 : #1: Wait for MFA code !!!
20.03.2021 08:25:06 : #1: Wait for MFA code !!!
20.03.2021 08:25:10 : Wakeup file 1 created!
20.03.2021 08:25:16 : #1: Wait for MFA code !!!
20.03.2021 08:25:26 : #1: Wait for MFA code !!!
20.03.2021 08:25:36 : #1: Wait for MFA code !!!
20.03.2021 08:25:46 : #1: Wait for MFA code !!!
20.03.2021 08:25:46 : SetPassword
20.03.2021 08:25:46 : reconnect Car #2
20.03.2021 08:25:48 : Localpath: /passwortinfo
System.NullReferenceException: Object reference not set to an instance of an object
at TeslaLogger.WebServer.passwortinfo (System.Net.HttpListenerRequest request, System.Net.HttpListenerResponse response) [0x0014e] in :0
at TeslaLogger.WebServer.OnContext (System.Object o) [0x0023d] in :0
20.03.2021 08:25:56 : #1: Wait for MFA code !!!
20.03.2021 08:26:06 : #1: Wait for MFA code !!!
20.03.2021 08:26:16 : #1: Wait for MFA code !!!
20.03.2021 08:26:26 : #1: Wait for MFA code !!!
20.03.2021 08:26:36 : #1: Wait for MFA code !!!
20.03.2021 08:26:46 : #1: Wait for MFA code !!!
20.03.2021 08:26:49 : Localpath: /passwortinfo
System.NullReferenceException: Object reference not set to an instance of an object
at TeslaLogger.WebServer.passwortinfo (System.Net.HttpListenerRequest request, System.Net.HttpListenerResponse response) [0x0014e] in :0
at TeslaLogger.WebServer.OnContext (System.Object o) [0x0023d] in :0
20.03.2021 08:26:56 : #1: Wait for MFA code !!!
20.03.2021 08:27:06 : #1: Wait for MFA code !!!
20.03.2021 08:27:16 : #1: Wait for MFA code !!!
20.03.2021 08:27:26 : #1: Wait for MFA code !!!
20.03.2021 08:27:36 : #1: Wait for MFA code !!!
20.03.2021 08:27:46 : #1: Wait for MFA code !!!
20.03.2021 08:27:51 : Localpath: /passwortinfo
System.NullReferenceException: Object reference not set to an instance of an object
at TeslaLogger.WebServer.passwortinfo (System.Net.HttpListenerRequest request, System.Net.HttpListenerResponse response) [0x0014e] in :0
at TeslaLogger.WebServer.OnContext (System.Object o) [0x0023d] in :0
20.03.2021 08:27:56 : #1: Wait for MFA code !!!
20.03.2021 08:28:06 : #1: Wait for MFA code !!!

**Comment by IMgoRt** [comment]
Now prompted for MFA on 1.47.3.0
Thanks

**Comment by bassmaster187** [comment]
Could you please post the logfile before and after the prompt. 
The Exception is gone?

**Comment by IMgoRt** [comment]
> Could you please post the logfile before and after the prompt.
> The Exception is gone?

No more exceptions:

25.03.2021 07:20:01 : Housekeeping: delete database.mothership chunk 889001
25.03.2021 07:20:02 : Housekeeping: delete database.mothership chunk 890001
25.03.2021 07:20:03 : Housekeeping: database.mothership older than 14 days count: 188
25.03.2021 07:20:03 : RunHousekeepingInBackground finished, took 3556.53ms
25.03.2021 07:20:09 : #2: Wait for MFA code !!!
25.03.2021 07:20:19 : #2: Wait for MFA code !!!
25.03.2021 07:20:29 : #2: Wait for MFA code !!!
25.03.2021 07:20:39 : #2: Wait for MFA code !!!
25.03.2021 07:20:49 : #2: Wait for MFA code !!!
25.03.2021 07:20:59 : #2: Wait for MFA code !!!
25.03.2021 07:21:05 : #2: MFA Code: 468831
25.03.2021 07:21:05 : #2: transaction_id: 4ZRESB22
25.03.2021 07:21:05 : #2: MFA1 Result: {
"data": [
{
"dispatchRequired": false,
"id": "089885e1-a7dd-49cc-8f49-e158a8be9f1d",
"name": "1+8",
"factorType": "token:software",
"factorProvider": "TESLA",
"securityLevel": 1,
"activatedAt": "2021-01-31T08:37:19.000Z",
"updatedAt": "2021-01-31T08:38:27.000Z"
}
]
}
25.03.2021 07:21:07 : #2: Code: ebe5f7802e27d0126194338fc8cec056808fab033664435e7d5a96dbbec7
25.03.2021 07:21:07 : #2: UpdateRefreshToken
25.03.2021 07:21:07 : #2: UpdateRefreshToken OK: 1
25.03.2021 07:21:09 : #2: HttpStatus: OK
25.03.2021 07:21:09 : #2: UpdateTeslaToken
25.03.2021 07:21:09 : #2: update tesla_token OK: 1
25.03.2021 07:21:09 : #2: TOKEN: XtsX2XXadXX2X7dX86X3XXc5XX6XfcXf8XeXX3bXXaXf1X11X4XX08XX2X0bX68XeXX7
25.03.2021 07:21:10 : #2: display_name: goRt
25.03.2021 07:21:10 : #2: vin: 5YJ3F7EC1LFXXXXXX
25.03.2021 07:21:10 : #2: WriteCarsettings -> VIN
25.03.2021 07:21:10 : #2: UpdateTeslaToken
25.03.2021 07:21:10 : #2: update tesla_token OK: 1
25.03.2021 07:21:10 : #2: id: X05X8XX48XX5
25.03.2021 07:21:10 : #2: vehicle_id: X21X6XX16X
25.03.2021 07:21:10 : #2: WriteCarsettings -> TaskerToken
25.03.2021 07:21:10 : #2: UpdateTeslaToken
25.03.2021 07:21:10 : #2: update tesla_token OK: 1
25.03.2021 07:21:10 : #2: CheckUseTaskerToken
25.03.2021 07:21:11 : #2: LastTaskerToken not found - Stop using fast TaskerToken request! Reply: not found
25.03.2021 07:21:11 : #2: Tasker Config:
Server Port: https://teslalogger.de
Path: wakeup.php
Attribute: t=313cde94
25.03.2021 07:21:11 : #2: Start ScanMyTesla Thread!
25.03.2021 07:21:11 : #2: Streamingtoken: X86XeXX67XX7X93X
25.03.2021 07:21:11 : #2: Insert first Pos
25.03.2021 07:21:12 : #2: Result.Statuscode: 408 (RequestTimeout) cmd: drive_state
25.03.2021 08:21:24 : Wakeup file 1 created!
25.03.2021 07:21:42 : #2: IsDriving = NULL!

25.03.2021 07:21:52 : #2: Country Code:
25.03.2021 07:21:52 : #2: Voltage at 50% SOC:0V Date:1/1/0001 12:00:00 AM

**Comment by bassmaster187** [comment]
Perfect. Thank you
