### ISSUE TITLE
Authorisation für admin

### ISSUE THREAD

**Issue by DrMichael** [bassmaster187/TeslaLogger#54]
Es wäre vielleicht gut noch eine Datei .htaccess in admin anzulegen mit folgendem Inhalt:

AuthType Basic
AuthName "Bitte melden Sie sich an"
AuthUserFile /var/www/html/admin/.htpasswd
require valid-user

Und dann mit htpasswd einen Benutzer mit Passwort einzurichten.

Dann kann nur dieser Benutzer auch auf die Seite zugreifen.

Michael

**Comment by tabsl** [comment]
https://github.com/bassmaster187/TeslaLogger/pull/65

**Comment by endurance1968** [comment]
Oder zumindest Dinge die man permanent braucht von Dingen wie AccountDaten zu trennen. Aktuell ist entweder alles oder nichts extern erreichbar und VPN möchte ich nicht auf allen meinen Geräten einrichten somit fällt die Option weg.

**Comment by Adminius** [comment]
Version 1.48.1
Admin Panel can now be proteced by password. Check menu/settings/Teslalogger Adminpanel credentials

https://github.com/bassmaster187/TeslaLogger/blob/master/TeslaLogger/bin/changelog.md#version-1481

@bassmaster187 close?
