### ISSUE TITLE
Reboots...

### ISSUE THREAD

**Issue by DrMichael** [bassmaster187/TeslaLogger#55]
Hallo Christian,

wenn man den TeslaLogger auf einem Server laufen lässt, auf dem auch noch andere Dienste laufen, ist es nicht ganz so ideal, wenn ein Reboot gemacht wird. Klar, auf einem dedizierten Raspi spielt das keine Rolle.

Aber ein vollständiger Reboot wäre doch wohl auch nicht notwendig, oder? Neustarten, des TeslaLoggers und ggflls. Grafana müsste doch reichen?

Grafana-Neustart ist ja kein Problem. Beim TeslaLogger bin ich mir nicht so sicher. Unter Unix würde man das sinnigerweise mit einem Signal machen, SIGHUP z.B. Keine Ahnung, ob das mit mono und C# funktioniert.

Kann man alternativ nicht ein Script "restart.sh" aufrufen, falls das existiert? Oder ein restart.sh mit /sbin/reboot haben, aber wenn restart-private.sh existiert, wird dieses aufgerufen. (Das wäre so ähnlich wie mit geofence...

Michael

**Comment by Adminius** [comment]
Oder Docker nutzen...
