### ISSUE TITLE
memory leak in TL 1.47.5.0

### ISSUE THREAD

**Issue by superfloh247** [bassmaster187/TeslaLogger#551]
03.04.2021 20:00:16 : TeslaLogger process statistics
WorkingSet64:            89059328
PeakWorkingSet64:        96555008
PrivateMemorySize64:     97837056
VirtualMemorySize64:    148824064
HandleCount:                    0
StartTime: 4/3/2021 7:52:26 PM
03.04.2021 20:00:18 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:00:17
03.04.2021 20:00:49 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:00:41
03.04.2021 20:01:14 : #1: Waiting for car to go to sleep 3
03.04.2021 20:01:37 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:01:35
03.04.2021 20:02:14 : #1: Waiting for car to go to sleep 4
03.04.2021 20:02:34 : #1: Stream: Timeout
03.04.2021 20:02:56 : #1: Stream: Timeout
03.04.2021 20:03:14 : #1: Waiting for car to go to sleep 5
03.04.2021 20:03:17 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:03:16
03.04.2021 20:03:27 : #1: Stream Data Error: vehicle_disconnected 10
03.04.2021 20:04:10 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:04:09
03.04.2021 20:04:15 : #1: Waiting for car to go to sleep 6
03.04.2021 20:05:11 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:05:05
03.04.2021 20:05:15 : #1: Waiting for car to go to sleep 7
03.04.2021 20:05:57 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:05:55
03.04.2021 20:06:15 : #1: Waiting for car to go to sleep 8
03.04.2021 20:06:35 : #1: Stream: Timeout
03.04.2021 20:06:50 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:06:48
03.04.2021 20:07:15 : #1: Waiting for car to go to sleep 9
03.04.2021 20:07:47 : #1: Stream: Timeout
03.04.2021 20:08:08 : #1: Stream: Timeout
03.04.2021 20:08:15 : #1: Waiting for car to go to sleep 10
03.04.2021 20:08:31 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:08:27
03.04.2021 20:09:06 : #1: Stream Data Error: vehicle_disconnected 20
03.04.2021 20:09:15 : #1: Waiting for car to go to sleep 11
03.04.2021 20:09:18 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:09:17
03.04.2021 20:09:49 : #1: Stream: Timeout
03.04.2021 20:10:05 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:10:05
03.04.2021 20:10:16 : #1: Waiting for car to go to sleep 12
03.04.2021 20:11:03 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:10:55
03.04.2021 20:11:16 : #1: Waiting for car to go to sleep 13
03.04.2021 20:11:54 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:11:53
03.04.2021 20:12:16 : #1: Waiting for car to go to sleep 14
03.04.2021 20:12:32 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:12:27
03.04.2021 20:13:04 : #1: Stream: Timeout
03.04.2021 20:13:16 : #1: Waiting for car to go to sleep 15
03.04.2021 20:13:25 : #1: Stream: Timeout
03.04.2021 20:13:46 : #1: Stream: Timeout
03.04.2021 20:14:03 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:14:00
03.04.2021 20:14:16 : #1: Waiting for car to go to sleep 16
03.04.2021 20:14:47 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:14:46
03.04.2021 20:14:57 : #1: Stream Data Error: vehicle_disconnected 30
03.04.2021 20:15:16 : #1: Waiting for car to go to sleep 17
03.04.2021 20:15:41 : #1: Stream: Timeout
03.04.2021 20:15:57 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:15:55
03.04.2021 20:16:07 : #1: Stream: Timeout
03.04.2021 20:16:16 : #1: Waiting for car to go to sleep 18
03.04.2021 20:16:53 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:16:53
03.04.2021 20:17:16 : #1: Waiting for car to go to sleep 19
03.04.2021 20:17:26 : #1: Stream: Timeout
03.04.2021 20:17:41 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:17:39
03.04.2021 20:18:12 : #1: Stream: Timeout
03.04.2021 20:18:16 : #1: Waiting for car to go to sleep 20
03.04.2021 20:18:34 : #1: Stream: Timeout
03.04.2021 20:18:49 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:18:47
03.04.2021 20:19:16 : #1: Waiting for car to go to sleep 21
03.04.2021 20:19:36 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:19:34
03.04.2021 20:20:16 : #1: Waiting for car to go to sleep 22
03.04.2021 20:20:21 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:20:20
03.04.2021 20:20:54 : #1: Stream Data Error: vehicle_disconnected 40
03.04.2021 20:21:12 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:21:06
03.04.2021 20:21:16 : #1: Waiting for car to go to sleep 23
03.04.2021 20:22:07 : #1: Stream: Timeout
03.04.2021 20:22:17 : #1: Waiting for car to go to sleep 24
03.04.2021 20:22:30 : #1: Stream: Timeout
03.04.2021 20:22:47 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:22:41
03.04.2021 20:23:17 : #1: Waiting for car to go to sleep 25
03.04.2021 20:23:20 : #1: Stream: Timeout
03.04.2021 20:23:41 : #1: Stream: Timeout
03.04.2021 20:23:55 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:23:52
03.04.2021 20:24:17 : #1: Waiting for car to go to sleep 26
03.04.2021 20:24:47 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:24:40
03.04.2021 20:25:17 : #1: Waiting for car to go to sleep 27
03.04.2021 20:25:25 : #1: Stream: Timeout
03.04.2021 20:25:45 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:25:37
03.04.2021 20:26:17 : #1: Waiting for car to go to sleep 28
03.04.2021 20:26:31 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:26:30
03.04.2021 20:27:04 : #1: Stream Data Error: vehicle_disconnected 50
03.04.2021 20:27:17 : #1: Waiting for car to go to sleep 29
03.04.2021 20:27:17 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:27:16
03.04.2021 20:28:12 : #1: Stream: Timeout
03.04.2021 20:28:17 : #1: Restart communication with Tesla Server! 2
03.04.2021 20:28:22 : #1: ScanMyTesla FastMode: False
03.04.2021 20:28:22 : DEBUG : FindOpenChargingStates: SQL

SELECT
 id
FROM
 chargingstate
WHERE
 CarID=1
 AND EndDate IS NULL ORDER BY StartDate ASC (C:\dev\TeslaLogger\TeslaLogger\DBHelper.cs:1422)
03.04.2021 20:28:22 : DEBUG : CloseChargingStates took 186.76ms (C:\dev\TeslaLogger\TeslaLogger\DBHelper.cs:840)
03.04.2021 20:28:22 : Distance: 34.8337920381218 - Radius: 95 - 🏠 E22
03.04.2021 20:28:22 : Reverse geocoding by Geofence
03.04.2021 20:28:23 : #1: change TeslaLogger state: Start -> Online
03.04.2021 20:28:33 : #1: Result.Statuscode: 408 (RequestTimeout) cmd: vehicle_state
03.04.2021 20:28:33 : #1: Result.Statuscode: 408 (RequestTimeout) cmd: drive_state
03.04.2021 20:28:53 : DEBUG : SuC: <Berlin, Germany - EUREF-Campus> <11> <12> (C:\dev\TeslaLogger\TeslaLogger\NearbySuCService.cs:172)
03.04.2021 20:28:53 : DEBUG : SuC: <Beelitz, Germany> <13> <14> (C:\dev\TeslaLogger\TeslaLogger\NearbySuCService.cs:172)
03.04.2021 20:28:53 : DEBUG : SuC: <Herzsprung, Germany> <9> <10> (C:\dev\TeslaLogger\TeslaLogger\NearbySuCService.cs:172)
03.04.2021 20:28:53 : DEBUG : SuC: <Uckerfelde, Germany> <4> <4> (C:\dev\TeslaLogger\TeslaLogger\NearbySuCService.cs:172)
03.04.2021 20:28:53 : DEBUG : ShareSuc: 
Insert superchargerstate: Berlin, Germany - EUREF-Campus Available: 11
Insert superchargerstate: Beelitz, Germany Available: 13
Insert superchargerstate: Herzsprung, Germany Available: 9
already have it: Uckerfelde, Germany 
 (C:\dev\TeslaLogger\TeslaLogger\NearbySuCService.cs:140)
03.04.2021 20:29:03 : #1: IsDriving = NULL!
03.04.2021 20:31:36 : #1: GetOutsideTempAsync: NULL
03.04.2021 20:33:24 : #1: change TeslaLogger state: Online -> Start
03.04.2021 20:33:25 : #1: STOP communication with Tesla Server to enter sleep Mode! https://teslalogger.de/faq-1.php
03.04.2021 20:33:26 : #1: Waiting for car to go to sleep 0
03.04.2021 20:33:37 : #1: Stream: Timeout
03.04.2021 20:33:50 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:33:49
03.04.2021 20:34:26 : #1: Waiting for car to go to sleep 1
03.04.2021 20:34:36 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:34:35
03.04.2021 20:35:20 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:35:19
03.04.2021 20:35:26 : #1: Waiting for car to go to sleep 2
03.04.2021 20:36:07 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:36:06
03.04.2021 20:36:26 : #1: Waiting for car to go to sleep 3
03.04.2021 20:36:39 : #1: Stream Data Error: vehicle_disconnected 60
03.04.2021 20:36:51 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:36:50
03.04.2021 20:37:23 : #1: Stream: Timeout
03.04.2021 20:37:26 : #1: Waiting for car to go to sleep 4
03.04.2021 20:37:44 : #1: Stream: Timeout
03.04.2021 20:38:05 : #1: Stream: Timeout
03.04.2021 20:38:26 : #1: Waiting for car to go to sleep 5
03.04.2021 20:38:26 : #1: Stream: Timeout
03.04.2021 20:38:41 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:38:38
03.04.2021 20:39:27 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:39:26
03.04.2021 20:39:27 : #1: Waiting for car to go to sleep 6
03.04.2021 20:40:17 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:40:16
03.04.2021 20:40:27 : #1: Waiting for car to go to sleep 7
03.04.2021 20:41:13 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:41:06
03.04.2021 20:41:27 : #1: Waiting for car to go to sleep 8
03.04.2021 20:42:00 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:41:58
03.04.2021 20:42:22 : #1: Stream Data Error: vehicle_disconnected 70
03.04.2021 20:42:27 : #1: Waiting for car to go to sleep 9
03.04.2021 20:42:34 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:42:33
03.04.2021 20:43:21 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:43:19
03.04.2021 20:43:27 : #1: Waiting for car to go to sleep 10
03.04.2021 20:44:10 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:44:09
03.04.2021 20:44:27 : #1: Waiting for car to go to sleep 11
03.04.2021 20:45:04 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:44:59
03.04.2021 20:45:27 : #1: Waiting for car to go to sleep 12
03.04.2021 20:45:50 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:45:49
03.04.2021 20:46:23 : #1: Stream Data Error: vehicle_disconnected 80
03.04.2021 20:46:27 : #1: Waiting for car to go to sleep 13
03.04.2021 20:46:36 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:46:35
03.04.2021 20:47:22 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:47:21
03.04.2021 20:47:27 : #1: Waiting for car to go to sleep 14
03.04.2021 20:48:06 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:48:05
03.04.2021 20:48:27 : #1: Waiting for car to go to sleep 15
03.04.2021 20:49:02 : #1: Stream: Timeout
03.04.2021 20:49:23 : #1: Stream: Timeout
03.04.2021 20:49:27 : #1: Waiting for car to go to sleep 16
03.04.2021 20:49:44 : #1: Stream: Timeout
03.04.2021 20:49:59 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:49:59
03.04.2021 20:50:27 : #1: Waiting for car to go to sleep 17
03.04.2021 20:50:50 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:50:50
03.04.2021 20:51:23 : #1: Stream Data Error: vehicle_disconnected 90
03.04.2021 20:51:28 : #1: Waiting for car to go to sleep 18
03.04.2021 20:51:36 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:51:35
03.04.2021 20:52:23 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:52:21
03.04.2021 20:52:28 : #1: Waiting for car to go to sleep 19
03.04.2021 20:53:14 : #1: shift_state:  Power: 0 Datetime: 03.04.2021 20:53:08
03.04.2021 20:53:28 : #1: Waiting for car to go to sleep 20
03.04.2021 20:53:45 : #1: Stream: Timeout
03.04.2021 20:54:07 : #1: Stream: Timeout
03.04.2021 20:54:28 : #1: Waiting for car to go to sleep 21
03.04.2021 20:54:28 : #1: Stream: Timeout
03.04.2021 20:54:49 : #1: Stream: Timeout
03.04.2021 20:55:10 : #1: Stream: Timeout
03.04.2021 20:55:28 : #1: Waiting for car to go to sleep 22
03.04.2021 20:55:32 : #1: Stream: Timeout
03.04.2021 20:56:28 : #1: Waiting for car to go to sleep 23
03.04.2021 20:56:58 : #1: Stream: Timeout
03.04.2021 20:57:19 : #1: Stream: Timeout
03.04.2021 20:57:28 : #1: Waiting for car to go to sleep 24
03.04.2021 20:57:40 : #1: Stream: Timeout
03.04.2021 20:58:01 : #1: Stream: Timeout
03.04.2021 20:58:24 : #1: Stream: Timeout
03.04.2021 20:58:28 : #1: Waiting for car to go to sleep 25
03.04.2021 20:58:45 : #1: Stream: Timeout
03.04.2021 20:59:06 : #1: Stream: Timeout
03.04.2021 20:59:27 : #1: Stream: Timeout
03.04.2021 20:59:28 : #1: Waiting for car to go to sleep 26
03.04.2021 20:59:49 : #1: Stream: Timeout
03.04.2021 21:00:10 : #1: Stream: Timeout
03.04.2021 21:00:16 : TeslaLogger process statistics
WorkingSet64:            98013184
PeakWorkingSet64:       114556928
PrivateMemorySize64:    107409408
VirtualMemorySize64:    159211520
HandleCount:                    0
StartTime: 4/3/2021 7:52:26 PM

**Comment by pbertra** [comment]
04.04.2021 18:00:26 : TeslaLogger process statistics
WorkingSet64: 1219424256
PeakWorkingSet64: 1219424256
PrivateMemorySize64: 1535143936
VirtualMemorySize64: 1955995648
HandleCount: 0
StartTime: 4/3/2021 4:06:15 PM

I confirm the bug!
Mono was taking all my VM's memory, making all other processes starve.

**Comment by superfloh247** [comment]
please also confirm fix in 1.47.6.0 commit c765563012d78ad2658e948e7809e2bb40c920ba

**Comment by pbertra** [comment]
I updated now.
Will monitor to see if it stays quiet.

**Comment by bassmaster187** [comment]
After 24 hours on a docker with 6 cars connected I don't see any memory leaks anymore.

```
04.04.2021 23:00:29 : TeslaLogger process statistics
WorkingSet64: 64880640
PeakWorkingSet64: 126754816
```

**Comment by pbertra** [comment]
Memory usage seems to be stable for the docker container, around 120MB
