### ISSUE TITLE
"funny" charts in dashboard Akku Trips

### ISSUE THREAD

**Issue by mss1010** [bassmaster187/TeslaLogger#559]
In the akku trips dashboard, on top there are some funny charts, which are technically wrong.
There are parts which have multiple y values for an x value, which is impossible:

![grafik](https://user-images.githubusercontent.com/36116339/115070890-d43ee580-9ef5-11eb-933a-5c74cf8cdf33.png)

**Comment by Adminius** [comment]
that is the way grafana displays lines... it's not a bug, it's a feature ;)

**Comment by Adminius** [comment]
@mss1010, can we or you close this issue or do you have other questions?
