### ISSUE TITLE
Add user authentication/login feature to admin portal

### ISSUE THREAD

**Issue by kylefu8** [bassmaster187/TeslaLogger#574]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to have an authentication/login feature to admin portal. Then we could expose the admin IP/page to the internet.

**Describe alternatives you've considered**
Integrate admin portal to Grafana, and leverage its authentication module.

**Additional context**
None. Thanks for creating such a wonderful tool for Tesla users:)

**Comment by bassmaster187** [comment]
Please update to newest version. If you running on Docker. Make supre you update the dockerfile: https://github.com/bassmaster187/TeslaLogger/blob/master/docker_setup.md#docker-update--upgrade

Let me know if it works for you

https://github.com/bassmaster187/TeslaLogger/commit/796b5a9b566d067b360306dc25e68db26cd80c8f
