### ISSUE TITLE
Unable to login to Tesla account

### ISSUE THREAD

**Issue by Sleepy81** [bassmaster187/TeslaLogger#589]
** Append Logfile **
30.05.2021 20:52:08 : SetPassword
30.05.2021 20:52:08 : reconnect Car #1
30.05.2021 20:52:08 : #1: Abort: Reconnect!
30.05.2021 20:52:08 : Start Reconnect!
30.05.2021 20:52:08 : #1: GetAvgConsumption: nothing found!!!
30.05.2021 20:52:08 : #1: No Refresh Token
30.05.2021 20:52:08 : #1: Login with : 'REMOVED' / 'REMOVED'
30.05.2021 20:52:09 : #1: GetTokenAsync2
30.05.2021 20:52:10 : #1: Error: GetTokenAsync2 HttpStatus: OK / Expecting: Redirect !!!
30.05.2021 20:52:10 : #1: Error: GetTokenAsync2 Redirect Location = null!!! Wrong credentials?
30.05.2021 20:52:10 : #1: Abort: Tesla_token == NULL
30.05.2021 20:52:10 : #1: *** Exit Loop !!!

Edit: Removed partially anonymized login details.

**Describe the bug**
Unable to login to Tesla account. Positive I used the correct login credentials.
Best guess is because Tesla started to use CAPTCHA.

**To Reproduce**
Create a new TeslaLogger install, and try to connect to Tesla account.

** Teslalogger Type **
Docker on Synology NAS. v 1.48.3.0

**Comment by bassmaster187** [comment]
Exactly, it's because of using captcha since last friday. I'll try to get a new version ASAP

**Comment by bassmaster187** [comment]
Please check if it works now

**Comment by Sleepy81** [comment]
Works fine now!
