### ISSUE TITLE
Install instructions without docker

### ISSUE THREAD

**Issue by paulhargreaves** [bassmaster187/TeslaLogger#591]
**Is your feature request related to a problem? Please describe.**
I'd like to install without a PI and without docker. There are currently no instructions on the right way to do this.

**Describe the solution you'd like**
Instructions to appear.

**Describe alternatives you've considered**
Running with docker. I've created a VM instead of using docker since docker messes up host virtual networking, and I prefer the isolation/backup capabilities of a VM.

**Additional context**
None.

**Comment by bassmaster187** [comment]
Install Docker on a VM and run the docker inside of the VM.
