### ISSUE TITLE
Unable to download SRTM data from https://dds.cr.usgs.gov/srtm/version2_1/SRTM3

### ISSUE THREAD

**Issue by sgaert** [bassmaster187/TeslaLogger#596]
Since some days i can´t download SRTM data.

> 19.06.2021 14:17:37 : Reverse geocoding by MapQuest: 7
> 19.06.2021 14:17:37 : Download failed: https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/N47E010.hgt.zip
> 19.06.2021 14:17:37 : #1: change TeslaLogger state: Start -> Online
> 19.06.2021 14:17:38 : Download failed: https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/North_America/N47E010.hgt.zip
> 19.06.2021 14:17:39 : Download failed: https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/South_America/N47E010.hgt.zip
> 19.06.2021 14:17:39 : Download failed: https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Australia/N47E010.hgt.zip
> 19.06.2021 14:17:40 : Download failed: https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Islands/N47E010.hgt.zip

**To Reproduce**
finsh drive in an area without known SRTM data

** Teslalogger Type **
Docker
Did you update the Image with apt-get update & upgrade? Yes

** Do you use Tasker or iBeacon **
No

**Additional context**
browse to any *.hgt.zip file on https://dds.cr.usgs.gov/srtm/version2_1/SRTM3 in the browser return a 404.
maybe an other souce of SRTM files is required like https://srtm.kurviger.de/SRTM3/

**Comment by bassmaster187** [comment]
Please check the new Teslalogger version
