### ISSUE TITLE
Question: Integration with existing RasPi image/project?

### ISSUE THREAD

**Issue by n-gineer** [bassmaster187/TeslaLogger#600]
I am making a robotic arm to charger my car. It will depend on some data from the car (e.g. location, heading, charge state) as well as commands (open charge port, stop charging, lock charge port).

I already have my own RasPi setup for most of the computer vision tasks. I'd like to add on TeslaLogger to have this Pi be multi-function and simplify the data retrieval, key refresh, and commands. However, this project seems to be setup for only a standalone clean install on a new Pi. Is adding it on to an existing Pi a problem? "Feature Request" may not be the best label, as it may already be possible. This is more of a "Question".

I have considered purchasing a separate Pi to perform only the logging as an alternative, but it seems duplicative on hardware and software.

Thanks!

**Comment by Adminius** [comment]
theoretically it is possible to add additional functionality.
But: each TeslaLogger update restarts RasPi. If it's ok for you, try it out :)
Alternative: you can use docker.
