### ISSUE TITLE
Captcha Bug / Login with new Account not Working

### ISSUE THREAD

**Issue by fynnsh** [bassmaster187/TeslaLogger#603]
** Append Logfile **
08.07.2021 13:36:49 : #1: No Refresh Token
08.07.2021 13:36:49 : #1: Login with : 'XXXXXXXX.Xe' / 'xxxxxxxxx'
08.07.2021 13:36:50 : #1: GetTokenAsync2
08.07.2021 13:36:50 : #1: Error: GetTokenAsync2 HttpStatus: OK / Expecting: Redirect !!!

08.07.2021 13:36:50 : #1: Error: GetTokenAsync2 Redirect Location = null!!! Wrong credentials?

08.07.2021 13:36:50 : #1: Abort: Tesla_token == NULL

08.07.2021 13:36:50 : #1: *** Exit Loop !!!

**Describe the bug**
Login not Working

**To Reproduce**

Login with new Account

**Screenshots**
![image](https://user-images.githubusercontent.com/24509725/124915353-badba000-dff1-11eb-9a24-95df9c563268.png)

** Teslalogger Type **
Docker

**Comment by bassmaster187** [comment]
please retry with new version
