### ISSUE TITLE
How to migrate from Raspberry to Docker?

### ISSUE THREAD

**Issue by Scotty1928** [bassmaster187/TeslaLogger#612]
Hey folks,
My raspberry has issues with it's ethernet port, which does not function anymore.

Now since i have a docker host already running anyways, how do i migrate to docker?

Thanks for your advice
Scotty

**Comment by rowich** [comment]
Hi Scotty
you need a usable backup file from the database. This is generated
automagically every night as long as the raspberry works. If ethernet is
no longer working, you need to either extract the file from the SD card,
or you need to connect a screen and keyboard to the raspberry, logon and
copy the file another connected USB stick. If you like to preserve also
your favourites, copy also the private geofence backup file from the
same folder. This is the tricky part.

You'll find the files at /etc/teslalogger/backup



The docker part is quite easy (I never did it, but I did the similar
steps with a newer raspberry).
Get Teslalogger running and on the admin interface, import the DB file
using "Extras / Restore database". This could take a while.
Afterwards, configure your car credentials in the upper part of the
regular settings dialog. Done.

If you have more than one car, ensure to preserve the order of the cars.

Unfortunately, the restore of the geofence file is not that easy. If you
run Windows, connect to the "\\teslalogger\teslalogger" share, unpack
the private file (e.g. using 7ZIP) and replace the existing
"geofence-private.csv" file with the one from the backup. You could also
restore the file directly using ssh at /etc/teslalogger

Hope this helps.

(and sorry, the manual explains that all, but is currently only
available in german language and the multi language online version is
blocked at my desk...)

Cheers,
  Rolf.


Am 01.08.2021 um 13:13 schrieb Scotty1928:

**Comment by Scotty1928** [comment]
i'll try that tomorrow. if it does not work out i'll ask again 😄 
thank you!
