### ISSUE TITLE
No external requests

### ISSUE THREAD

**Issue by dr2okevin** [bassmaster187/TeslaLogger#613]
Using the admin interface currently requires me to allow scripts from the following domains
* jquery.com
* unpkg.com
* teslalogger.com
* impala64.com

The reason for using self hosted software is for not spreading a lot of data all over the internet. Especially behind jquery.com and unpkg.com are big companies who can collect information over a lot of different websites.

It would make it also possible to use the teslalogger when these services are not available. It happened already in the past that a lot of website stopped working because one of the big cloud companies had network trouble.

And even more, it would improve the speed, because getting data from the local network is faster then getting it from the internet.

**Comment by Adminius** [comment]
fixed https://github.com/bassmaster187/TeslaLogger/commit/715587540b2832ffad059ffa1bdf2d64dd9372e4
