### ISSUE TITLE
Not intentionally set admin panel password

### ISSUE THREAD

**Issue by rowich** [bassmaster187/TeslaLogger#615]
A friend of mine just reported that his Teslalogger Admin Panel is asking for a password, but he never set one. I don't think that a family member was doing that to trick him.

I know it's a (new) dialog in the settings dialog, but how to get rid of it if accidentially set or forgotten?

I expect we have still access to the file system...

BTW: It got detected after finding that the logger was not recording anymore for around one month... (don't think we're going to find out why)

**Comment by Adminius** [comment]
via ssh remove .htaccess file

rm /var/www/html/.htaccess
