### ISSUE TITLE
Webserver container built on synology NAS has errors (Could not initialize random number generator)

### ISSUE THREAD

**Issue by tkuehne71** [bassmaster187/TeslaLogger#617]
** Append Logfile **
n/a

**Describe the bug**
I am installing TeslaLogger on my Synology NAS running DSM 6.2.4-25556. The installed Docker package is version 20.10.3-0554.

I am running the installation as per the description and the steps complete without errors. However the finished webservice (teslalogger_webserver_1) container goes into a restart loop. The docker log shows the error message:

Function not implemented: AH00141: Could not initialize random number generator

This seems to be a problem of the webserver and might require a newer kernel or a different library.

**Comment by bassmaster187** [comment]
is this fixed already fixed?

**Comment by tkuehne71** [comment]
I haven‘t checked recently as I moved the installation to another system.

**Comment by ThomasTr** [comment]
Had same problem. Even the newest DSM Version (DSM 7.0.1-42218) has a very old kernel: 3.10.108. This old kernel does not support the needed function used by apache. My workaround is to use a slightly different webserver: php:7.3-apache-buster

For that change first line in teslalogger/docker/webserver/Dockerfile to `FROM php:7.3-apache-buster`

@bassmaster187: Willing to change these in the Dockerfile? Can provide Pull request.

**Comment by Kabulla** [comment]
> Had same problem. Even the newest DSM Version (DSM 7.0.1-42218) has a very old kernel: 3.10.108. This old kernel does not support the needed function used by apache. My workaround is to use a slightly different webserver: php:7.3-apache-buster
> 
> For that change first line in teslalogger/docker/webserver/Dockerfile to `FROM php:7.3-apache-buster`
> 
> @bassmaster187: Willing to change these in the Dockerfile? Can provide Pull request.

yup, that does the trick, thank you!
