### ISSUE TITLE
Add "drive in autopilot"

### ISSUE THREAD

**Issue by IceDragoneu** [bassmaster187/TeslaLogger#619]
Hello,

it would be an awesome feature to track the routes driven in autopilot mode.
An additional bool value in the pos table would be perfect, if the tesla api gives out these data.

In grafana there could be stats about XX percent driven in autopilot mode, or on a map the driven route could be displayed in different colors depending on the autopilot stats.

Best Regards
IceDragon

**Comment by superfloh247** [comment]
no trace whatsoever in the API whether AP is enabled or not
