### ISSUE TITLE
Error: GetTokenAsync2 Redirect Location = null!!! Wrong credentials? / *** Recaptcha not supported!!! ***

### ISSUE THREAD

**Issue by jonasf21** [bassmaster187/TeslaLogger#636]
Just installed teslalogger on a fresh raspi (on pi4) install. Everything went fine however i cant register my account/car:

06.09.2021 15:11:51 : #1: GetAvgConsumption: nothing found!!!
06.09.2021 15:11:51 : #1: No Refresh Token
06.09.2021 15:11:51 : #1: Login with : 'XonXsXXreXXgXx.Xe' / 'xxxxxxxx'
06.09.2021 15:11:51 : No MQTTHost settings -> MQTT disabled!
gs -> MQTT disabled!
06.09.2021 15:11:51 : MQTT terminated
06.09.2021 15:11:52 : #1: GetTokenAsync2
06.09.2021 15:11:52 : #1: *** Recaptcha not supported!!! ***
06.09.2021 15:11:52 : #1: Error: GetTokenAsync2 HttpStatus: OK / Expecting: Redirect !!!
06.09.2021 15:11:52 : #1: Error: GetTokenAsync2 Redirect Location = null!!! Wrong credentials?
06.09.2021 15:11:52 : #1: Abort: Tesla_token == NULL
06.09.2021 15:11:52 : #1: *** Exit Loop !!!

Changed my tesla account pass and updated credentials, still the same. Any hints?

**Comment by Adminius** [comment]
update to new 1.48.10.0 version and try again

**Comment by jonasf21** [comment]
I am already on that version:

06.09.2021 15:11:33 : TeslaLogger Version: 1.48.10.0
06.09.2021 15:11:34 : Teslalogger Online Version: 1.48.10.0
06.09.2021 15:11:34 : Logfile Version: 1.0.10.0

**Comment by speedAmaster** [comment]
I am working off the same updated versions.
I removed my car (have no successful data logged anyway). Try to put a new car back in. 
I cannot see any captcha. "Recaptcha not supported!!!"
see LOG:

06.09.2021 16:37:30 : SetPassword
06.09.2021 16:37:30 : Insert Password
06.09.2021 16:37:30 : #1: GetAvgConsumption: nothing found!!!
06.09.2021 16:37:30 : #1: No Refresh Token
06.09.2021 16:37:30 : #1: Login with : 'yyyyyyyyyyyyy' / 'xxxxxxxxxxxxxxx'
06.09.2021 16:37:30 : #1: GetTokenAsync2
06.09.2021 16:37:31 : #1: *** Recaptcha not supported!!! ***
06.09.2021 16:37:31 : #1: Error: GetTokenAsync2 HttpStatus: OK / Expecting: Redirect !!!
06.09.2021 16:37:31 : #1: Error: GetTokenAsync2 Redirect Location = null!!! Wrong credentials?
06.09.2021 16:37:31 : #1: Abort: Tesla_token == NULL
06.09.2021 16:37:31 : #1: *** Exit Loop !!!

**Comment by rschillerlnw** [comment]
Same errors here - I changed my Tesla password and wanted to update Teslalogger with the new credentials. And bam-no more connectivity :(

**Comment by bassmaster187** [comment]
I have a working solution on .net Framework (Windows), but it seems like it's not working on Mono (Raspebrry / Docker)

**Comment by speedAmaster** [comment]
great step! unfortunately not a solution for many. hopefully it can be done on docker as well, soon

**Comment by bassmaster187** [comment]
> great step! unfortunately not a solution for many. hopefully it can be done on docker as well, soon

I tried latest Mono version but it still asks für reCaptcha. I'll try .net core for the next Step

**Comment by bassmaster187** [comment]
With the new version you can use access token & refresh token from a 3rd party webview based app for authentification.

I am still searching for a solution for mono, but can't promise a fast solution.

![image](https://user-images.githubusercontent.com/6816385/132405840-32695dc5-a67f-4fde-89fb-df83bb91b9c6.png)
