### ISSUE TITLE
Model Y: Charging phases reported incorrectly

### ISSUE THREAD

**Issue by jonasf21** [bassmaster187/TeslaLogger#641]
Running 1.48.11.0 with docker images

My Model Y is reporting incorrect charging values:

Wird geladen: | 6 kW / +23.16 kWh  238V / 8A / 2P Fertig: 1h 55m Fertig um: 2:42 PM / 90%

As you can see its reporting only 2 phases. The telsa app (4.0.1 on android) is also not reporting 3 phases (the round 3 icon is missing). However inside the car it is reporting that charging is indeed on 3 phases (ver 2021.32.5).

My energy meter (SMA energy meter) is also reporting that its charging on 3 phases.

Can it safely be assumed this is a bug within tesla's API?

**Comment by rowich** [comment]
Yes, this is an unfortunately well known bug in the Tesla API.

Am 13.09.2021 um 12:52 schrieb jonasf21:

**Comment by jonasf21** [comment]
Ok, thanks for clarification.
