### ISSUE TITLE
Import from Teslamate fails as no .netcore 4.5.2 is available anymore for linux

### ISSUE THREAD

**Issue by kysersoze81** [bassmaster187/TeslaLogger#643]
** Append Logfile **
Not relevant for this issue.

**Describe the bug**
Followed instructions in [guide ](https://github.com/bassmaster187/TeslaLogger/tree/master/Teslamate-Import)to import from TeslaMate in docker to TeslaLogger in docker get this error

root@Teslalogger:/home/TeslaLogger/TeslaLogger# dotnet run /home/TeslaLogger/Teslamate-Import/bin/Teslamate-Import.exe
/usr/share/dotnet/sdk/5.0.401/Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.5.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/TeslaLogger/TeslaLogger/TeslaLogger.csproj]

The build failed. Fix the build errors and run again.

**To Reproduce**
setup docker containers with port 5432 open on Teslamate postgres . 
configure Teslamate-Import.exe.config with IP and credentials for TelsaMate and Teslalogger. 
install .netcore .... only 5.1 and 3.1 were available so I installed both
(apt install aspnetcore-runtime-3.1 aspnetcore-targeting-pack-3.1)
(apt install aspnetcore-runtime-5.1 aspnetcore-targeting-pack-5.1)
try running it . It fails because .NET 4 is no longer available from Microsoft

**Expected behavior**
Slowly import data to Teslalogger

** Teslalogger Type **
 Docker /
Did you update the Image with apt-get update & upgrade? no

** Do you use Tasker or iBeacon **
no

**Additional context**
I think the resolution would be to adjust import script to work with .NET 5.1
running current version (TeslaLogger is up to date (current version: 1.48.12.0, latest version online: 1.48.12.0, update policy: all))
running on docker (latest) Debian 10 LXC (updated) under Proxmox (7.0-11)

**Comment by bassmaster187** [comment]
could you please try to use mono to run teslamate import tool?

**Comment by kysersoze81** [comment]
> could you please try to use mono to run teslamate import tool?

I installed mono and it took about 4 hrs. but looks like its gotten it all moved over. Should have thought of that myself.
Maybe update the Teslamate-Import/README.md 
Thanks for your help
