### ISSUE TITLE
TM3 P 2021 not detected correctly

### ISSUE THREAD

**Issue by Shrekmachine** [bassmaster187/TeslaLogger#652]
M3 P 2021 Performance identified as M3 SR+ 2021 (LWR E3D6)
Version Teslalogger: | 1.48.14.0

**Comment by bassmaster187** [comment]
Please post your output from:
http://raspberry:5000/decodecar/1

**Comment by Shrekmachine** [comment]
Server is responding with 404
![image](https://user-images.githubusercontent.com/8019511/135059336-63cc0ce5-76d2-41f8-98cc-4075bcac0ccb.png)

admin is working fine http://berry4:8888/admin/index.php

**Comment by Shrekmachine** [comment]
Cosmo has same issue. let me assume if you find the issue by using his protocol, mine could be solved as well.
https://tff-forum.de/t/teslalogger-mit-raspberry-pi-mysql-grafana-osm/100891/2046

**Comment by Shrekmachine** [comment]
Jetzt wird das Model korrekt angezeigt. Kann es sein, dass man mind. einmal laden muss?

**Comment by bassmaster187** [comment]
Ja, man muss ein mal laden, damit das Fahrzeug erkannt wird.
