### ISSUE TITLE
Settings Page Error: Connection refused - URL: http://teslalogger:8888/getallcars'

### ISSUE THREAD

**Issue by Shrekmachine** [bassmaster187/TeslaLogger#653]
** Append Logfile **
you find it here: \\raspberry\teslalogger\nohup.out
Can't find this

**Describe the bug**
![image](https://user-images.githubusercontent.com/8019511/134818809-1503b9ac-52b3-4b70-b063-de1ae84a7553.png)

**To Reproduce**
Call Settings

**Expected behavior**
No Error message

**Screenshots**
![image](https://user-images.githubusercontent.com/8019511/134818820-52c5278a-c950-498d-824d-a746641c45fb.png)

** Teslalogger Type **
Raspberry PI 4
Did you update the Image with apt-get update & upgrade? yes
[logfile.zip](https://github.com/bassmaster187/TeslaLogger/files/7234356/logfile.zip)

** Do you use Tasker or iBeacon **
no
**Additional context**

**Comment by rowich** [comment]
@Shrekmachine:
Get the current logfile via Admin Panel:
Menu item "Logfile" (where you also have "Settings"), then "Download
Logfile" at the upper left corner

Am 26.09.2021 um 19:58 schrieb Shrekmachine:
>
> ** Append Logfile **
> you find it here: \raspberry\teslalogger\nohup.out
> Can't find this
>
>
...

**Comment by Shrekmachine** [comment]
ok, I was searching for the file in the directory. File attached. 
In the meantime issues grow. Teslalogger not showing any data even that I drove, charged etc.

**Comment by rowich** [comment]
Sorry, no, there is nothing attached
I recommend to open the ZIPped file and paste the content here or online
on github into the message.
Is your version on the current level (1.48.14.0)? I remember I had a
similar issue before, but never again with the current version. There
were issues with the Tesla token, which are solved with the .14 release.
You might have to re-authenticate again your car if nothing is currently
recorded. Ensure to have the latest version.

BTW: I personally cannot help to solve your issue, I was only seeing
that you didn't knew how to find the logfile.

Am 27.09.2021 um 09:51 schrieb Shrekmachine:
>
> ok, I was searching for the file in the directory. File attached.
> In the meantime issues grow. Teslalogger not showing any data even
> that I drove, charged etc.
>

**Comment by Shrekmachine** [comment]
it is in the original message. I can see it inline as "logfile.zip".
Version is update to date. I cloned it last night (1.18.14.0)
I tried to renew the token, which did not work. very strange. I tend to completely remove and reinstall TeslaLogger.
Please note: I'm not a "Linux geek"
Thanks a lot, highly appreciated.

**Comment by rowich** [comment]
OK, the logfile has been added to your original text with the screen shots, so this should be fine now and probably helpful for those able to help. Good to hear that you have the current version running, not good to read that the token refresh was not working. The reinstall is quite easy as long as you have your current backup for database and private-geofence in a safe place.
I am neither a Linux geek nor one of the software specialists here but an IT specialist with wide horizon ;-)

**Comment by bassmaster187** [comment]
Port 8888 is probably the wrong port. It can't be used by Teslalogger and Apache at the same time. Please set it to default port 5000 unless you really have another listener on port 5000.

![image](https://user-images.githubusercontent.com/6816385/135057566-d0a853a0-e120-4c21-9d4c-045404908a5f.png)

**Comment by Shrekmachine** [comment]
Then the error message comes back on top of settings page:
errortext = 'Error: Connection refused - URL: http://teslalogger:5000/getallcars'
With Teslalogger HTTP Port = 8888 it was gone
Server is refusing all connections on port 5000

**Comment by bassmaster187** [comment]
please send me a current logfile after changing to port 5000

**Comment by Shrekmachine** [comment]
I do not know how to change to port 5000? What and how?
All I can say that currently Port 5000 is not listening as `netstat -an | grep 5000 | grep -i listen` responds without any verbose message"

**Comment by Shrekmachine** [comment]
Mit Port 8888 komme ich Problemlos auf alle TL Seiten. Nur http://xxxx:port/decodecar/1 funktioniert nicht. 5000 wird abgelehnt und bei 8888 kommt 
![image](https://user-images.githubusercontent.com/8019511/135071466-0ed6db03-dbfa-43ab-a609-956184d79ef5.png)

**Comment by bassmaster187** [comment]
Ich brauche dein Logfile vom Teslalogger

**Comment by Shrekmachine** [comment]
[logfile.zip](https://github.com/bassmaster187/TeslaLogger/files/7243719/logfile.zip)

**Comment by bassmaster187** [comment]
Laut logfile konnte der Port geöffnet werden
28.09.2021 12:46:12 : HttpListener bound to http://*:5000/

geh mal bitte im Admin Panel und schau mal ob er immer noch die Fehlermeldung bringt, dass er getallcars nicht öffnen kann

**Comment by Shrekmachine** [comment]
Im Moment taucht sie nicht auf.

**Comment by Shrekmachine** [comment]
http://berry4:5000/decodecar/1 funktioniert nicht

**Comment by Shrekmachine** [comment]
> Ich sehe jetzt auch das erste Mal Tripdaten auf der Index Seite

und jetzt, nach einem Reboot, sind sie wieder weg. Ich verstehe das nicht.

**Comment by bassmaster187** [comment]
Beim Docker wird nicht Port 5000 freigegeben sondern Port 5010, weil das mit Synology Probleme macht.

Probier mal: http://berry4:5010/decodecar/1

**Comment by Shrekmachine** [comment]
Na bitte! 
ModelName:M3 LR P 2021
Wh_TR:0.158

AvgMaxRage:501

display_name:Meep!
vin:LRW3E7EL5MCXXXXXX
car_type:model3
car_special_type:base
trim_badging:p74d
has_ludicrous_mode:False
DB_Wh_TR:0

VIN Year:2021
VIN carType:Model 3
VIN AWD:True
VIN MIC:True
VIN battery:NMC
VIN motor:Y dual
Voltage at 50% SOC:0V Date:1/1/0001 12:00:00 AM
Vehicle Config:
{
    "response":
    {
        "can_accept_navigation_requests":true,
        "can_actuate_trunks":true,
        "car_special_type":"base",
        "car_type":"model3",
        "charge_port_type":"CCS",
        "default_charge_to_max":false,
        "driver_assist":"TeslaAP3",
        "ece_restrictions":true,
        "efficiency_package":"M32021",
        "eu_vehicle":true,
        "exterior_color":"PearlWhite",
        "exterior_trim":"Black",
        "has_air_suspension":false,
        "has_ludicrous_mode":false,
        "interior_trim_type":"White2",
        "key_version":2,
        "motorized_charge_port":true,
        "performance_package":"Performance",
        "plg":true,
        "rear_drive_unit":"PM216MOSFET",
        "rear_seat_heaters":1,
        "rear_seat_type":0,
        "rhd":false,
        "roof_color":"RoofColorGlass",
        "seat_type":null,
        "spoiler_type":"Passive",
        "sun_roof_installed":null,
        "third_row_seats":"None",
        "timestamp":1632833193883,
        "trim_badging":"p74d",
        "use_range_badging":true,
        "wheel_type":"UberTurbine20Gunpowder"
    }
}

**Comment by Shrekmachine** [comment]
Auf j+ sehe ich die Tripdaten inzwischen wieder, auf TeslaLogger nicht

**Comment by Shrekmachine** [comment]
Jetzt hat sich auch TeslaLogger berappelt. Sehr merkwürdig, dass das über Nacht gedauert hat.
Auch die Fehlermeldung taucht momentan nicht mehr auf.
Ich mache zu.
Danke für die Unterstützung
