### ISSUE TITLE
Grafana Ladehistorie zeigt falschen Wert für "geladen kWh" an

### ISSUE THREAD

**Issue by superfloh247** [bassmaster187/TeslaLogger#655]
überall wo charging_end.charge_energy_added verwendet wird sollte chargingstate.charge_energy_added verwendet werden

chargingstate.charge_energy_added wird oft korrekt berechnet bei zusammengefassten Ladungen, mit https://github.com/superfloh247/TeslaLogger/tree/feature-integrate-charge-energy-added sollte es dann wieder überall stimmen, auch rückwirkend

die Ladestatistik sollte dann auch auf dem korrekt berechneten wert basieren

**Comment by bassmaster187** [comment]
https://github.com/bassmaster187/TeslaLogger/commit/93f7641aef17b5b562a07a707eb48e2d10ac3af2
