### ISSUE TITLE
Geofence *Solved*

### ISSUE THREAD

**Issue by Powerbook001** [bassmaster187/TeslaLogger#682]
Hallo,
I recently migrated from Teslamate because I find more complete Teslalogger, especially for integrations with other software.

But I cannot create any new Geofence, because in the "trip" section of Grafana the address to click on to add a Geofence does not appear. I just have a blank, unless I already have a Geofence that I have imported from Teslamate.

Am I missing something, is there some other way to create them?

Thank you,

Nico

<img width="557" alt="Screenshot 2021-11-01 at 09 40 32" src="https://user-images.githubusercontent.com/16048535/139645467-0e3f7cf7-c06d-4cff-935a-f9444b876815.png">

**Comment by rowich** [comment]
Hello Nico

Your list looks weird, mine looks different - there are no locations in 
your list from where to where your trip went as here:


(note: Mouse cursor was flying above the "Start Address", here: 79618 
Rheinfelden...)

Cheers,
   Rolf.

Am 01.11.2021 um 09:45 schrieb Nico:

**Comment by Powerbook001** [comment]
In the blank field it should appear the address of the location, also if there is not any geofence?
Am I right?

**Comment by rowich** [comment]
Correct - otherwise it would list the individual name via Geofence 
definition and not the original Street/City stuff.
Are these entries on your side imported trips, have you tried that 
already with current trips recorded from Teslalogger on it's own?

Am 01.11.2021 um 10:51 schrieb Nico:

**Comment by Powerbook001** [comment]
It does not change weather are imported or real trip logged by Teslalogger.
The addresses do not appear. But if I enter the single trip I can see the location on the map correctly.

**Comment by bassmaster187** [comment]
Did you Import your data? If yes from where? Maybe there is a bug in any import tool.

**Comment by Powerbook001** [comment]
I imported from Teslmate.

**Comment by Powerbook001** [comment]
is there something I can do to solve the issue?
Thank you

**Comment by superfloh247** [comment]
Missing addresses for start and destination are usually computed when TeslaLogger restarts.
To comply with the usage agreement of "nominatim" the reverse address resolution (lat+lng to address) will take a really long time if it has to get lots of addresses. This should be visible in the log file, please attach nohup.out.

**Comment by Powerbook001** [comment]
It's quite large....

[nohup.out.zip](https://github.com/bassmaster187/TeslaLogger/files/7463860/nohup.out.zip)

**Comment by superfloh247** [comment]
I think you cannot update properly with the integrated update function in docker

openWB is not configured properly
31.10.2021 07:04:32 : System.Net.WebException: Could not find a part of the path "/openWB/web/api.php?get=all"

MQTT is not configured properly
31.10.2021 07:05:02 : 31.10.2021 07:05:02 : System.NullReferenceException: Object reference not set to an instance of an object
.Main (System.String[] args) [0x00161] in <7c8487d453604b61a02420b1943b9207>:0 
31.10.2021 07:05:02 :   at MQTTClient.Program.Main (System.String[] args) [0x00161] in <7c8487d453604b61a02420b1943b9207>:0 

I have never seen this error, do you run several instances in parallel?
01.11.2021 14:09:01 : Sharing violation on path /etc/teslalogger/GeocodeCache.xml

UpdateAllPOIAddresses, which is the function that should fill your missing addresses, starts very often but almost never finishes (interrupted by restart)

**Comment by Powerbook001** [comment]
I’m running Docker in a Mac server. I’m not using parallels.
I also have some issues with mqtt as you also noted. The config file is correctly configured, but TeslaLogger does not comunicate with the broker….
You think that should be better to run teslamate on a NAS or raspberrly? Could the OS be the issue?
Thank you

**Comment by Powerbook001** [comment]
I tried removing the Mqtt configuration and I think that it's starting to reverse geo coding.

```

03.11.2021 21:10:22 : Reverse geocoding by Nominatim4
03.11.2021 21:10:27 : GeocodeCache:Insert
03.11.2021 21:10:27 : Reverse geocoding by Nominatim5
03.11.2021 21:10:32 : GeocodeCache:Insert
03.11.2021 21:10:32 : Reverse geocoding by Nominatim6
03.11.2021 21:10:37 : GeocodeCache:Insert
03.11.2021 21:10:37 : Reverse geocoding by Nominatim7
03.11.2021 21:10:42 : GeocodeCache:Insert
03.11.2021 21:10:42 : Reverse geocoding by Nominatim8
03.11.2021 21:10:47 : GeocodeCache:Insert
03.11.2021 21:10:47 : Reverse geocoding by Nominatim9
03.11.2021 21:10:52 : GeocodeCache:Insert
03.11.2021 21:10:52 : Reverse geocoding by Nominatim10
03.11.2021 21:10:57 : GeocodeCache:Insert
03.11.2021 21:10:57 : Reverse geocoding by Nominatim11
03.11.2021 21:11:02 : GeocodeCache:Insert
03.11.2021 21:11:02 : Reverse geocoding by Nominatim12
03.11.2021 21:11:07 : GeocodeCache:Insert
03.11.2021 21:11:07 : Reverse geocoding by Nominatim13

```

**Comment by superfloh247** [comment]
good news :-)

I have no idea why and how a faulty MQTT config could interrupt TeslaLogger in such a way

**Comment by Powerbook001** [comment]
I confirm that the process has terminated and all addresses now appear correctly.

By the way it would be great to have the possibility to be able to set up Mqtt paramaters directly in the setting section.
