### ISSUE TITLE
Shelly 3EM as „Wallbox“ in TL

### ISSUE THREAD

**Issue by sirathan** [bassmaster187/TeslaLogger#688]
I am using a Fronius Wattpilot Wallbox. The Wallbox is based on Go-e Charger but unfortunatley the API is closed until now. Therefore the wallbox cannot be integrated in TL. 

To measure the power consumed by the wallbox i installed a 3 phase smartmeter (Shelly 3EM) to the wallbox. With this workaround i was able integrate the wallbox in solaranzeige.de (as the Shelly 3EM is integrated there)

I am interessted in integrating the wallbox into TL, as you did it with openWB, go-e and Tesla Wallbox. 

Maybe it would be a nice feature for other users with unsupported wallboxes or wallboxes without API or UMC to install a Shelly 3 EM and integrate it into TL. The Shelly has an open API and costs only about 100€. 

So my request is: Can you integrate Shelly 3 EM into TL to support the wallbox features?

I would be available 4 testing.

**Comment by bassmaster187** [comment]
If you provide  me a portforwarding to your Shelly I could try to support it. Please send me your IP address and port to my email. You can find it here: https://www.impala64.de/blog/kontakt/

**Comment by superfloh247** [comment]
https://shelly-api-docs.shelly.cloud/gen1/#shelly-3em-mqtt

**Comment by bassmaster187** [comment]
Please check if it's working with latest version

**Comment by bassmaster187** [comment]
Please make sure you update manually even if you have the latest version because I have updated Teslalogger without increasing the version. 
https://github.com/bassmaster187/TeslaLogger/commit/e7d7f6ae8b2361f7b8a23af9796ac3c07e6e2940

**Comment by sirathan** [comment]
Connection check / info looks good. 
![image](https://user-images.githubusercontent.com/93380362/140551174-89d08d8b-04f3-4e71-b485-395876def016.png)

Efficiency in Graphana "Ladehistory" looks a bit high ;-) but i only just started charging.

![image](https://user-images.githubusercontent.com/93380362/140551325-b5e72b16-e862-4c95-aa66-c293bd62a867.png)

Is there another place where i can see some output?

**Comment by bassmaster187** [comment]
After first charging at home you should see the efficiency calculated by Shelly in charging history dashboard

![image](https://user-images.githubusercontent.com/6816385/140563367-52f89056-37ec-46f6-8c72-44a9eb73ae49.png)

**Comment by sirathan** [comment]
i found it there, but it seems a bit to efficient. 

![image](https://user-images.githubusercontent.com/93380362/140563872-ddaa3527-b99a-4ea5-bfc4-9013612a4e12.jpeg)

**Comment by sirathan** [comment]
If i change the select statement in the "Ladehistory" dashboard by switching "cost_kwh_meter_invoce" and "chargingstat.charge_engerg_added" i get an EFF of 92% whiche seams more reasonably. Could this be the solutoin?

New statement is like this:
              cost_kwh_meter_invoice / chargingstate.charge_energy_added  * 100 as Eff,


![image](https://user-images.githubusercontent.com/93380362/140570937-99d2d5cf-37e3-4e75-af88-e6701a3920f8.png)

**Comment by sirathan** [comment]
Hi Christian. Where you able to have a look at the effeciency calculation. It always shows values above 100%.

**Comment by Powerbook001** [comment]
Forgive me,
I'm using a Shelly 3EM (tree phases).
What should I write in the serting field "parameters" ?
Because any value I insert I get a "null" value result.

Thank you

**Comment by sirathan** [comment]
I only insert the IP adress, no params

![image](https://user-images.githubusercontent.com/93380362/145570925-f71152ff-3fda-4041-8c68-a2181c0d77c7.jpeg)

**Comment by Powerbook001** [comment]
I get a "null"

![image](https://user-images.githubusercontent.com/16048535/145572625-a8f26f3e-fd21-4608-8fb0-8df4677886e4.jpeg)

**Comment by Powerbook001** [comment]
Maybe does not work because I have usr/psw access?

**Comment by sirathan** [comment]
This might be the Problem. i am not using uid/pw on my shelly

**Comment by Powerbook001** [comment]
I tried removing password and also checked while charging. 
But still get "Null"...
