### ISSUE TITLE
Wrong Fase charge reported

### ISSUE THREAD

**Issue by Powerbook001** [bassmaster187/TeslaLogger#689]
I realized recently that TL reports a 2 phase charge although I was charging with a 3 phase charger with 16Amps.

![image](https://user-images.githubusercontent.com/16048535/140754448-fc3f9583-3fff-451f-814e-00c726968816.jpeg)

**Comment by Powerbook001** [comment]
Sorry I realized that there was a ticket open already.

**Comment by bassmaster187** [comment]
Duplikate: https://github.com/bassmaster187/TeslaLogger/issues/684
