### ISSUE TITLE
The method driver /usr/lib/apt/methods/https could not be found

### ISSUE THREAD

**Issue by freeesty** [bassmaster187/TeslaLogger#692]
**Describe the bug**
docker-compose build fail:

` docker-compose build
Sending build context to Docker daemon     413B
Step 1/5 : FROM mono:5.20.1.34
5.20.1.34: Pulling from library/mono
7d2977b12acb: Pull complete
f3a96016cede: Pull complete
05a6ab00376a: Pull complete
cebe820795cc: Pull complete
Digest: sha256:0912ee40f725f9351eaa9a1f3ec7fbc59dda5f6fbdc6b2eeb664feea13dd2a91
Status: Downloaded newer image for mono:5.20.1.34
 ---> 429edcd2234d
Step 2/5 : RUN echo "Europe/Berlin" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
 ---> Running in ab8ff90356c7

Current default time zone: 'Etc/UTC'
Local time is now:      Thu Nov 18 17:21:46 UTC 2021.
Universal Time is now:  Thu Nov 18 17:21:46 UTC 2021.

 ---> 17c69e08d983
Step 3/5 : RUN apt-get update &&   apt-get install -y --no-install-recommends git &&   apt-get install -y --no-install-recommends mariadb-client &&   apt-get clean &&   apt-get autoremove -y &&   rm -rf /var/lib/apt/lists/* &&   echo "export TERM=xterm" >> /root/.bashrc  &&   echo "DOCKER" >> /tmp/teslalogger-DOCKER
 ---> Running in 7625c75bb1bd
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [53.0 kB]
Get:3 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [3177 B]
Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [743 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [7080 kB]
Reading package lists...
E: The method driver /usr/lib/apt/methods/https could not be found.
...
...
E: The method driver /usr/lib/apt/methods/https could not be found.
1 error occurred:
        * Status: The command '/bin/sh -c apt-get update &&   apt-get install -y --no-install-recommends git &&   apt-get install -y --no-install-recommends mariadb-client &&   apt-get clean &&   apt-get autoremove -y &&   rm -rf /var/lib/apt/lists/* &&   echo "export TERM=xterm" >> /root/.bashrc  &&   echo "DOCKER" >> /tmp/teslalogger-DOCKER' returned a non-zero code: 100, Code: 100`

** Teslalogger Type **
Docker inside of a proxmox container

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

apt-utils is installed and up to date

**Comment by switchdk** [comment]
Hi @freeesty,

I have a hacky solution which will get you up and running. It is not really a proper fix but it will do for now.

Edit the file `docker/teslalogger/Dockerfile` to reflect this for the **# install packages** section
```
# install packages
RUN ln -s /usr/lib/apt/methods/http /usr/lib/apt/methods/https && \
  rm /etc/apt/sources.list.d/mono-official-stable.list && \
  apt-get update && \
  apt-get install -y --no-install-recommends apt-transport-https && \
  apt-get install -y --no-install-recommends git && \
  apt-get install -y --no-install-recommends mariadb-client && \
  apt-get clean && \
  apt-get autoremove -y && \
  rm -rf /var/lib/apt/lists/* && \
  echo "export TERM=xterm" >> /root/.bashrc  && \
  echo "DOCKER" >> /tmp/teslalogger-DOCKER
```
the first four lines are the ones that have been changed.

Once you have saved the file, you can run `docker-compose build` again and it should work.

**Comment by freeesty** [comment]
thanks, seems to work.
But getting other errors afterwards:

```
debconf: delaying package configuration, since apt-utils is not installed
...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
```

building finished anyway, but starting not:

`Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /root/TeslaLogger/TeslaLogger/GrafanaDashboards
`

**Comment by sirathan** [comment]
I had the same error `E: The method driver /usr/lib/apt/methods/https could not be found.` and i used your suggested changes to the Dockerfile and for me it worked. Thank you

**Comment by Obihoernchen** [comment]
Just adding `rm /etc/apt/sources.list.d/mono-official-stable.list && \` before `apt-get update && \` is enough because the mono repository is not used afterwards.

**Comment by freeesty** [comment]
> thanks, seems to work. But getting other errors afterwards:
> 
> ```
> debconf: delaying package configuration, since apt-utils is not installed
> ...
> debconf: unable to initialize frontend: Dialog
> debconf: (TERM is not set, so the dialog frontend is not usable.)
> debconf: falling back to frontend: Readline
> debconf: unable to initialize frontend: Readline
> debconf: (This frontend requires a controlling tty.)
> debconf: falling back to frontend: Teletype
> dpkg-preconfigure: unable to re-open stdin:
> ```
> 
> building finished anyway, but starting not:
> 
> `Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /root/TeslaLogger/TeslaLogger/GrafanaDashboards `

reason for this error is docker-compose v2. if you use latest 1.29.x the error is gone.
