### ISSUE TITLE
(additionally) Split MQTT message into seperate channels

### ISSUE THREAD

**Issue by hakan42** [bassmaster187/TeslaLogger#696]
**Is your feature request related to a problem? Please describe.**

Currently, the MQTT message is one big JSON block, which makes listening to specific events harder than it needs to be as one needs to listen to each and every event coming in, parsing the JSON and disregarding the change if no interesting event occurs.

**Describe the solution you'd like**

The message sent to the topic "Tesla" is "{ "charging": false, "odometer": 4711, ... "car_version": "2021.36.whatever" ... }"

In addition to that message, post messages like:

    Tesla - full message as now, for compatibility
    Tesla/charging - "false"
    Tesla/odometer - "4711"
    Tesla/car_version - "2021.whatever"
    Tesla/another_key_from_message - "something"

**Describe alternatives you've considered**

A listener application that receives the message, seperates it into its parts and reposts it to the MQTT server if and when the value of some key changes. 

**Additional context**

Please see also:

https://github.com/bassmaster187/TeslaLogger/issues/506#issuecomment-930492317

wherein a similiar suggestion has been made

**Comment by Adminius** [comment]
why not to use http instead? you can listen only for relevant topics:
https://github.com/bassmaster187/TeslaLogger/blob/master/TeslaLogger/WebServer.md

**Comment by hakan42** [comment]
HTTP is not appropiate because I would have to open up a connection and keep that open indefinetely. Also, TeslaLogger and consumer can live in seperate networks, allowing for further security. 

MQTT allows me to decouple connectivity (even if it keeps the underlying connection to the MQTT server open, but this is another topic for another day) .

**Comment by Schimi1983** [comment]
Genau das wünsche ich mir auch... wollte schon vor "monaten" einen future request schreiben und habe es immer verschoben....

**Comment by Adminius** [comment]
@hakan42 & @Schimi1983 are you ok with this?
![image](https://user-images.githubusercontent.com/17052262/165390053-dcfaa2e1-7a91-488d-9448-3badc6ea82bd.png)

Main Topic Tesla(-1) stays with full json
sub topics of Tesla(-1) are same keys from json

**Comment by hakan42** [comment]
perfect, thank you 😄
