### ISSUE TITLE
Upgrade Grafana to V8

### ISSUE THREAD

**Issue by hisabimbola** [bassmaster187/TeslaLogger#698]
**Is your feature request related to a problem? Please describe.**
I noticed that grafana mentioned in the docker compose file is a bit out of date now. More than one year. From experience, the longer it is the more difficult it'd be to upgrade later on.

**Describe the solution you'd like**
Update grafana been used to grafana 8

**Describe alternatives you've considered**
Stay on current version but will hit a bump later down the road

**Additional context**
Keine

**Comment by bassmaster187** [comment]
Grafana has deprecated the table plugin but didn't publish all features we need for the new table. 
https://github.com/grafana/grafana/issues/24092

After one year there they released this feature in 8.3.0 but with other bugs.
https://github.com/grafana/grafana/pull/41443#issuecomment-965338766

There is actually a Teslalogger branch using 8.3.0 with all the migrations needed to get it work, but without the new table as mentiond before:
https://github.com/bassmaster187/TeslaLogger/tree/Grafana8.3.0

**Comment by hisabimbola** [comment]
Oh damn, I'll monitor the branch then and hopefully grafana fixes the issue. I'll close this issue then since you're already working on it.
