### ISSUE TITLE
My degradation: data disappeared

### ISSUE THREAD

**Issue by ostorezio** [bassmaster187/TeslaLogger#713]
** Append Logfile **
Not applicable

**Describe the bug**
The "My Degradation" page ( https://teslalogger.de/degradation_token.php?token=xxxxxxxx&car=M3+LR ) does not show my degradation data, the pink dots/line. It used to be OK until a few days ago

**To Reproduce**
Just hit the My Degradation URL

**Expected behavior**
To see BOTH the fleet data AND my car data

**Screenshots**
Here it is: 
<img width="1367" alt="Screen Shot 2021-12-14 at 3 51 21 PM" src="https://user-images.githubusercontent.com/87861096/146022896-a5d5991b-8b74-4768-af91-42f19495042e.png">

** Teslalogger Type **
 Raspberry Pi4 / Docker , Version 1.49.4.0

** Do you use Tasker or iBeacon **

**Additional context**

**Comment by sirathan** [comment]
I have the same issue

**Comment by snookerfly** [comment]
same here since 1.49.4.0 (maybe even 1.49.3.0)

**Comment by brau01ma** [comment]
Same to my both Cars..

**Comment by bassmaster187** [comment]
fixed in 1.50.0
