### ISSUE TITLE
Car position dot disappeared

### ISSUE THREAD

**Issue by ostorezio** [bassmaster187/TeslaLogger#714]
** Append Logfile **
[nohup.out.gz](https://github.com/bassmaster187/TeslaLogger/files/7712891/nohup.out.gz)

**Describe the bug**
In the Grafana pages, the dot showing the car position disappeared

**To Reproduce**
Scroll through the "General / Consumption" graphs

**Expected behavior**
A dot corresponding to gar position is supposed to be located on the map

**Screenshots**
<img width="1628" alt="Screen Shot 2021-12-14 at 4 36 58 PM" src="https://user-images.githubusercontent.com/87861096/146031587-9b8cd26d-94c3-44a9-9c94-3e752e9c9f2b.png">

** Teslalogger Type **
See log file

** Do you use Tasker or iBeacon **

**Additional context**

**Comment by bassmaster187** [comment]
Open Issue on Trackmap Panel:

https://github.com/pR0Ps/grafana-trackmap-panel/issues/67

**Comment by ostorezio** [comment]
OK, I think the bug popped out with Grafana upgrade to 8.3.2, that is, yesterday morning, see below:

ezio@raspberry:/etc/teslalogger $ grep "Grafana Version" nohup.out 
01.12.2021 19:16:35 : Grafana Version: 7.2.0
09.12.2021 00:27:02 : Grafana Version: 7.2.0
09.12.2021 00:29:03 : Grafana Version: 7.2.0
14.12.2021 02:02:52 : Grafana Version: 7.2.0
14.12.2021 02:04:54 : Grafana Version: 7.2.0
14.12.2021 11:03:53 : Grafana Version: 8.3.2
14.12.2021 11:05:53 : Grafana Version: 8.3.2
14.12.2021 16:29:34 : Grafana Version: 8.3.2
15.12.2021 04:55:47 : Grafana Version: 8.3.2
15.12.2021 05:27:37 : Grafana Version: 8.3.2

**Comment by bassmaster187** [comment]
Please update your Teslalogger and check if now everything works as expected.

**Comment by ostorezio** [comment]
What is the fixed Teslalogger version?
I tried the update, but no version changes:

Before update:

15.12.2021 05:27:34 : TeslaLogger Version: 1.49.5.0
15.12.2021 05:27:35 : Teslalogger Online Version: 1.49.5.0
15.12.2021 05:27:35 : Logfile Version: 1.0.12.0
15.12.2021 05:27:35 : SRTM Version: 0.0.4.0
15.12.2021 05:27:37 : Grafana Version: 8.3.2
15.12.2021 05:27:37 : OS Version: RPI4B 1.4 / 4.19.118.7
15.12.2021 05:27:38 : DB Version: 10.3.22-MariaDB-0+deb10u1
15.12.2021 05:27:42 : 15.12.2021 05:27:42 : MqttClient Version: 2.1.0.0

After update:

15.12.2021 11:56:26 : TeslaLogger Version: 1.49.5.0
15.12.2021 11:56:27 : Teslalogger Online Version: 1.49.5.0
15.12.2021 11:56:27 : Logfile Version: 1.0.12.0
15.12.2021 11:56:27 : SRTM Version: 0.0.4.0
15.12.2021 11:56:28 : Grafana Version: 8.3.2
15.12.2021 11:56:28 : OS Version: RPI4B 1.4 / 4.19.118.7
15.12.2021 11:56:29 : DB Version: 10.3.22-MariaDB-0+deb10u1
15.12.2021 11:56:33 : 15.12.2021 11:56:33 : MqttClient Version: 2.1.0.0

**Comment by bassmaster187** [comment]
It is an invisible update. Just check if the issue went away.

**Comment by ostorezio** [comment]
Just tried, unfortunately no dot.
Here's a brief screen recording: https://bbbsw.it/download/GrafanaTrackmap.mov (too big to post here)

**Comment by bassmaster187** [comment]
Did you try to clear browser cache? 

https://youtu.be/NtAFC1vey64

**Comment by ostorezio** [comment]
Cache cleared on Firefox.
No improvements. I will try using a different browser

**Comment by ostorezio** [comment]
Tried also with Safari on Mac.
Cache cleared, no dot on trackmap.

**Comment by ostorezio** [comment]
If you wish to check my system, it is accessible from the Internet.
I can send you the credentials via email

**Comment by ostorezio** [comment]
Gotcha!!!

I checked this commit: https://github.com/bassmaster187/TeslaLogger/commit/c70271391537ab14fc500502c273c1b20664b4e4?diff=split

and noticed that two files have been fixed: trackmap_ctrl.js and trackmap_ctrl.js.map

I X-checked these two file against the ones I have in /var/lib/grafana/plugins/pR0Ps-grafana-trackmap-panel/dist/ and noticed that they have not been updated by the Teslalogger "UPDATE" function.

So I copied the files manually and the fix worked, the dot is back on the screen.
