### ISSUE TITLE
Docker Grafana / Status Dashboard missing Statusinformation

### ISSUE THREAD

**Issue by tscsmith** [bassmaster187/TeslaLogger#716]
Docker Image
After upgrade to the latest release the status dashboard is missing some informations.

Current Status, Firmware, KM

![image](https://user-images.githubusercontent.com/46021479/146203395-fa41c971-91cb-4079-bc48-589be0e387db.png)

**Comment by bassmaster187** [comment]
Fixed in:
https://github.com/bassmaster187/TeslaLogger/commit/92d3e9fc43f366fd3158e6422d02396dc1b2c9b5
