### ISSUE TITLE
M3 SR+ is detected as LR RWD

### ISSUE THREAD

**Issue by brau01ma** [bassmaster187/TeslaLogger#717]
Mein neues M3 SR+ 60kwh wird von Teslalogger als LR RWD erkannt.

`15.12.2021 19:24:20 : #2: Voltage at 50% SOC:0V Date:12/15/2021 4:47:17 PM
15.12.2021 19:24:22 : #2: Car: M3 LR RWD - 0.145 Wh/km
15.12.2021 19:24:22 : #2: VIN decoder: Model 3 2021 AWD:False MIC:True battery:LFP motor:3 single
15.12.2021 19:24:22 : #2: Vehicle Config: car_type:'model3' car_special_type:'base' trim_badging:'50'

15.12.2021 19:24:13 : #2: vin: LRW3E7FA3MCXXXXXX`

**Comment by brau01ma** [comment]
my Teslalogger is running on 1.49.2.0

**Comment by bassmaster187** [comment]
Fixed in next version

**Comment by brau01ma** [comment]
Ich habe ein Update durchgeführt, leider keine Änderung bisher..
