### ISSUE TITLE
Eigene Degradation wird in der Fleet Statistic wird nicht mehr angezeigt.

### ISSUE THREAD

**Issue by Onkel-Tomm** [bassmaster187/TeslaLogger#720]
Eigene Degradation wird in der Fleet Statistic wird nicht mehr angezeigt.
Die rosa Punkte und die Linie sind in der Statistik nicht mehr sichtbar.
Die grauen Punkte  und die blaue Linie für den Durchschnitt werden noch angezeigt.

**Comment by bassmaster187** [comment]
duplicate of: #713
