### ISSUE TITLE
How to add second car linked to the same account?

### ISSUE THREAD

**Issue by SandeepNadella** [bassmaster187/TeslaLogger#721]
I generated the refresh and access tokens and tried to add the cars. I was able to add the first car linked to my account. However, I want to second car linked to my account as well. How can I do that? I tried by it adds the first car again.

**Comment by panaut0lordv** [comment]
What index (Tesla account car position) are you specifying? Can we have a look at logs around the timestamp you were trying to add it?

**Comment by bassmaster187** [comment]
Should be much easier with new version because you can select your car now by a combobox:

Check: https://youtu.be/32AmSac226I

https://github.com/bassmaster187/TeslaLogger/commit/0c6d3177b84545a3bbb0d3282c808e467334ca2e
