### ISSUE TITLE
Daily backup of Teslalogger in docker version

### ISSUE THREAD

**Issue by sirathan** [bassmaster187/TeslaLogger#723]
The raspberry image creates an automatic daily backup of the database and the private geofence. The docker version does only support backup on manual request or by executinng "docker exec -ti teslalogger_teslalogger_1 /etc/teslalogger/backup.sh". 

It would be nice to have a solution which automatically creates a daily backup to a persisted directory.

**Comment by nanourbina** [comment]
You can easily add a crontab entry to do :-).

**Comment by FlorianAlexander** [comment]
the location of the backup.sh has changed to /home/[username]/TeslaLogger/TeslaLogger/bin/backup.sh

**Comment by bassmaster187** [comment]
It works. 
![image](https://github.com/bassmaster187/TeslaLogger/assets/6816385/a122f3d4-429a-4966-ac26-55cbc624a81d)

**Comment by mkoegel** [comment]
@bassmaster187 Funktioniert prima, nur läuft mir jetzt mit den vielen Backups die SD Karte voll.
Gibt es eine Möglichkeit alte Backups nach einer gewissen Zeit automatisch wieder zu löschen oder nur eins pro Monat aufzuheben?

**Comment by rowich** [comment]
Wir arbeiten an einer Lösung, die Backup-Files aufzuräumen. Ein erster Commit dazu liegt vor (der räumt mal alles ab, was älter als ein Jahr ist und markiert monatliche Sicherungen, so dass auch dort mehr abgeräumt werden kann (keine Tagesdateien vom Vormonat). Braucht eventuell noch ein wenig Fine-Tuning, aber ist unterwegs.
