### ISSUE TITLE
Exceptionless - Opt out

### ISSUE THREAD

**Issue by devmarxx** [bassmaster187/TeslaLogger#749]
Is it possible to opt out from taking part in "Exceptionless" via the UI?

If not, could it be an idea to add a selection box for such a feature under "Settings"?

Regards

Chris

**Comment by ThmsD** [comment]
As far as I know, there is currently no option to opt out.
Exceptionless is used to find errors in the program. No personal data is collected, so its use will only provide a better user experience in the end.

**Comment by bassmaster187** [comment]
Edit your config File "TeslaLogger.exe.config"

after EndTag of appclicationSettings insert a tag for exceptionless and disable it:

```
...
  </applicationSettings>
  <exceptionless apiKey="Fr6JebtLWFka4nFwGXSkZAYEXIKCXn6AYGJb1mzt"  enabled="false"  />
```

check: https://exceptionless.com/docs/clients/dotnet/configuration/
