### ISSUE TITLE
adding Keba Wallboxes

### ISSUE THREAD

**Issue by satip** [bassmaster187/TeslaLogger#761]
Enhancement:

it would be nice, if TL suppots more Wallboxes:
https://github.com/bassmaster187/TeslaLogger/blob/master/wallbox.md

iam using a Keba KeConntact P30 Wallbox and it is working fine with integration in Loxone:
![grafik](https://user-images.githubusercontent.com/17120775/158058756-77519776-b82e-4c15-ab8e-9275131cfb41.png)

THX

**Comment by bassmaster187** [comment]
Implemented in: https://github.com/bassmaster187/TeslaLogger/pull/772

Please give it a try
