### ISSUE TITLE
Dashboard empty after selling car

### ISSUE THREAD

**Issue by hisabimbola** [bassmaster187/TeslaLogger#784]
** Append Logfile **
you find it here: \\raspberry\teslalogger\nohup.out

**Describe the bug**
I recently sold my tesla and I transferred the car from the tesla web dashboard and also deleted the car in the admin settings. Now I can't see anything in the grafana dashboards. I'll like to be able to still see the history data of the car and be able to compare with my new car when I get it. 

**To Reproduce**

**Expected behavior**

**Screenshots**

** Teslalogger Type **
Raspberry PI 3 / Raspberry Pi4 / Docker / Selfmade
Did you update the Image with apt-get update & upgrade?

** Do you use Tasker or iBeacon **

**Additional context**

**Comment by Adminius** [comment]
If will see the car data, you are not allowed to delete it ;)
Try to restore backup before you deleted the car.

**Comment by hisabimbola** [comment]
Sadly, I do not have a backup before deleting 😭

**Comment by Adminius** [comment]
try some DB viewer, like HeidiSQL or phpMyAdmin and look for carID column in the tables. If old data is still there, you can "copy" new car in car table and edit it to match old carID and old car.
but DO BACKUP first ;)

**Comment by hisabimbola** [comment]
I saw that I have backups so I restored that. Thanks for your help @Adminius
