### ISSUE TITLE
teslalogger.de returning http 408

### ISSUE THREAD

**Issue by marki555** [bassmaster187/TeslaLogger#787]
Anyone else having issues with teslalogger.de website returning HTTP error 408 (Resource Limit Is Reached)? It seems to be affecting also the functionality of my docker instance of TeslaLogger (which also shows http 408 errors in its logfile). I tried accessing the website from multiple locations and I think it started already on Friday...

**Comment by bassmaster187** [comment]
I aware of this problem. My webhoster is not able to handle requests from almost 3000 Teslalogger. I'm about to setup a new root server.

**Comment by marki555** [comment]
Thanks for the quick response. I guess it does not make sense to try the ScanMyTesla integration until that is done...

**Comment by bassmaster187** [comment]
teslalogger.de is now on a root server.

**Comment by rowich** [comment]
"This is a problem you can throw money on"

seriously: another sponsoring round required?

Am 24.04.2022 um 20:34 schrieb Christian P.:
