### ISSUE TITLE
Question: send personal data to teslalogger.de?

### ISSUE THREAD

**Issue by ghostreader86** [bassmaster187/TeslaLogger#79]
Hi,

quick question:
I wonder why you send personal data of the users to your http://teslalogger.de server, see [WebHelper.cs](https://github.com/bassmaster187/TeslaLogger/blob/master/TeslaLogger/WebHelper.cs).
Version of TaskerLogger (`d.Add("v", System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString());`) is fine for your logging, compare #39, but why 

```
d.Add("t", TaskerHash);

d.Add("cv", DBHelper.currentJSON.current_car_version);
d.Add("m", carSettings.Model);
d.Add("bt", carSettings.Battery);
d.Add("n", carSettings.Name);
d.Add("eff", carSettings.Wh_TR);
d.Add("oc", option_codes);

d.Add("db_eff", carSettings.DB_Wh_TR);
d.Add("db_eff_cnt", carSettings.DB_Wh_TR_count);

d.Add("pw", power);
d.Add("temp", temperature);
d.Add("le", length);
d.Add("ln", language);
```

Either I do not understand it correctly or you want to have an overview who is using your tool with details you do not need to know. 

From what i understood your motivation is to not trust any webservice, so why collecting personal data on your own?

Please get me correctly, i appriciate your work and approach and really want to use it as soon as my Tesla is delivered. I know I can configure it that there is no data push to your site.

Regards
GhostReader

**Comment by ghostreader86** [comment]
even worse, in `TaskerHash` there is the VIN encoded

**Comment by bassmaster187** [comment]
As I don't get the consumption trough the API, I have to calculate it backwards from the loose of typical rage. Therefore, I need the Model / Battery / Type / and option_codes / db_eff / db_eff_cnt. 
With these data it was possible to calculate how much Wh 1 km is: 

`private void UpdateEfficiency()
        {
            string eff = "0.190052356";
            string car = "";

            if (carSettings.Model == "MS")
            {
                if (carSettings.Battery == "BTX5")
                {
                    if (carSettings.AWD)
                    {
                        eff = "0.186";
                        car = "S 75D";
                    }
                    else
                    {
                        eff = "0.185";
                        car = "S 75";
                    }
                }
                else if (carSettings.Battery == "BTX4")
                {
                    if (carSettings.Performance)
                    {
                        eff = "0.200";
                        car = "S P90D";
                    }
                    else
                    {
                        eff = "0.189";
                        car = "S90D";
                    }
                }
                else if (carSettings.Battery == "BTX6")
                {
                    if (carSettings.Performance)
                    {
                        eff = "0.200";
                        car = "S P100D";
                    }
                    else
                    {
                        eff = "0.189";
                        car = "S 100D";
                    }
                }
                else if (carSettings.Battery == "BTX8")
                {
                    if (carSettings.AWD)
                    {
                        eff = "0.186";
                        car = "S 75D (85kWh)";
                    }
                    else
                    {
                        eff = "0.185";
                        car = "S 75 (85kWh)";
                    }
                }
                else if (carSettings.Battery == "BT85")
                {
                    if (carSettings.AWD)
                    {
                        if (carSettings.Performance)
                        {
                            car = "S P85D";
                            eff = "0.201";
                        }
                        else
                        {
                            car = "S 85D";
                            eff = "0.186";
                        }
                    }
                    else
                    {
                        if (carSettings.Performance)
                        {
                            car = "S P85";
                            eff = "0.210";
                        }
                        else
                        {
                            car = "S 85";
                            eff = "0.201";
                        }
                    }
                }
                else if (carSettings.Battery == "PBT85")
                {
                    car = "S P85";
                    eff = "0.210";
                }
                else if (carSettings.Battery == "BT70")
                {
                    car = "S 70 ?";
                    eff = "0.200";
                }
                else if (carSettings.Battery == "BT60")
                {
                    car = "S 60 ?";
                    eff = "0.200";
                }
                else
                {
                    car = "S ???";
                    eff = "0.200";
                }
            }
            else if (carSettings.Model == "MX")
            {
                if (carSettings.Battery == "BTX5")
                {
                    eff = "0.208";
                    car = "X 75D";
                }
                else if (carSettings.Battery == "BTX4")
                {
                    if (carSettings.Performance)
                    {
                        eff = "0.208";
                        car = "X 90D";
                    }
                    else
                    {
                        eff = "0.217";
                        car = "X P90D";
                    }
                }
                else if (carSettings.Battery == "BTX6")
                {
                    if (carSettings.Performance)
                    {
                        eff = "0.226";
                        car = "X P100D";
                    }
                    else
                    {
                        eff = "0.208";
                        car = "X 100D";
                    }
                }
                else
                {
                    car = "X ???";
                    eff = "0.208";
                }

            }
            else if (carSettings.Model == "M3")
            {
                if (carSettings.Battery == "BT37")
                {
                    if (carSettings.Performance)
                    {
                        eff = "0.153";
                        car = "M3P";
                    }
                    else
                    {
                        eff = "0.153";
                        car = "M3";
                    }
                }
                else
                {
                    eff = "0.153"; 
                    car = "M3 ???";
                }
            }
            else
            {
                if (carSettings.Battery == "BT85")
                {
                    car = "S 85 ?";
                    eff = "0.200";
                }
            }

            if (carSettings.Name != car || carSettings.Wh_TR != eff)
            {
                carSettings.Name = car;
                carSettings.Wh_TR = eff;
                carSettings.WriteSettings();
            }
        }`

power (unit), temperature (unit), length (unit) and language are just statistics for me to know if it's worth to spend more time in these particular topics or is a waste of time. 

The VIN with the E-Mail as a cryptographic salt is used to compute a hash for tasker app. It is absolutely not possible to restore either the VIN nor the e-mail trough the hash. 
https://en.wikipedia.org/wiki/Cryptographic_hash_function

I don't collect any personal data nor I'm interested in getting personal data. 

For reverse geocoding (get street names from latitude / longitude) there will be send personal data (position) to openstreetmap (nominatim).
