### ISSUE TITLE
Problem between Mariadb / RPI3B + / ARMV7L to install Teslalogger

### ISSUE THREAD

**Issue by Lionel26** [bassmaster187/TeslaLogger#799]
Having an RPI3B+ Qur which is installed Teslamate, and which works perfectly well, I now wanted to install Teslalogger on this RPI, since I saw that it is possible to install it on the RPI 3; 3B, 3B+, 4, with Docker.
So I followed the Bassmaster 187 procedure, and arrived at the end of the procedure I have the following 3 lines:
Pulling database (mariadb:10.4.7)...
10.4.7: Pulling from library/mariadb
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

I understand that as Bassmaster187 mentioned, Mariadb is not compatible with ARMV7L because system 32bits ... How is it that it is said to install it on different RPIs, including 3B+ (therefore Armv7l ), but that in the end it does not work because for Mariadb you need a 64bits system?

Does anyone have the solution to get around this problem? Knowing that I have already teslamate which turns on this RPI3B+ ARMV7L with Docker.

**Comment by bassmaster187** [comment]
Docker on Raspberry:
As the official MariaDB Docker image is not supporting 32Bit OS, it seems like there are only 2 changes necessary to run it on a Raspberry.

Original:
database:
image: mariadb:10.4.7
New:
database:
image: jsurf/rpi-mariadb

please let me know if it works

**Comment by Lionel26** [comment]
Thank you very much for your help, thank you thank you! I got back there 2 times. The first time it blocked here:
"Creating teslalogger_grafana_1 ... error
Warning: Host is already in use by another container "
Because I already have in a Grafana container in Port 3000 for Teslamate. So I modified the Docker-compose.YML by putting Ports 3010: 3000 in Grafana. With this other modification, everything seems to have settled well, I have access to Grafana, without dashboards for the moment, I think it's normal.
I also have access to Teslalogger by doing "http://myadressip:8888/admin"
But I have this error message by going in the settings:
"errortext = 'Error: php_network_getaddresses - URL: http://teslalogger:5000/getallcars'"
I see the parameters, but by clicking on "Credentials", I get a blank page with the same error message ...
Do you have an idea what's going on?
Thank you again for the help

**Comment by Lionel26** [comment]
After having insisted a lot, does and redo the manipulations, this time all like to work. The car being asleep, I will see more tomorrow. In the meantime I'm going to fall asleep too ...
Thank you again for the help, I will tell you later if everything is working properly
