### ISSUE TITLE
Option to open chargeport automatically on all superchargers

### ISSUE THREAD

**Issue by HanSolo72** [bassmaster187/TeslaLogger#800]
I suggest an option to open the charge port automatically at all superchargers, so I do not have to copy & paste all superchargers from geofence.csv to my persconal geofence file and add the option +ocp:R->P at each supercharger.

**Comment by Adminius** [comment]
Is it really a good idea?
Example:
somebody drives old Model S without auto-close charge port.
This user drives to a location with some grocery stores but also with a SuC and do not want to charge... Charge port will be opened anyway but not closed

So, this option can't be enabled per default.

**Comment by HanSolo72** [comment]
@Adminius: I didn't wrote it should be default, just an option that everyone who wants that feature can enable it. That's all. Some who drives an old Model S didn't have to enable this function.

@ThmsD: What are the disadvantages? Why is that option available at Geofence when it has disadvantages?

**Comment by ThmsD** [comment]
E.g., coming to a fully occupied supercharger.

**Comment by Adminius** [comment]
> just an option

that makes it more complex

**Comment by HanSolo72** [comment]
> that makes it more complex

More complex than the current geofence window?

**Comment by HanSolo72** [comment]
> E.g., coming to a fully occupied supercharger.

Like in Geofence, the option should look like in geofence D/R -> P, D -> P, R -> P. And also: Yo don't have to enable it if you don't want it. No disatvantage for you.

And why this function was added to geofence in the first place?

**Comment by Adminius** [comment]
> More complex than the current geofence window?

yes. Window you mean is only for private-gefonce and not for general.
What you want is setting for all Superchargers, that means, we have to write completly new logic on completely new place.

> Like in Geofence, the option should look like in geofence D/R -> P, D -> P, R -> P
How can It help on fully ocupied SuC?
1. each SuC is different. In most R->P would work, but not all.
2. I can also park with R->P to wait for a free spot and geofence radius is about 50m on most places...

> And why this function was added to geofence in the first place?
Why not? ;) For example for your home charger. You park always in a same way on a known place.

**Comment by HanSolo72** [comment]
Ok, looks like no one is interested in this suggestion so I close it.
