### ISSUE TITLE
Direct ScanMyTesla connection

### ISSUE THREAD

**Issue by flosoft** [bassmaster187/TeslaLogger#813]
**Is your feature request related to a problem? Please describe.**
Currently using ScanMyTesla requires the data to be sent to teslalogger.de and then forwarded on to the TeslaLogger instance.

**Describe the solution you'd like**
It would be great to be able to have support for direct ingestion from ScanMyTesla, without sending data through teslalogger.de, assuming that the mobile device running ScanMyTesla has direct access to TeslaLogger (HTTP(S)) - i.e. reverse proxy, exposed port or VPN.

**Comment by bassmaster187** [comment]
To help keep the connection problems very low we decided not to offer a direct connection. So we can get rid of question like:
- how can I configure my router?
- how to get a certificate
- why don't I get any data
- why is Netflix stutter now
- why....

It is very common to have a proxy server if two clients are behind a router / firewall. Any chat client like Whatsapp or Teamviewer are using proxy server.

**Comment by flosoft** [comment]
agreed that this shouldn't be the default approach, but it would be nice to have the option, even if it requires some more manual configuration.
