### ISSUE TITLE
Installation in VM

### ISSUE THREAD

**Issue by nikolauskrismer** [bassmaster187/TeslaLogger#83]
Hi,

first and most important I want to say a big THANK YOU.
The project you implemented is really useful and due to its handbook also very well documented (ok... in german, which might be a but unusual for a development project... but I can deal with that).

I installed your logger into an ubuntu vm.
Without major issues I was able to get everything up and working.
One minor issue is, that in my version of grafana the map plugin is now called pr0ps-trackmap-plugin instead of grafana-trackmap-plugin... maybe you want to change that also for raspberry installations, so that newer version of the plugin (and maybe even grafana itself) can be used...

However, I do have one question:

I first checked out teslalogger to "/opt"...
On the first start all files were copied other locations (www into /var/www/html, rest to /etc/teslalogger).
I guess that I now should start teslalogger from /etc/teslalogger, right?
At least that's what the admin panel indicates, since it writes files into /etc/teslalogger.
My problem now is that in that directory the MySQL definition files are missing, so teslalogger won't start up if I execute it from there.
If I start it from /opt/Teslalogger/Teslalogger everything works out well, but then the admin panel changes are not regarded. Even worse, the android tasker task does not help at all, since the wakeupfile is written to /etc/Teslalogger (and I do not know if linking files helps in that case...)

Can you please give me some insights on how the installation should look like (or update your documentation to reflect a bit more details on how an installations on a common OS would look like...).

Thanks in advance,
Niko

**Comment by bassmaster187** [comment]
Teslalogger should be placed to 
/etc/teslalogger

admin page in /var/www/html

we are actually making a dockerfile. Take a look in "docker" branch. You will find almost everything you need there. We have also problems with trackmap panel, but I actually don't want to update to the latest Grafana / Trackmap Panel, because there is a big bug there: https://github.com/pR0Ps/grafana-trackmap-panel/issues/16

**Comment by rowich** [comment]
Niko

You are right, a german documentation seems to be a little bit weird,
but at time of writing, *all* was german only.
I can confirm, I have an international/english language handbook on my
todo list together with updates to the latest features and iOS hints for
wakeup.

Cheers
  Rolf.

Am 29.08.2019 um 18:22 schrieb Nikolaus Krismer:

**Comment by nikolauskrismer** [comment]
@bassmaster187:
Thanks... that helped a lot. I just linked the MySQL dll (and also the other missing dlls) into /etc/teslalogger from the git repository (also located somewhere within /etc/teslalogger) and now I think it should work as it should. Thanks!
