### ISSUE TITLE
Logging starts extremely late

### ISSUE THREAD

**Issue by Scotty1928** [bassmaster187/TeslaLogger#834]
Hey everyone,

I recently discovered that logging starts extremely late, so much that it does not log most of local commutes of several kilometers. before, i had temporarily enabled "Position by StreamingAPI" for a few days to test. after i disabled this i did not check again until last week, where i added a second car, a MIC Y LR, where i discovered the issue, which seems to be happening for both vehicles.

Unfortunately, i cannot provide steps to reproduce, other than suggesting it might have to do with disabling said "Position by StreamingAPI", of which i am unsure to be the cause.

Before, logging started pretty much within a few hundred meters of my parking garage, which would represent a driving time of less than two minutes until logging started. Now, even longer drives of 20 minutes go unlogged in roughly half the cases.

I'm using the Raspberry i bought as a finished product from e-mobility driving solutions. I did not ssh into the device, ever. Updates are automated or sometimes started via the admin web interface.

Tasker is, technically, enabled, but has not been used for months or even years.

Thank you all in advance!

[nohup.log](https://github.com/bassmaster187/TeslaLogger/files/9062984/nohup.log)

**Comment by Scotty1928** [comment]
That i cannot confirm. I usually have quite a fast response when changing anything via App.

**Comment by Scotty1928** [comment]
It seems to get worse: Of almost 250km, yesterday only 5 or 6 got logged. :/

**Comment by bassmaster187** [comment]
It seems like you are affected by server timeouts. Could you please try this: https://github.com/bassmaster187/TeslaLogger/blob/master/docs/en/faq.md#teslalogger-keep-loosing-connection-to-tesla-server

**Comment by ThmsD** [comment]
> It seems like you are affected by server timeouts. Could you please try this: https://github.com/bassmaster187/TeslaLogger/blob/master/docs/en/faq.md#teslalogger-keep-loosing-connection-to-tesla-server

I'm going to try this as well. But I'm the only person who has access to the car via app and TeslaLogger is the only external service that uses the Tesla API.

**Comment by Scotty1928** [comment]
So after roughly three weeks of testing i can say it was significantly better. A few days after this, Tesla replaced the modem, and since that point it's almost flawless! 

Thank you

**Comment by ThmsD** [comment]
@Scotty1928 How did you get Tesla to replace the modem?

**Comment by Scotty1928** [comment]
Told them i had connectivity issues - which i actually had - and it was shortly before the 80'000km warranty end.

My car took quite long to find a cell network when leaving areas without service...
