### ISSUE TITLE
Grafana parallel function with teslamate on Docker containers

### ISSUE THREAD

**Issue by papakwstas** [bassmaster187/TeslaLogger#838]
Hi 

i have installed teslamate on docker and works ok. I installed another container with teslalogger. Changed teslalogger.exe.config file for grafana port as "6000:6000". There is no error as i see. 

The problem is that when i try to load http://localhost:6000 i get an empty page!

can you advise please?

thanx

**Comment by bassmaster187** [comment]
could you please post your docker file and teslalogger.exe.config

**Comment by papakwstas** [comment]
Hi and thanks for reverting, 

after great research i found that the correct syntax is "6000:3000" so that the port of the site is eventually 6000.
