### ISSUE TITLE
Negative EndRange

### ISSUE THREAD

**Issue by parapluplu** [bassmaster187/TeslaLogger#84]
The following SQL statement can produce a negative `EndRange `(named in Grafana `TR km Ende`)
https://github.com/bassmaster187/TeslaLogger/blob/6ead99dcd0c24b634165091f121bca1a65c30b90/TeslaLogger/Grafana/Vampir%20Drain.json#L247

For some reason I have a `TP2.odometer=0`

I used the following SQL statement to further debug the problem (same as the one linked above, but just displaying more values and human readable dates) - also important is the where clause `TP2.odometer - TP1.odometer < 0`:

```sql
SELECT T1.EndDate as StartDate, TP1.address as Adresse, 
T2.StartDate as EndDate, T2.StartPos as EndPos, TP2.odometer, TP1.ideal_battery_range_km as StartRange,  TP2.ideal_battery_range_km + (TP2.odometer - TP1.odometer) as EndRange,
TP1.ideal_battery_range_km - (select EndRange) as RangeDiff,
timestampdiff(MINUTE, T1.EndDate, T2.StartDate) / 60 as TimeDiffHours,
(select RangeDiff / TimeDiffHours) as RangeLostPerHour,
(SELECT sum(TIMESTAMPDIFF(MINUTE,StartDate,EndDate) / 60) FROM teslalogger.state where state = 'asleep' and StartDate >= T1.EndDate and EndDate  <= T2.StartDate) as sleephours,
(select sleephours / TimeDiffHours * 100) as sleeppercent,
TP1.odometer as tp1odo,
TP2.odometer as tp2odo,
T2.StartPos as t2startpos,
TP1.ideal_battery_range_km as tp1ibr,
TP2.ideal_battery_range_km as tp2ibr
FROM drivestate as T1 
left outer join drivestate as T2 on T1.id + 1 = T2.id 
left outer Join pos as TP1 on T1.EndPos = TP1.id 
left outer join pos as TP2 on T2.StartPos = TP2.id
where TP1.ideal_battery_range_km - TP2.ideal_battery_range_km >= 0 and timestampdiff(MINUTE, T1.EndDate, T2.StartDate) > 60 and TP2.odometer - TP1.odometer < 0
```

The output is:

---
| StartDate | Adresse | EndDate | EndPos | odometer | StartRange | EndRange | RangeDiff | TimeDiffHours | RangeLostPerHour | sleephours | sleeppercent | tp1odo | tp2odo | t2startpos | tp1ibr | tp2ibr | 
| - | - | - | -: | -: | -: | -: | -: | -: | -: | -: | -: | -: | -: | -: | -: | -: | 
| 2019-08-23 18:03:09 | Kirberg | 2019-08-24 08:32:31 | 20505 | 0 | 339.604422485798 | -12905.441669214753 | 13245.046091700551 | 14.4833 | 914.5026070429495 | \N | \N | 13239.5260311891 | 0 | 20505 | 339.604422485798 | 334.084361974347 | 

I'm not sure if the issue is that `TP2.odomoter=0` and how that can happen.

**Comment by pbertra** [comment]
I also so add a few (6) odometer 0 values in the pos table causing strange values in the grafana interface. These entries were in three distinct trips but 4 were consecutive in a same trip.
I fixed them manually but I will monitor this to see if new 0 values appear.
I any case, if we get a 0 value from the API, I guess the entry should be discarded.

**Comment by bassmaster187** [comment]
done
