### ISSUE TITLE
Language support bug

### ISSUE THREAD

**Issue by AnnihilaT** [bassmaster187/TeslaLogger#85]
All strings which contain more than a single word are not properly translated.  See snippet attached.

![tempsnip](https://user-images.githubusercontent.com/29304509/65369963-22293400-dc54-11e9-8ea4-d0480dafbdae.png)

When a string contains 2 words the non-german text is concatenated to the end of the original german text.

**Comment by bassmaster187** [comment]
Please update, even if it seems like there is no update.
