### ISSUE TITLE
Admin panel URL admin panel proposal - enhancementrequest

### ISSUE THREAD

**Issue by endurance1968** [bassmaster187/TeslaLogger#86]
Looks like that the admin panel proposal always http://rasberry/admin this could be improved by using the hostname in case user changed the hostname instead of hardcoded? name.

**Comment by rowich** [comment]
The "real" URL of the admin panel can be adjusted via the "Settings" menu. This URL is also used to add new private "Geofence" locations. Not an issue from my point of view. The conclusion from the local hostname to the real URL cannot be done, if, for example, a DNS CNAME is used.

**Comment by endurance1968** [comment]
It is not an real issue - right. But just not nice and easy to further improve make it more error prone.
That it can be changed I know since I am writing exactly about the edit box where you should enter the URL.
