### ISSUE TITLE
teslalogger_webserver_1 listen tcp4 0.0.0.0:8888: bind: address already in use

### ISSUE THREAD

**Issue by atlynch61** [bassmaster187/TeslaLogger#865]
I am running in docker on Synology:  How do I change the port in use?

**Comment by bassmaster187** [comment]
edit your docker-compose.yml file and change port 8888 of your webserver to whatever you want.

....
webserver:
    build: docker/webserver/.
    restart: always
    volumes:
      - ./docker/webserver/php.ini:/usr/local/etc/php/php.ini
      - ./TeslaLogger/www:/var/www/html
      - ./TeslaLogger/bin:/etc/teslalogger
      - ./docker/teslalogger/Dockerfile:/tmp/teslalogger-DOCKER
      - ./TeslaLogger/GrafanaConfig/datasource.yaml:/tmp/datasource-DOCKER
      - teslalogger-tmp:/tmp/
    ports:
      - **8888**:80
    environment:
      - TZ=Europe/Berlin
 ....
