### ISSUE TITLE
Supercharger usage in Grafana non available for many SuC out of Germany

### ISSUE THREAD

**Issue by robi59italy** [bassmaster187/TeslaLogger#869]
** Append Logfile **
you find it here: \\raspberry\teslalogger\nohup.out

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Teslalogger Type **
Raspberry PI 3 / Raspberry Pi4 / Docker / Selfmade
Did you update the Image with apt-get update & upgrade?

** Do you use Tasker or iBeacon **

**Additional context**

**Comment by Adminius** [comment]
Are you sharing the data?

**Comment by HanSolo72** [comment]
Isn't the charging session logged or do you just miss the label "Supercharger"? If the second, the file https://github.com/bassmaster187/TeslaLogger/blob/master/TeslaLogger/bin/geofence.csv has to be updated with those superchargers. As of now, Arezzo and Aosta are included in that file.
