### ISSUE TITLE
Initial Values of admin page last trip

### ISSUE THREAD

**Issue by endurance1968** [bassmaster187/TeslaLogger#87]
Looks like the initial value of trip duration is not set to 0 which it should in case no drive recorded so far.

> Letzter Trip
> --
> Start: | 00:00
> Dauer: | **_35791394:07 min_**
> Distanz: | 0 km
> Verbrauch: | 0 kWh
> Ø Verbrauch: | 0 Wh/km
> Max km/h / PS: | 0 km/h / 0 PS

**Comment by bassmaster187** [comment]
done
