### ISSUE TITLE
Setup in English but still German words

### ISSUE THREAD

**Issue by NyLan-1** [bassmaster187/TeslaLogger#871]
** Append Logfile **
you find it here: \\raspberry\teslalogger\nohup.out
[nohup.zip](https://github.com/bassmaster187/TeslaLogger/files/9699068/nohup.zip)

**Describe the bug**
In Teslalogger Dashboard, the sentence is in German.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50555264/193624129-35956516-e2f8-404c-b70b-02a30b7fc0a9.png)

** Teslalogger Type **
Raspberry PI 3 / Raspberry Pi4 / Docker / Selfmade
Did you update the Image with apt-get update & upgrade?

** Do you use Tasker or iBeacon **

**Additional context**

**Comment by NyLan-1** [comment]
I manually modified [TeslaLogger/www/admin/dashboard.php]
from 
$('#car_statusLabel').text("<?php t("Wird geladen"); ?>:");
to
$('#car_statusLabel').text("<?php t("Charging"); ?>:");

I can't tell if it's a clean way to modify the code, but at least it's correctly displayed in english on my dashboard

**Comment by NyLan-1** [comment]
Still not fixed. Last update reverted my modification. Had to do it again.

**Comment by HanSolo72** [comment]
> Still not fixed. Last update reverted my modification. Had to do it again.

Should be fixed. Please check and close this issue.
