### ISSUE TITLE
Wrong location at charging session

### ISSUE THREAD

**Issue by mkhlzhr** [bassmaster187/TeslaLogger#873]
I've on charging session and the location is wrong.
How can I change the location of a charging session and set the correct location?

**Comment by mkhlzhr** [comment]
Does somebody know how I can change a location of a charging session? Teslalogger has taken the previous location of my M3 for a charging session.

**Comment by mkhlzhr** [comment]
Hello, can someone please let me know if there is a way to change a location of a charging session?

**Comment by bassmaster187** [comment]
It's only possible in the database with tools like MySQL Workbench

**Comment by mkhlzhr** [comment]
But home can I Access? Can I install MySQL Workbench on my PC and access to the database using the IP of my Teslalogger? Which is the user and password?

**Comment by bassmaster187** [comment]
User:  root
Password: teslalogger

**Comment by mkhlzhr** [comment]
Thanks. I just changed the POS for one carging session and it worked.

If I would like to delete some Visited places. Can this be done?

**Comment by bassmaster187** [comment]
Yes, you can do it as well.
