### ISSUE TITLE
Charging costs are not copied automatically

### ISSUE THREAD

**Issue by mkhlzhr** [bassmaster187/TeslaLogger#895]
**Describe the bug**
Since the last update of Teslalogger the charging costs are not copied automatically for each charging sessión.

**Comment by superfloh247** [comment]
fixed next release https://github.com/bassmaster187/TeslaLogger/commit/965690d0cb9ab126b6cf79085a24f50eda4590d3

**Comment by bassmaster187** [comment]
@mkhlzhr is the issue solved with the new update?

**Comment by sunfreak** [comment]
I had the same issue and it was fixed with 1.54.5.0. Many thanks!
