### ISSUE TITLE
Can't update car-tokens after changing tesla-account-password

### ISSUE THREAD

**Issue by Bankaifan** [bassmaster187/TeslaLogger#915]
** Append Logfile **
[logfile (1).zip](https://github.com/bassmaster187/TeslaLogger/files/10424921/logfile.1.zip)

**Describe the bug**
I had to change my account-password.
After that, i have to recreate the access-tokens (as far, as i know). 
I try to put in the new access- and refresh-token, click ok, select the car and click save. 
A message pops up, to look at the logfile

**To Reproduce**
1) Change account password at tesla.com
2) Create new tokens with Auth for Tesla
3) Edit existing car in teslalogger-settings
4) Put in the new tokens
5) Select car from dropdown-menu
6) Save

**Expected behavior**
New token should be saved and cardata being collected and save to existing db

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/476059/212659226-41ccb339-fd9b-4c68-9e93-b800bf6d4a24.png)

** Teslalogger Type **
Raspberry Pi4 / Docker
Did you update the Image with apt-get update & upgrade?
Yes

** Do you use Tasker or iBeacon **
No

**Additional context**
-

**Comment by bassmaster187** [comment]
Should be fixed in new version

**Comment by Bankaifan** [comment]
Lost one week of data (was my fault - haven't created a backup before i did the first try) but it worked perfectly now! Thanks @bassmaster187
