### ISSUE TITLE
DBCONNECTION Table 'teslalogger.pos' doesn't exist in engine

### ISSUE THREAD

**Issue by mikealanni** [bassmaster187/TeslaLogger#923]
Please help, my Tesla logger stoped  working

Error
DBCONNECTION Table 'teslalogger.pos' doesn't exist in engine

**Comment by bassmaster187** [comment]
could you please try to update your Teslalogger? If that doesn't work after reboot, please send me a logfile.

**Comment by mikealanni** [comment]
I did fixed as I found a back and restore it. Thank you!

**Comment by Shrekmachine** [comment]
Ich habe gerade mit vielen umwegen und hängen auf meinem Ugreen Nas TeslaLogger im Docker installiert. 
Jetzt komme ich nicht mehr weiter. Die Fehlmeldung vom Teslalogger Log lautet:
30.12.2025 12:11:53 : DB Version: 10.4.7-MariaDB-1:10.4.7+maria~bionic
30.12.2025 12:11:53 : DBCONNECTION Table 'teslalogger.pos' doesn't exist

MariaDB [teslalogger]> SHOW TABLES;
+--------------------------------+
| Tables_in_teslalogger          |
+--------------------------------+
| active_route_energy_at_arrival |
| can                            |
| car_version                    |
| cars                           |
| kvs                            |
+--------------------------------+
5 rows in set (0.000 sec)

Ich habe das mit meiner Installation auf dem RPI verglichen, da sind es 28 Einträge.
Den Neuaufbau der DB habe ich bereits probiert. Es bleibt immer bei den 5 Einträgen und TL bleibt in der Fehlermeldung, dass es pos nicht finden kann, hängen.
