### ISSUE TITLE
All the URLs in the 'Dashboards' menu are absolute pathed.

### ISSUE THREAD

**Issue by Slyke** [bassmaster187/TeslaLogger#924]
** Append Logfile **
Not required

**Describe the bug**
Running on a Synology NAS inside Docker

My URL is: http://10.1.2.3:8888/admin/index.php?carid=2

All the URLs in the Dashboard menu (pointing to Grafana) are set to raspberry. Eg: http://raspberry:3000/d/Mlc06BiRk/Akku%20Trips

**To Reproduce**
1. Steps to reproduce the behavior:
2. Setup in docker.
3. Setup your credentials
4. Mouse over the 'Dashboard' menu.
5. Before clicking on a link, take note of the URL, then click.
6. Connection refused.

**Expected behavior**
URL should use my current domain: 10.1.2.3 (or whatever it is)

**Screenshots**
![image](https://user-images.githubusercontent.com/6442613/215472315-04cdcf3e-fcb8-4543-9a8d-d177c1fb564a.png)

** Teslalogger Type **
SynologyNAS/Docker
Did you update the Image with apt-get update & upgrade? No

** Do you use Tasker or iBeacon **
No

**Additional context**
v1.54.10

**Comment by bassmaster187** [comment]
Go to settings and change the URL for Grafana and Admin Panel

![image](https://user-images.githubusercontent.com/6816385/215971144-7ca2f9b4-60d5-4181-aa73-6692595e55be.png)
