### ISSUE TITLE
Wrong Kwh charged reported

### ISSUE THREAD

**Issue by Tobor7** [bassmaster187/TeslaLogger#937]
Hi,
I have found an error in the kwh charged field. In the example below, it is impossible to charge 36,56kw in 6 minutes on a Tesla gen 3. The 6 minutes is ok, but the 36,56kw is incorrect (should be near 0,3kw).
![image](https://user-images.githubusercontent.com/90622675/218277609-04f4d3fa-0906-4395-a031-c5319af088ca.png)
Tesla app report the right kwh (37kw for the day)
![image](https://user-images.githubusercontent.com/90622675/218277865-b7611652-4dcd-4d8a-98e5-def80f2ce44f.png)
The car was plugged all day with 2 charging session: One in the morning till 80% and one in the evening (car preheating) for 6 minutes.

**Comment by superfloh247** [comment]
please reboot your TL. it should combine those two charing entries into one with correct kWh charged
