### ISSUE TITLE
TotalSuperchargerStalls Koordinaten falsch

### ISSUE THREAD

**Issue by metawatchkalle** [bassmaster187/TeslaLogger#938]
Seit Version 1.54.12.0 werden die Nearby SUC's / TotalSuperchargerStalls falsch angezeigt. Obwohl ich in Deutschland sitze werden ausschließlich SUC's aus Spanien, Portugal und Marokko angezeigt. Die war in vorigen Versionen nicht so.
Beispiel-Ausschnitt aus dem Log:
"3.02.2023 05:55:01 : #1[Thread Pool Worker:10782]: UpdateDriveHeightStatistics(173): 1 rows updated
13.02.2023 05:59:30 : #1[NearbySuCServiceThread:22]: nearbySuCServiceOK 101
13.02.2023 05:59:31 : #1[NearbySuCServiceThread:22]: SuC sent: 10 **lat:49.964182 lng: 11.629153 - El Ejido, Spain**"

Die Koordinaten sollten aber in der Nähe von Bayreuth/Deutschland sein.

Hier noch ein Screenshot der TotalSuperchargerStalls:

![SUC](https://user-images.githubusercontent.com/4587701/218375498-47c2ce08-6faa-4db4-a2ea-6f0ef34e3d80.jpg)

**Comment by Utty88** [comment]
Ich habe das gleiche Problem, jedoch fing es bei mir schon am 10.02. um 06:55 Uhr an. Ich glaube, da war die Version 1.54.12 noch nicht released.

**Comment by metawatchkalle** [comment]
Ich hab auch nochmal das Logfile durchforstet: Bei mir ebenfalls ab 10.02.2023 um 03:27 Uhr der erste falsche Eintrag. Version war damals die 1.54.11.0

**Comment by tyson-112** [comment]
Bei mir auch, zwischen Leonberg und Murr wird mir Marrakesch angezeigt....
Hauptsächlich spanische und marokkanische.

**Comment by bassmaster187** [comment]
Das sollte mit der Version 1.54.13 behoben sein

**Comment by bassmaster187** [comment]
999d41b3f80f3abb30cd31e82a5cc76922f9eb8b
