### ISSUE TITLE
"Set Cost" aus Docker Installation nicht erreichbar

### ISSUE THREAD

**Issue by LeChuck11** [bassmaster187/TeslaLogger#941]
Beim Aufrufen der "Set Cost" Funktion aus Grafarna wird eine fehlerhafte URL aufgerufen. --> http://docker:8888/admin%20/chargingcost.php?id=1234

Ohne das Leerzeichen (%20) funktioniert es

**Comment by LeChuck11** [comment]
Das gleiche Verhalten zeigt sich beim Erstellen von Geofence Einträgen aus Grafarna heraus

**Comment by bassmaster187** [comment]
Kannst du bitte nochmal in Einstellungen den Link setzen. Da ist wohl noch ein Space am ende drin.

**Comment by LeChuck11** [comment]
Jawohl, das war es. Entschuldige, da habe ich nicht richtig geschaut.
