### ISSUE TITLE
Link vom Admin-Panel zum Dashboard fehlerhaft

### ISSUE THREAD

**Issue by sebitnt** [bassmaster187/TeslaLogger#964]
TeslaLogger läuft bei mir auf einem Raspberry, welcher jedoch nicht unter dem Namen "raspberry" erreichbar ist. In die Links vom Admin-Panel zu den Grafana Dashboards ist jedoch nicht die IP des Raspberrys oder dessen tatsächliche Netzwerkname eingesetzt, sondern immer der Name "raspberry", welcher dann natürlich nicht zu erreichen ist. Der Link ist dann z.B.
http://raspberry:3000/d/NjcHFGJGz/Available%20Supercharger%20Stalls%20Statistics
statt richtigerweise
http://192.168.0.10:3000/d/NjcHFGJGz/Available%20Supercharger%20Stalls%20Statistics
oder
http://meinserver:3000/d/NjcHFGJGz/Available%20Supercharger%20Stalls%20Statistics

Vielen Dank für das tolle Tool!

**Comment by albi** [comment]
Hatte ich auch mal. Restart schon gemacht? Cache vom Browser geleert?

**Comment by sebitnt** [comment]
Ein Restart bringt nichts. Ich habe aber mittlerweile herausgefunden, dass die Links in der Datei /etc/teslalogger/dashboardlinks.txt stehen. Dort habe ich sie geändert und nun funktioniert es wie gewünscht.
Trotzdem ist es ein Bug, da man ja nicht davon ausgehen kann, dass jeder Raspberry auch raspberry heißt. Eventuell wäre es besser, hier einfach in PHP $_SERVER['SERVER_ADDR'] zu nutzen.

**Comment by albi** [comment]
Aber in den Einstellungen hast du die richtige Adresse gesetzt? Denn dort musste ich auch hand anlegen und mein Raspi heisst auch nicht Raspberry. https://docs.google.com/gview?embedded=true&url=https://teslalogger.de/Teslalogger.pdf Seite 18 Punkt 3.11 dort siehst du das.

**Comment by sebitnt** [comment]
Hatte damit zwar schon einmal herumgespielt, jedoch wurden meine Änderungen nur in den bestehenden raspberry-link in der "Mitte" eingefügt. Offenbar muss man es jedoch komplett ersetzen. Ich habe nun das folgende eingetragen:
http://192.168.0.10:8888/admin/
http://192.168.0.10:3000/
Damit funktioniert es wunderbar. Danke!
