### ISSUE TITLE
Ladekosten zu Hause werden nach Neuinstallation vom Vorjahr übernommen…

### ISSUE THREAD

**Issue by albi** [bassmaster187/TeslaLogger#984]
Ich habe gestern nochmal eine saubere Installation vorgenommen, nachdem ich das nicht über git gemacht hatte. Dennoch hatte ich vorher eine funktionierende TeslaLogger Version laufen.

Nun ist mir aufgefallen, dass ich bei den Ladesession in diesem Jahr noch den niedrigeren Strompreis für zu Hause drin habe, welcher noch letztes Jahr galt. Ab 1.1.23 aber habe ich immer den höheren Strompreis eingegeben. Dieser war aber nach der Neuinstallation nicht mehr gespeichert und es nahm den alten.

Kann es sein dass die Copy Charging Costs Funktion nicht den letzten Ladevorgang als Referenz ranzieht? Das Phänomen hatte ich jetzt bereits das zweite mal, dass ich diese Preise manuell korrigieren musste.

Habe ganz normal meine Datenbank vorher gespeichert und nach Anleitung wiederhergestellt. Ebenso meine Geofence Datei an den richtigen Ort gelegt.

**Comment by superfloh247** [comment]
Du kannst den DEBUG-Log anmachen, dann lässt sich evtl. was im Logfile nachvollziehen

/etc/teslalogger/TeslaLogger.exe.config

um diesen Block erweitern, einfach zu den andern Settings dazu

```
      <setting name="VerboseMode" serializeAs="String">
        <value>True</value>
      </setting>
```

<img width="421" alt="Bildschirm­foto 2023-03-29 um 13 40 49" src="https://user-images.githubusercontent.com/26180993/228524574-6358ce39-180b-4d3c-b496-5907988e5442.png">

**Comment by albi** [comment]
Ist das nicht grad zu spät dafür? Habe ja alles korrigiert. Die SQL Abfrage kann ich leider nicht übersetzen für mich. Sieht aber nicht so verkehrt aus.

Das Ding ist, ich habe das nun schon das zweite mal festgestellt. Ist praktisch meine 3. Installation von Teslalogger. Bei Installation 2 und 3 ist dieses Phänomen aufgetaucht.

**Comment by superfloh247** [comment]
aktuellen Zustand backup'en, verbose Mode anmachen, altes Backup einspielen und schauen, welche Referenzladevorgänge für deine Ladungen herangezogen werden.

**Comment by albi** [comment]
Phew, da musst du mich dann durchführen. Bin grad nur mächtig im Stress im Büro und auch Abends am Arbeiten. Kann ich dich hier einfach anschreiben wenn ich das machen würde? Kann da gern behilflich sein. Anfang des Jahres ist es noch einfacher die richtigen Preise nachzutragen. Aber je mehr ich lade um so mehr Arbeit hab ich damit das wieder zu korrigieren.

**Comment by superfloh247** [comment]
Immer mit der Ruhe :)

Man könnte es vermutlich auch mit einem alten Backup von dir nachvollziehen, ich hab aber keine Entwicklungslandschaft für andere Installationen und möchte auch gar keine andern Datenbanken haben. Geht mich nix an.

Vielleicht kann @bassmaster187 da was machen.

**Comment by albi** [comment]
Blöde Frage: Wenn ich einfach in einen neuen Ordner aufm Raspi TeslaLogger installiere, hat das dann eine eigene Datenbank? Das wäre ja dann einfach für mich. Dann müsste ich nicht die bestehende Installation anfassen. Ich müsste vermutlich das Docker Image stoppen, richtig?

**Comment by HanSolo72** [comment]
Ich kann den Fehler auch reproduzieren. Es reicht, auf Update zu drücken. Ich hatte mich schon vor einigen Wochen über falsche Preise gewundert und die Preise angepasst, jetzt sind sie schon wieder weg. Habe jetzt zum Test beim neusten Eintrag (ID = 396) 35 Cent eingetragen, dann auf Update gedrückt. Voila: Überschrieben mit dem alten Preis aus 2022, wie bei allen anderen Datensätzen auch. Vielleicht sollte er nur dann updaten, wenn Preis (cost_per_kwh) null ist (nicht 0).

Hier ein Teil des Verbose Logs:
31.03.2023 00:49:34 : #2[DBUpdaterThread:17]: UpdateChargeEnergyAdded(396): 1 rows updated to charge_energy_added 13.36
31.03.2023 00:49:34 : #2[DBUpdaterThread:17]: CopyChargePrice enabled for '🔌 🏠 Zuhause'
31.03.2023 00:49:34 : #2[DBUpdaterThread:17]: CopyChargePrice: reference charging session found for '🔌 🏠 Zuhause', ID 395 - cost_per_kwh:0.2348 cost_per_session:0 cost_per_minute:0
31.03.2023 00:49:34 : #2[DBUpdaterThread:17]: UpdateChargePrice id:396 cost_per_kwh:14.83kWh * 0.2348 = 3.482084
31.03.2023 00:49:34 : #2[DBUpdaterThread:17]: UpdateChargePrice: 1 rows updated to cost_per_kwh 0.2348
31.03.2023 00:49:34 : #2[DBUpdaterThread:17]: UpdateChargePrice id:396 cost_per_minute:104.233333333333min * 0 = 0
31.03.2023 00:49:34 : #2[DBUpdaterThread:17]: UpdateChargePrice: 1 rows updated to cost_per_minute 0
31.03.2023 00:49:34 : #2[DBUpdaterThread:17]: UpdateChargePrice id:396 cost_per_session:0
31.03.2023 00:49:34 : #2[DBUpdaterThread:17]: UpdateChargePrice: 1 rows updated to cost_per_session 0
31.03.2023 00:49:34 : #2[DBUpdaterThread:17]: UpdateChargePrice id:396 cost_total:3.482084
31.03.2023 00:49:34 : #2[DBUpdaterThread:17]: UpdateChargePrice: 1 rows updated to cost_total 3.482084

**Comment by superfloh247** [comment]
Oh, jetzt hab ich ne Idee, warum das passiert, danke!

**Comment by HanSolo72** [comment]
Danke, der Fehler ist jetzt weg. Kurze Frage: Wo merkt er sich das denn? Ich sehe keine entsprechende Spalte in der Tabelle chargingstate.

Ich möchte hier noch mein SQL-Statement teilen, um die falschen Daten anzupassen. Preis, Datum, Ladeanschrift und CarID müssen halt noch angepasst werden:
SET @kwhprice=.2349;
UPDATE chargingstate, pos
SET	chargingstate.cost_per_kwh = @kwhprice,
	chargingstate.cost_total = chargingstate.cost_kwh_meter_invoice*@kwhprice
WHERE
	chargingstate.pos = pos.id
	AND cost_kwh_meter_invoice is not null
	AND pos.address like '🔌 🏠 Zuhause'
	AND chargingstate.StartDate between '2022-10-01' and '2023-01-01'
	AND chargingstate.CarID = 1

**Comment by superfloh247** [comment]
da merkt er sich das https://github.com/superfloh247/TeslaLogger/blob/40cf80cfd2d3208de82bce0cce64e154a7f453ae/TeslaLogger/DBHelper.cs#L555

**Comment by albi** [comment]
Kann das schneller released werden? Ich habe gerade wieder nach einem Restart von TeslaLogger alle Heimladevorgänge anzupassen aus diesem Jahr.

**Comment by albi** [comment]
@HanSolo72 

Wo kann ich das SQL Statement eingeben? Sorry für die n00b Frage. Aber ich müsste grad zig Einträge anpassen.

**Comment by HanSolo72** [comment]
Wenn ich das richtig sehe, wurde für diese Änderung noch nicht einmal ein pull request erstellt. Kannst Du das bitte machen, @superfloh247?

@albi: Das SQL kannst Du entweder in phpMyAdmin oder HeidiSQL ausführen. Ich empfehle HeidiSQL. Aber ich weiß nicht, ob Du so einfach von außen auf die DB kommst, ohne vorher Rechte anzupassen. Kann Dir hier aber keinen Crashkurs in MariaDB geben.

**Comment by albi** [comment]
@HanSolo72 das ist mir soweit klar, aber ich weiss nicht wie das mit dem docker image geht. oder muss phpMYAdmin auf dem Raspi installiert sein? Ist es schon im Docker image und wenn ja wie komme ich da ran?

**Comment by HanSolo72** [comment]
Sorry, das weiß ich auch nicht. Ich habe die DB auf einem eigenen DB-Server installiert. Da wirst Du Dich durchgoogeln müssen. Vielleicht hilft Dir das hier weiter: https://stackoverflow.com/questions/52421469/how-to-open-mysql-database-from-docker-container-in-my-local-heidisql#52422317

**Comment by albi** [comment]
Scheint jetzt zu gehen wenn ich mich nicht täusche.
