### ISSUE TITLE
Fahrt wurde nicht aufgezeichnet/ anschließende Ladung am falschen Ort

### ISSUE THREAD

**Issue by germangolfer** [bassmaster187/TeslaLogger#990]
[**](url) Append Logfile **
you find it here: \\raspberry\teslalogger\nohup.out

**Describe the bug**
15:50 Uhr von der Arbeit (Paderborn) nach Hause gefahren und anschließen ab ca 16:55 Uhr an der Wallbox zu hause (Dortmund) geladen.
Da schon gesehen das die Fahrt komplett fehlt und der Kilometerstand nicht stimmt.
Nach dem Laden wird in der Statistik angezeigt das ich auf der Arbeit geladen habe.
Teslalogger restart durchgeführt. Kilometerstand passt, Rest fehlt

**To Reproduce**

**Expected behavior**

**Screenshots**
[logfile.txt](https://github.com/bassmaster187/TeslaLogger/files/11254790/logfile.txt)

** Teslalogger Type **
 Raspberry Pi4
Did you update the Image with apt-get update & upgrade?

** Do you use Tasker or iBeacon **

**Additional context**

**Comment by germangolfer** [comment]
![IMG_0073](https://user-images.githubusercontent.com/131033746/232582707-114f3a1a-a55e-4159-907e-ed40ea122ef9.jpeg)

**Comment by superfloh247** [comment]
17.4. losgefahren:
17.04.2023 07:31:11 : Distance: 0.481735566319755 - Radius: 30 - 🔌 🏠 HOME
17.04.2023 07:31:11 : #1[Car_1:20]: change TeslaLogger state: Start -> Online
17.04.2023 07:31:33 : #1[Car_1:20]: ShiftStateChange: P -> D
17.04.2023 07:31:33 : #1[Car_1:20]: change TeslaLogger state: Online -> Drive

17.4. angekommen:
17.04.2023 08:38:00 : #1[Car_1:20]: ShiftStateChange: D -> P
17.04.2023 08:38:00 : #1[Car_1:20]: change TeslaLogger state: Drive -> Start
17.04.2023 08:38:00 : Distance: 12.824299045862 - Radius: 20 - 💼 Work
17.04.2023 08:38:01 : #1[Car_1:20]: change TeslaLogger state: Start -> Online

das kommt mir komisch vor
17.04.2023 08:38:12 : #1[Car_1:20]: change TeslaLogger state: Start -> Online
17.04.2023 08:38:35 : #1[Car_1:20]: change TeslaLogger state: Start -> Online
17.04.2023 09:04:51 : #1[Car_1:20]: change TeslaLogger state: Start -> Online

hier passt es wieder
17.04.2023 09:31:03 : #1[Car_1:20]: change TeslaLogger state: Start -> Sleep
17.04.2023 09:31:03 : Distance: 12.824299045862 - Radius: 20 - 💼 Work
17.04.2023 09:31:03 : #1[Car_1:20]: state: asleep

17.04.2023 11:03:19 : IsOnline: Connection reset by peer
17.04.2023 11:36:30 : #1[Thread Pool Worker:72775]: UpdateRefreshToken
17.04.2023 11:36:30 : #1[Thread Pool Worker:72775]: UpdateRefreshToken OK: 1
17.04.2023 11:36:30 : #1[Thread Pool Worker:72775]: UpdateTeslaToken
17.04.2023 11:36:30 : #1[Thread Pool Worker:72775]: update tesla_token OK: 1


steaming API startet neu:
17.04.2023 11:36:31 : #1[StreamAPIThread_1:72805]: StartStream

15:50 Uhr von der Arbeit (Paderborn) nach Hause gefahren und anschließen ab ca 16:55 Uhr an der Wallbox zu hause (Dortmund) geladen.

Die Fahrt fehlt komplett, weder streaming API noch Classic API haben was gemerkt

17.04.2023 16:56:46 : #1[Car_1:20]: change TeslaLogger state: Sleep -> Start
17.04.2023 16:56:46 : Distance: 12.824299045862 - Radius: 20 - 💼 Work
17.04.2023 16:56:46 : #1[Car_1:20]: change TeslaLogger state: Start -> Online
17.04.2023 16:56:46 : Distance: 12.824299045862 - Radius: 20 - 💼 Work
17.04.2023 16:56:46 : #1[Car_1:20]: state: online
17.04.2023 16:57:02 : #1[Car_1:20]: change TeslaLogger state: Online -> Charge

bei Ladebeginn wird extra nochmal eine neue Position bestimmt:
17.04.2023 16:57:32 : #1[Thread Pool Worker:73636]: StartChargingState Task distance: 0

Abweichung: 0, also korrekt laut Tesla

Ladung beendet:
17.04.2023 19:26:05 : #1[Car_1:20]: change TeslaLogger state: Charge -> Start
17.04.2023 19:26:05 : #1[Car_1:20]: UpdateChargeEnergyAdded(1637): 1 rows updated to charge_energy_added 25.82
17.04.2023 19:26:05 : Distance: 12.824299045862 - Radius: 20 - 💼 Work
17.04.2023 19:26:06 : #1[Car_1:20]: change TeslaLogger state: Start -> Online

immer noch "auf Arbeit"
17.04.2023 19:52:47 : Distance: 12.824299045862 - Radius: 20 - 💼 Work
17.04.2023 19:54:17 : Distance: 12.824299045862 - Radius: 20 - 💼 Work

Update gedrückt
17.04.2023 20:00:52 : UPDATE request!

Update gemacht
17.04.2023 20:02:15 : update package: download and unzip successful

Reboot nach Update
17.04.2023 20:02:45 : TeslaLogger Version: 1.54.18.0

Auto ist noch am Arbeitsplatz
17.04.2023 20:02:57 : Distance: 12.824299045862 - Radius: 20 - 💼 Work

warum das?
17.04.2023 20:05:46 : Reboot request!

Auto zu Hause
17.04.2023 20:06:18 : Distance: 3.56942165025241 - Radius: 30 - 🔌 🏠 HOME


Ich tippe auf Fehler bei Tesla, da hatte ein Tesla-Server Schluckauf.

Hast du mal Grafana "Mothership" vom 17.4. 8:30 - 17:30 für uns?

**Comment by germangolfer** [comment]
Hi, danke für die schnelle Rückmeldung. anbei der Screenshot vom Mothership. Hoffe das reicht so…..wüsste adhoc nicht wie ist anders beistellen kann. Aber wie du schon sagst….die Abfahrt von „work“ fehlt komplett.
![IMG_0076](https://user-images.githubusercontent.com/131033746/232861785-b97fbd55-0421-4d49-b80f-51f8a5d800ba.jpeg)

**Comment by superfloh247** [comment]
IsOnline() wurde im betreffenden Zeitraum ausgeführt und hatte keine Fehler. Also weder offline noch timeout noch Netzwerkprobleme.

Server-Schluckauf bei Tesla  ¯\_(ツ)_/¯

**Comment by germangolfer** [comment]
vielen Dank für den schnell Support. Close :-)
