### ISSUE TITLE
Using TeslaLogger with existing Grafana Host in Docker HowTo

### ISSUE THREAD

**Issue by soulfire89** [bassmaster187/TeslaLogger#992]
**Is your feature request related to a problem? Please describe.**
Starting teslalogger_grafana_1     ... error
WARNING: Host is already in use by another container

ERROR: for teslalogger_grafana_1  Cannot start service grafana: driver failed programming external connectivity on endpoint teslalogger_grafana_1 (82a311da9f30f15bc10e100f5ddcf1e276c2eb78d75bc270284b3ac41bd49394): Bind for 0.0.0.0:3000 failStarting teslalogger_teslalogger_1 ... done

ERROR: for grafana  Cannot start service grafana: driver failed programming external connectivity on endpoint teslalogger_grafana_1 (82a311da9f30f15bc10e100f5ddcf1e276c2eb78d75bc270284b3ac41bd49394): Bind for 0.0.0.0:3000 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

**Describe the solution you'd like**
Using TeslaLogger with existing Grafana Host inside Docker on Synology NAS

**Additional context**
Please provide needed changes to config files for using alternative grafana host.

**Comment by bassmaster187** [comment]
Use a different port in your docker-compose.yml file.
e.g. 3001

![image](https://user-images.githubusercontent.com/6816385/233620814-ead09ae7-70e6-44e3-b5b6-6b0ef9b27aa3.png)

**Comment by soulfire89** [comment]
Will it be possible to use all the dashboards inside my existing grafana instance with a second database on mysql which is located at localhost:3000 or is it then needed to run two parallel grafana instances?

**Comment by bassmaster187** [comment]
I won't recommend it, because Teslalogger needs a specific version to run smooth. With the newest version of Grafana, there are many bugs in Grafana in which we are running trough.
