### ISSUE TITLE
Home screen does not update anymore ( since 27.April at 22:05 )

### ISSUE THREAD

**Issue by Maddimax** [bassmaster187/TeslaLogger#996]
There seem to be a bunch of errors in the log files. Maybe Tesla changed the API?

** Log File **
[tllog.txt](https://github.com/bassmaster187/TeslaLogger/files/11351440/tllog.txt)

** Teslalogger Type **
Docker

** Do you use Tasker or iBeacon **
No

**Comment by ostorezio** [comment]
Same problem here.
This morning, after upgrade to 1.54.15 the home page was empty of data, and the apache log showed lots of errors like this:

`[Fri Apr 28 10:25:01.212694 2023] [php7:warn] [pid 11044] [client 10.1.1.64:58031] PHP Warning:  file_get_contents(http://localhost:5000/currentjson/1): failed to open stream: Connection refused in /var/www/html/admin/current_json.php on line 12, referer: https://10.1.1.65/admin/index.php?carid=1`

I tried a wget connection to the URL, like so:

`$ wget http://localhost:5000/currentjson/1
--2023-04-28 10:25:56--  http://localhost:5000/currentjson/1
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:5000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:5000... failed: Connection refused.
`
So, there seemed to be a problem with the process running on port 5000.

I rebooted the RPi and now I get the problem reported by Maddimax.

HTH,
                Ezio

**Comment by albi** [comment]
got the same problem. no updates since 26.4.

the car is online in the tesla app, but not for teslalogger

**Comment by Trekster2000** [comment]
Same issue here since last night. Woke up to an car offline that can be accessed via tesla app.

Log shows a bunch of 404 not found when trying to access the car via API.

**Comment by rowich** [comment]
Same here. Charging session started at 22:30 was not recorded anymore, the trip ended ~18:00 is there.

**Comment by ostorezio** [comment]
> This morning, after upgrade to 1.54.15 t

Sorry, I meant upgrade to 1.54.18 of teslalogger.

**Comment by bassmaster187** [comment]
should be fixed in new version
https://github.com/bassmaster187/TeslaLogger/commit/6d26a61a1f31a518ad67f6ad3baa9577224dcf57

**Comment by Maddimax** [comment]
Awesome work, it works again, thanks!

I'm seeing this still in the log (the isCharging=NULL is colored red):

```
28.04.2023 19:17:25 : UpdateCO2 finish
28.04.2023 19:17:25 : RunHousekeepingInBackground finished, took 8416.143ms
28.04.2023 19:19:13 : #1[Thread Pool Worker:39]: Result.Statuscode: 408 (RequestTimeout) cmd: vehicle_data
28.04.2023 19:19:18 : #1[Car_1:23]: isCharging = NULL

28.04.2023 19:21:51 : #1[Car_1:23]: change TeslaLogger state: Online -> Start
```
