### ISSUE TITLE
Teslalogger reports "Car offline", last charging missed, last drive is reported

### ISSUE THREAD

**Issue by rowich** [bassmaster187/TeslaLogger#997]
** Append Logfile **
28.04.2023 12:19:40 : #1[StreamAPIThread_1:164]: StartStream
28.04.2023 12:19:40 : #1[Thread Pool Worker:159]: Result.Statuscode: 404 (NotFound) cmd: drive_state Retry: 1
28.04.2023 12:19:40 : #1[Thread Pool Worker:33]: Result.Statuscode: 404 (NotFound) cmd: vehicle_state Retry: 5
28.04.2023 12:19:41 : #1[Car_1:162]: IsDriving = NULL!
28.04.2023 12:19:44 : #1[Car_1:151]: *** Exit Loop !!!
28.04.2023 12:19:46 : #1[Thread Pool Worker:41]: Result.Statuscode: 404 (NotFound) cmd: drive_state Retry: 6
28.04.2023 12:19:47 : #1[Thread Pool Worker:41]: Restart Car 1
28.04.2023 12:19:47 : #1[Thread Pool Worker:41]: Request StopStreaming
28.04.2023 12:19:47 : #1[Thread Pool Worker:41]: ExitCarThread: 404 Error
28.04.2023 12:19:47 : Start Car 1
28.04.2023 12:19:47 : #1[RestartThread_1:165]: CheckUseTaskerToken
28.04.2023 12:19:47 : #1[ScanMyTesla_1:156]: Scanmytesla: Thread was being aborted.
28.04.2023 12:19:47 : #1[StreamAPIThread_1:157]: StartStream Ende
28.04.2023 12:19:48 : #1[RestartThread_1:165]: LastTaskerToken: 2021-02-20 13:02:25 Stop using fast TaskerToken request!
28.04.2023 12:19:48 : #1[Car_1:166]: GetAvgConsumption: sumkm: 23116.7; avgkm: 153.1; kwh/100km: 17.1; avgsocdiff: 36.8; maxkm: 437
28.04.2023 12:19:48 : #1[Car_1:166]: Restore Token OK. Age: 4/28/2023 6:49:28 AM
28.04.2023 12:19:48 : #1[Car_1:166]: TOKEN: XyJ...X2nX
28.04.2023 12:19:48 : #1[Car_1:166]: display_name: NCC-1031
28.04.2023 12:19:48 : #1[Car_1:166]: vin: 5YJ3E7EB6KFXXXXXX
28.04.2023 12:19:48 : #1[Car_1:166]: id: X49X9XX10XX7X71X
28.04.2023 12:19:48 : #1[Car_1:166]: vehicle_id: X02X8XX26X
28.04.2023 12:19:48 : #1[Car_1:166]: Tasker Config:
Server Port: https://teslalogger.de/
Path: wakeup.php
Attribute: t=b6c9ea3d
28.04.2023 12:19:48 : #1[ScanMyTesla_1:167]: Start ScanMyTesla Thread!
28.04.2023 12:19:48 : #1[Car_1:166]: Economy from DB: 0.152 Wh/km - count: 106
28.04.2023 12:19:48 : #1[Car_1:166]: Streamingtoken: X54XdXXf5XXfXbcX
28.04.2023 12:19:51 : #1[Thread Pool Worker:159]: Result.Statuscode: 404 (NotFound) cmd: charge_state Retry: 1
28.04.2023 12:19:52 : #1[Car_1:162]: isCharging = NULL
28.04.2023 12:19:52 : #1[Thread Pool Worker:95]: Result.Statuscode: 404 (NotFound) cmd: climate_state Retry: 1
28.04.2023 12:19:53 : Reverse geocoding by Nominatim27
28.04.2023 12:19:53 : #1[Car_1:166]: Country Code: ch
28.04.2023 12:19:53 : #1[Car_1:166]: Voltage at 50% SOC:0V Date:10/13/2022 5:05:28 PM
28.04.2023 12:19:53 : #1[Thread Pool Worker:95]: GetOutsideTempAsync: NULL
28.04.2023 12:19:53 : #1[Car_1:166]: Car: M3 LR - 0.152 Wh/km
28.04.2023 12:19:53 : #1[Car_1:166]: VIN decoder: Model 3 2019 AWD:True MIC:False battery:NMC motor:3 dual MIG:False
28.04.2023 12:19:53 : #1[Car_1:166]: Vehicle Config: car_type:'model3' car_special_type:'base' trim_badging:'74d'
28.04.2023 12:19:53 : #1[Car_1:166]: No meter config
28.04.2023 12:19:53 : #1[StreamAPIThread_1:168]: StartStream
28.04.2023 12:19:53 : #1[Thread Pool Worker:95]: Result.Statuscode: 404 (NotFound) cmd: drive_state Retry: 1
28.04.2023 12:19:54 : #1[Car_1:166]: IsDriving = NULL!
28.04.2023 12:19:57 : #1[Car_1:155]: *** Exit Loop !!!
28.04.2023 12:20:02 : #1[Thread Pool Worker:117]: Result.Statuscode: 404 (NotFound) cmd: vehicle_state Retry: 1
28.04.2023 12:20:04 : #1[Thread Pool Worker:142]: Result.Statuscode: 404 (NotFound) cmd: charge_state Retry: 1
28.04.2023 12:20:05 : #1[Car_1:166]: isCharging = NULL
28.04.2023 12:20:05 : #1[Thread Pool Worker:117]: Result.Statuscode: 404 (NotFound) cmd: climate_state Retry: 1
28.04.2023 12:20:06 : #1[Thread Pool Worker:117]: GetOutsideTempAsync: NULL
28.04.2023 12:20:08 : #1[Thread Pool Worker:27]: Result.Statuscode: 404 (NotFound) cmd: drive_state Retry: 2
28.04.2023 12:20:09 : #1[Car_1:162]: IsDriving = NULL!

(unable to add the log here - maybe I am stupid...)

**Describe the bug**
Last drive (yesterday) was reported
Last charging session (yesterday night) is missing
Admin panel reports "Offline"
App is able to connect and shows last charging session (cable still connected)
2 restarts of the Raspi4 did not solved the issue that car is shown as offline

![image](https://user-images.githubusercontent.com/49855876/235121948-d132283a-c17c-4032-9ad7-6c8a7ce45174.png)

** Teslalogger Type **
Raspberry Pi4
Did you update the Image with apt-get update & upgrade? No.

** Do you use Tasker or iBeacon **
Configured, not in use right now

**Comment by albi** [comment]
same as… https://github.com/bassmaster187/TeslaLogger/issues/996

**Comment by rowich** [comment]
dupe report accepted. Closed.

**Comment by rowich** [comment]
ups, 996 was closed also. Reopening this one.

**Comment by rowich** [comment]
works again with 1.54.19.0. As said for #996 : Awesome work!
